<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Generalized linear models | BMA / ST 590 computing companion</title>
  <meta name="description" content="This is a proto-textbook for BMA / ST 590, Statistical Modeling in Ecology, taught at NCSU in Fall 2023." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Generalized linear models | BMA / ST 590 computing companion" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a proto-textbook for BMA / ST 590, Statistical Modeling in Ecology, taught at NCSU in Fall 2023." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Generalized linear models | BMA / ST 590 computing companion" />
  
  <meta name="twitter:description" content="This is a proto-textbook for BMA / ST 590, Statistical Modeling in Ecology, taught at NCSU in Fall 2023." />
  

<meta name="author" content="Kevin Gross" />


<meta name="date" content="2023-09-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hierarchical-mixed-models.html"/>
<link rel="next" href="generalized-linear-mixed-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Maximum likelihood estimation</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#mathematical-basics"><i class="fa fa-check"></i><b>1.1</b> Mathematical basics</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#horse-kick-data"><i class="fa fa-check"></i><b>1.2</b> Horse-kick data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#calculate-and-plot-the-log-likelihood-function"><i class="fa fa-check"></i><b>1.2.1</b> Calculate and plot the log-likelihood function</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#find-the-mle-numerically-using-optimize"><i class="fa fa-check"></i><b>1.2.2</b> Find the MLE numerically using ‘optimize’</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#pulse-rate-data"><i class="fa fa-check"></i><b>1.3</b> Pulse rate data</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#tadpole-data"><i class="fa fa-check"></i><b>1.4</b> Tadpole data</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#transformable-constraints"><i class="fa fa-check"></i><b>1.5</b> Transformable constraints</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><i class="fa fa-check"></i><b>2</b> Beyond the MLE: Confidence regions and hypothesis tests using the likelihood function</a>
<ul>
<li class="chapter" data-level="2.1" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#confidence-intervals-for-single-parameters"><i class="fa fa-check"></i><b>2.1</b> Confidence intervals for single parameters</a></li>
<li class="chapter" data-level="2.2" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#two-param-mle"><i class="fa fa-check"></i><b>2.2</b> Confidence regions, profile likelihoods, and associated univariate intervals</a></li>
<li class="chapter" data-level="2.3" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#locally-quadratic-approximations-to-confidence-intervals-and-regions"><i class="fa fa-check"></i><b>2.3</b> Locally quadratic approximations to confidence intervals and regions</a></li>
<li class="chapter" data-level="2.4" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#comparing-models-likelihood-ratio-test-and-aic"><i class="fa fa-check"></i><b>2.4</b> Comparing models: Likelihood ratio test and AIC</a></li>
<li class="chapter" data-level="2.5" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#the-negative-binomial-distriution-revisited"><i class="fa fa-check"></i><b>2.5</b> The negative binomial distriution, revisited</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bayesian-computation.html"><a href="bayesian-computation.html"><i class="fa fa-check"></i><b>3</b> Bayesian computation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bayesian-computation.html"><a href="bayesian-computation.html#computations-with-conjugate-priors"><i class="fa fa-check"></i><b>3.1</b> Computations with conjugate priors</a></li>
<li class="chapter" data-level="3.2" data-path="bayesian-computation.html"><a href="bayesian-computation.html#jags-in-r"><i class="fa fa-check"></i><b>3.2</b> JAGS in R</a></li>
<li class="chapter" data-level="3.3" data-path="bayesian-computation.html"><a href="bayesian-computation.html#rstanarm"><i class="fa fa-check"></i><b>3.3</b> rstanarm</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="smooth-regression.html"><a href="smooth-regression.html"><i class="fa fa-check"></i><b>4</b> Smooth regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="smooth-regression.html"><a href="smooth-regression.html#loess-smoothers"><i class="fa fa-check"></i><b>4.1</b> Loess smoothers</a></li>
<li class="chapter" data-level="4.2" data-path="smooth-regression.html"><a href="smooth-regression.html#splines"><i class="fa fa-check"></i><b>4.2</b> Splines</a></li>
<li class="chapter" data-level="4.3" data-path="smooth-regression.html"><a href="smooth-regression.html#generalized-additive-models-gams"><i class="fa fa-check"></i><b>4.3</b> Generalized additive models (GAMs)</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="generalized-least-squares.html"><a href="generalized-least-squares.html"><i class="fa fa-check"></i><b>5</b> Generalized Least Squares</a>
<ul>
<li class="chapter" data-level="5.1" data-path="generalized-least-squares.html"><a href="generalized-least-squares.html#heterogeneous-variance"><i class="fa fa-check"></i><b>5.1</b> Heterogeneous variance</a></li>
<li class="chapter" data-level="5.2" data-path="generalized-least-squares.html"><a href="generalized-least-squares.html#temporal-serial-correlation"><i class="fa fa-check"></i><b>5.2</b> Temporal (serial) correlation</a></li>
<li class="chapter" data-level="5.3" data-path="generalized-least-squares.html"><a href="generalized-least-squares.html#spatial-data"><i class="fa fa-check"></i><b>5.3</b> Spatial data</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html"><i class="fa fa-check"></i><b>6</b> Hierarchical (mixed) models</a>
<ul>
<li class="chapter" data-level="6.1" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#one-factor-layout-dyestuff-data"><i class="fa fa-check"></i><b>6.1</b> One-factor layout: Dyestuff data</a></li>
<li class="chapter" data-level="6.2" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#bayesian-analysis"><i class="fa fa-check"></i><b>6.2</b> Bayesian analysis</a></li>
<li class="chapter" data-level="6.3" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#negative-within-group-correlations"><i class="fa fa-check"></i><b>6.3</b> Negative within-group correlations</a></li>
<li class="chapter" data-level="6.4" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#random-coefficient-models-rikz-data"><i class="fa fa-check"></i><b>6.4</b> Random coefficient models: RIKZ data</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#analysis-without-beach-level-covariate"><i class="fa fa-check"></i><b>6.4.1</b> Analysis without beach-level covariate</a></li>
<li class="chapter" data-level="6.4.2" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#adding-a-beach-level-covariate"><i class="fa fa-check"></i><b>6.4.2</b> Adding a beach-level covariate</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#nested-and-crossed-random-effects"><i class="fa fa-check"></i><b>6.5</b> Nested and crossed random effects</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#nested-random-effects"><i class="fa fa-check"></i><b>6.5.1</b> Nested random effects</a></li>
<li class="chapter" data-level="6.5.2" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#crossed-random-effects"><i class="fa fa-check"></i><b>6.5.2</b> Crossed random effects</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>7</b> Generalized linear models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression"><i class="fa fa-check"></i><b>7.1</b> Poisson regression</a></li>
<li class="chapter" data-level="7.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#bayesian-interlude"><i class="fa fa-check"></i><b>7.2</b> Bayesian interlude</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#rstanarm-1"><i class="fa fa-check"></i><b>7.2.1</b> rstanarm</a></li>
<li class="chapter" data-level="7.2.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#posterior-predictive-checks"><i class="fa fa-check"></i><b>7.2.2</b> Posterior predictive checks</a></li>
<li class="chapter" data-level="7.2.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#jags"><i class="fa fa-check"></i><b>7.2.3</b> JAGS</a></li>
<li class="chapter" data-level="7.2.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#observation-level-random-effects"><i class="fa fa-check"></i><b>7.2.4</b> Observation-level random effects</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#binary-responses"><i class="fa fa-check"></i><b>7.3</b> Binary responses</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#individual-binary-responses-tb-in-boar"><i class="fa fa-check"></i><b>7.3.1</b> Individual binary responses: TB in boar</a></li>
<li class="chapter" data-level="7.3.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#grouped-binary-data-industrial-melanism"><i class="fa fa-check"></i><b>7.3.2</b> Grouped binary data: Industrial melanism</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-adjusted-models-for-count-data"><i class="fa fa-check"></i><b>7.4</b> Zero-adjusted models for count data</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-truncated-models"><i class="fa fa-check"></i><b>7.4.1</b> Zero-truncated models</a></li>
<li class="chapter" data-level="7.4.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-inflated-models"><i class="fa fa-check"></i><b>7.4.2</b> Zero-inflated models</a></li>
<li class="chapter" data-level="7.4.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-altered-or-hurdle-models"><i class="fa fa-check"></i><b>7.4.3</b> Zero-altered, or “hurdle”, models</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#generalized-additive-models-gams-1"><i class="fa fa-check"></i><b>7.5</b> Generalized additive models (GAMs)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html"><i class="fa fa-check"></i><b>8</b> Generalized linear mixed models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#example-1-industrial-melanism-data"><i class="fa fa-check"></i><b>8.1</b> Example 1: Industrial melanism data</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#gees"><i class="fa fa-check"></i><b>8.1.1</b> GEEs</a></li>
<li class="chapter" data-level="8.1.2" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#glmms"><i class="fa fa-check"></i><b>8.1.2</b> GLMMs</a></li>
<li class="chapter" data-level="8.1.3" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#bayesian-fit"><i class="fa fa-check"></i><b>8.1.3</b> Bayesian fit</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#example-2-ticks-on-red-grouse"><i class="fa fa-check"></i><b>8.2</b> Example 2: Ticks on red grouse</a></li>
<li class="chapter" data-level="8.3" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#gamms"><i class="fa fa-check"></i><b>8.3</b> GAMMs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i>Bibliography</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BMA / ST 590 computing companion</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="generalized-linear-models" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Generalized linear models<a href="generalized-linear-models.html#generalized-linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Generalized linear modes allow us to extend the machinery of the “general linear model” (regression and ANOVA) to data sets in which the response variable may have a non-Gaussian distribution. Generalized linear models do not encompass all possible distributions for the response variable. Instead, the distribution of the response variable must belong to a group of distributions known as the “exponential family”. (Note that there is also such a thing as an exponential distribution. The exponential distribution is one of the distributions in the exponential family, but it is not the only one.) The exponential family of distributions includes many of the distributions that we encounter in practical data analysis, including Poisson, negative binomial, binomial, gamma, and beta distributions. The Gaussian distribution is included in the exponential family as well. One notable distribution that is not part of the exponential family is the <span class="math inline">\(t\)</span>-distribution. Distributions in the exponential family all give rise to likelihoods that share the same general form, and thus can be handled with a unified fitting scheme.</p>
<p>In practice, logistic regression (with binomial responses) and Poisson regression are far and away the two most common forms of generalized linear models that one encounters.</p>
<div id="poisson-regression" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Poisson regression<a href="generalized-linear-models.html#poisson-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We will begin with an example of Poisson regression. These data are originally from Poole, Anim. Behav. 37 (1989):842-49, and were analyzed in the second edition of Ramsey &amp; Schafer’s <em>Statistical Sleuth</em>. They describe an observational study of 41 male elephants over 8 years at Amboseli National Park in Kenya. Each record in this data set gives the age of a male elephant at the beginning of a study and the number of successful matings for the elephant over the study’s duration. The number of matings is a count variable. Our goal is to characterize how the number of matings is related to the elephant’s age. We’ll start by fitting a model with the canonical log link.</p>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="generalized-linear-models.html#cb532-1" aria-hidden="true" tabindex="-1"></a>elephant <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/elephant.txt&quot;</span>, <span class="at">head =</span> T)</span>
<span id="cb532-2"><a href="generalized-linear-models.html#cb532-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(elephant)</span></code></pre></div>
<pre><code>##   age matings
## 1  27       0
## 2  28       1
## 3  28       1
## 4  28       1
## 5  28       3
## 6  29       0</code></pre>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="generalized-linear-models.html#cb534-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age))</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="sourceCode" id="cb535"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb535-1"><a href="generalized-linear-models.html#cb535-1" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(matings <span class="sc">~</span> age, </span>
<span id="cb535-2"><a href="generalized-linear-models.html#cb535-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">&quot;log&quot;</span>), </span>
<span id="cb535-3"><a href="generalized-linear-models.html#cb535-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data   =</span> elephant)  <span class="co"># log link is the default</span></span>
<span id="cb535-4"><a href="generalized-linear-models.html#cb535-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb535-5"><a href="generalized-linear-models.html#cb535-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = matings ~ age, family = poisson(link = &quot;log&quot;), 
##     data = elephant)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.58201    0.54462  -2.905  0.00368 ** 
## age          0.06869    0.01375   4.997 5.81e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 75.372  on 40  degrees of freedom
## Residual deviance: 51.012  on 39  degrees of freedom
## AIC: 156.46
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Thus the so-called pseudo-<span class="math inline">\(R^2\)</span> for the model with the log link is
<span class="math display">\[
\mathrm{pseudo}-R^2 = 1 - \frac{51.012}{75.372} = 32.3\%
\]</span>
We can visualize the fit by plotting a best-fitting line with a 95% confidence interval. Because the scale parameter is not estimated here, we will use a critical value from a standard normal distribution. Later, when we estimate the scale parameter based on data, we will use a critical value from a <span class="math inline">\(t\)</span>-distribution instead.</p>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb537-1"><a href="generalized-linear-models.html#cb537-1" aria-hidden="true" tabindex="-1"></a>new.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(elephant<span class="sc">$</span>age),</span>
<span id="cb537-2"><a href="generalized-linear-models.html#cb537-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">to   =</span> <span class="fu">max</span>(elephant<span class="sc">$</span>age),</span>
<span id="cb537-3"><a href="generalized-linear-models.html#cb537-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">length =</span> <span class="dv">100</span>))</span>
<span id="cb537-4"><a href="generalized-linear-models.html#cb537-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb537-5"><a href="generalized-linear-models.html#cb537-5" aria-hidden="true" tabindex="-1"></a>predict.fm1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm1, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb537-6"><a href="generalized-linear-models.html#cb537-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb537-7"><a href="generalized-linear-models.html#cb537-7" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age))</span>
<span id="cb537-8"><a href="generalized-linear-models.html#cb537-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>age, <span class="at">y =</span> predict.fm1<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb537-9"><a href="generalized-linear-models.html#cb537-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb537-10"><a href="generalized-linear-models.html#cb537-10" aria-hidden="true" tabindex="-1"></a><span class="co"># add lines for standard errors</span></span>
<span id="cb537-11"><a href="generalized-linear-models.html#cb537-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb537-12"><a href="generalized-linear-models.html#cb537-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb537-13"><a href="generalized-linear-models.html#cb537-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm1<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm1<span class="sc">$</span>se.fit, </span>
<span id="cb537-14"><a href="generalized-linear-models.html#cb537-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb537-15"><a href="generalized-linear-models.html#cb537-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb537-16"><a href="generalized-linear-models.html#cb537-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb537-17"><a href="generalized-linear-models.html#cb537-17" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb537-18"><a href="generalized-linear-models.html#cb537-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm1<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm1<span class="sc">$</span>se.fit, </span>
<span id="cb537-19"><a href="generalized-linear-models.html#cb537-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb537-20"><a href="generalized-linear-models.html#cb537-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>While the canonical link is a natural starting point, we are free to try other link functions as well. Below, we try the identity link and plot the fit.</p>
<div class="sourceCode" id="cb538"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb538-1"><a href="generalized-linear-models.html#cb538-1" aria-hidden="true" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(matings <span class="sc">~</span> age, <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">&quot;identity&quot;</span>), <span class="at">data =</span> elephant)  </span>
<span id="cb538-2"><a href="generalized-linear-models.html#cb538-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb538-3"><a href="generalized-linear-models.html#cb538-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = matings ~ age, family = poisson(link = &quot;identity&quot;), 
##     data = elephant)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -4.55205    1.33916  -3.399 0.000676 ***
## age          0.20179    0.04023   5.016 5.29e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 75.372  on 40  degrees of freedom
## Residual deviance: 50.058  on 39  degrees of freedom
## AIC: 155.5
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb540-1"><a href="generalized-linear-models.html#cb540-1" aria-hidden="true" tabindex="-1"></a>predict.fm2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm2, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb540-2"><a href="generalized-linear-models.html#cb540-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb540-3"><a href="generalized-linear-models.html#cb540-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age))</span>
<span id="cb540-4"><a href="generalized-linear-models.html#cb540-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>age, <span class="at">y =</span> predict.fm2<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb540-5"><a href="generalized-linear-models.html#cb540-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb540-6"><a href="generalized-linear-models.html#cb540-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb540-7"><a href="generalized-linear-models.html#cb540-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm2<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm2<span class="sc">$</span>se.fit, </span>
<span id="cb540-8"><a href="generalized-linear-models.html#cb540-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb540-9"><a href="generalized-linear-models.html#cb540-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb540-10"><a href="generalized-linear-models.html#cb540-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb540-11"><a href="generalized-linear-models.html#cb540-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb540-12"><a href="generalized-linear-models.html#cb540-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm2<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm2<span class="sc">$</span>se.fit, </span>
<span id="cb540-13"><a href="generalized-linear-models.html#cb540-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb540-14"><a href="generalized-linear-models.html#cb540-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Note that the choice of the link function has a substantial impact on the shape of the fit. The canonical (log) link suggests that the average number of matings increases with age at an accelerating rate, while the identity link suggests that the average number of matings increases steadily with age. The AIC favors the identity link here.</p>
<p>We can also have a look at the residuals to see if they suggest any model deficiencies. In general, we prefer the deviance residuals, so we will look at them.</p>
<div class="sourceCode" id="cb541"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb541-1"><a href="generalized-linear-models.html#cb541-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> elephant<span class="sc">$</span>age, </span>
<span id="cb541-2"><a href="generalized-linear-models.html#cb541-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> <span class="fu">residuals</span>(fm2, <span class="at">type =</span> <span class="st">&quot;deviance&quot;</span>),</span>
<span id="cb541-3"><a href="generalized-linear-models.html#cb541-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;age&quot;</span>,</span>
<span id="cb541-4"><a href="generalized-linear-models.html#cb541-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Deviance residuals&quot;</span>)</span>
<span id="cb541-5"><a href="generalized-linear-models.html#cb541-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb541-6"><a href="generalized-linear-models.html#cb541-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The residuals do not suggest any deficiency in the fit.</p>
<p>For this fit, the residual deviance suggests a small amount of overdispersion. To be on the safe side, we can fit a quasi-Poisson model in which the scale (overdispersion) parameter is estimated from the data. Note that when we estimate the overdispersion parameter, the estimates of the model parameters do not change, but their standard errors increase. Consequently, the uncertainty in the fit increases as well. In this case, however, the increase is so slight that it is barely noticeable.</p>
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb542-1"><a href="generalized-linear-models.html#cb542-1" aria-hidden="true" tabindex="-1"></a>fm3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(matings <span class="sc">~</span> age, <span class="at">family =</span> <span class="fu">quasipoisson</span>(<span class="at">link =</span> <span class="st">&quot;identity&quot;</span>), <span class="at">data =</span> elephant)  </span>
<span id="cb542-2"><a href="generalized-linear-models.html#cb542-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb542-3"><a href="generalized-linear-models.html#cb542-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm3)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = matings ~ age, family = quasipoisson(link = &quot;identity&quot;), 
##     data = elephant)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -4.55205    1.42164  -3.202  0.00272 ** 
## age          0.20179    0.04271   4.725 2.97e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 1.126975)
## 
##     Null deviance: 75.372  on 40  degrees of freedom
## Residual deviance: 50.058  on 39  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb544-1"><a href="generalized-linear-models.html#cb544-1" aria-hidden="true" tabindex="-1"></a>predict.fm3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm3, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb544-2"><a href="generalized-linear-models.html#cb544-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb544-3"><a href="generalized-linear-models.html#cb544-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age))</span>
<span id="cb544-4"><a href="generalized-linear-models.html#cb544-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>age, <span class="at">y =</span> predict.fm3<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb544-5"><a href="generalized-linear-models.html#cb544-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb544-6"><a href="generalized-linear-models.html#cb544-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb544-7"><a href="generalized-linear-models.html#cb544-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm3<span class="sc">$</span>fit <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df =</span> <span class="dv">39</span>) <span class="sc">*</span> predict.fm3<span class="sc">$</span>se.fit, </span>
<span id="cb544-8"><a href="generalized-linear-models.html#cb544-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb544-9"><a href="generalized-linear-models.html#cb544-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb544-10"><a href="generalized-linear-models.html#cb544-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb544-11"><a href="generalized-linear-models.html#cb544-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb544-12"><a href="generalized-linear-models.html#cb544-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm3<span class="sc">$</span>fit <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">39</span>) <span class="sc">*</span> predict.fm3<span class="sc">$</span>se.fit, </span>
<span id="cb544-13"><a href="generalized-linear-models.html#cb544-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb544-14"><a href="generalized-linear-models.html#cb544-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>As an alternative, we could fit a model that uses a negative binomial distribution for the response. Negative binomial distributions belong to the exponential family, so we can fit them using the GLM framework. However, the authors of <code>glm</code> did not include a negative binomial family in their initial code. Venables &amp; Ripley’s <code>MASS</code> package includes a program called <code>glm.nb</code> which is specifically designed for negative binomial responses. <code>MASS::glm.nb</code> uses the parameterization familiar to ecologists, although they use the parameter <span class="math inline">\(\theta\)</span> instead of <span class="math inline">\(k\)</span>. So, in their notation, if <span class="math inline">\(y \sim \mathrm{NB}(\mu, \theta)\)</span>, then <span class="math inline">\(\mathrm{Var}(y) = \mu + \mu^2/\theta\)</span>.</p>
<div class="sourceCode" id="cb545"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb545-1"><a href="generalized-linear-models.html#cb545-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(MASS)</span></code></pre></div>
<pre><code>## Loading required package: MASS</code></pre>
<div class="sourceCode" id="cb547"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb547-1"><a href="generalized-linear-models.html#cb547-1" aria-hidden="true" tabindex="-1"></a>fm4 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(matings <span class="sc">~</span> age, <span class="at">link =</span> identity, <span class="at">data =</span> elephant)  </span>
<span id="cb547-2"><a href="generalized-linear-models.html#cb547-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb547-3"><a href="generalized-linear-models.html#cb547-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm4)</span></code></pre></div>
<pre><code>## 
## Call:
## glm.nb(formula = matings ~ age, data = elephant, link = identity, 
##     init.theta = 15.80269167)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -4.56939    1.45770  -3.135  0.00172 ** 
## age          0.20232    0.04428   4.569  4.9e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(15.8027) family taken to be 1)
## 
##     Null deviance: 64.836  on 40  degrees of freedom
## Residual deviance: 43.214  on 39  degrees of freedom
## AIC: 156.87
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  15.8 
##           Std. Err.:  23.0 
## 
##  2 x log-likelihood:  -150.872</code></pre>
<div class="sourceCode" id="cb549"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb549-1"><a href="generalized-linear-models.html#cb549-1" aria-hidden="true" tabindex="-1"></a>predict.fm4 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm4, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb549-2"><a href="generalized-linear-models.html#cb549-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb549-3"><a href="generalized-linear-models.html#cb549-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age))</span>
<span id="cb549-4"><a href="generalized-linear-models.html#cb549-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>age, <span class="at">y =</span> predict.fm4<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb549-5"><a href="generalized-linear-models.html#cb549-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb549-6"><a href="generalized-linear-models.html#cb549-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb549-7"><a href="generalized-linear-models.html#cb549-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm4<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm4<span class="sc">$</span>se.fit, </span>
<span id="cb549-8"><a href="generalized-linear-models.html#cb549-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb549-9"><a href="generalized-linear-models.html#cb549-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb549-10"><a href="generalized-linear-models.html#cb549-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb549-11"><a href="generalized-linear-models.html#cb549-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb549-12"><a href="generalized-linear-models.html#cb549-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm4<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm4<span class="sc">$</span>se.fit, </span>
<span id="cb549-13"><a href="generalized-linear-models.html#cb549-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb549-14"><a href="generalized-linear-models.html#cb549-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Notice that <span class="math inline">\(\hat{\theta} = 15.8\)</span>, again indicating that the extra-Poisson variation is mild. Notice also that the error bounds on the fitted curve are ever so slightly larger than the error bounds from the Poisson fit, and nearly identical to the error bounds from the quasi-Poisson fit.</p>
</div>
<div id="bayesian-interlude" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Bayesian interlude<a href="generalized-linear-models.html#bayesian-interlude" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="rstanarm-1" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> rstanarm<a href="generalized-linear-models.html#rstanarm-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will take a look at how Poisson regression can be handled from a Bayesian perspective. This interlude will also allow us to introduce a few more Bayesian concepts.</p>
<p>We’ll first fit the Poisson regression with identity link using <code>rstanarm::stan_glm</code>.</p>
<div class="sourceCode" id="cb550"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb550-1"><a href="generalized-linear-models.html#cb550-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(rstanarm)</span></code></pre></div>
<pre><code>## Loading required package: rstanarm</code></pre>
<pre><code>## Loading required package: Rcpp</code></pre>
<pre><code>## This is rstanarm version 2.21.4</code></pre>
<pre><code>## - See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!</code></pre>
<pre><code>## - Default priors may change, so it&#39;s safest to specify priors, even if equivalent to the defaults.</code></pre>
<pre><code>## - For execution on a local, multicore CPU with excess RAM we recommend calling</code></pre>
<pre><code>##   options(mc.cores = parallel::detectCores())</code></pre>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="generalized-linear-models.html#cb558-1" aria-hidden="true" tabindex="-1"></a>fm5 <span class="ot">&lt;-</span> <span class="fu">stan_glm</span>(matings <span class="sc">~</span> age, </span>
<span id="cb558-2"><a href="generalized-linear-models.html#cb558-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">&quot;identity&quot;</span>), </span>
<span id="cb558-3"><a href="generalized-linear-models.html#cb558-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">data   =</span> elephant,</span>
<span id="cb558-4"><a href="generalized-linear-models.html#cb558-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">seed   =</span> <span class="dv">1</span>)  </span></code></pre></div>
<div class="sourceCode" id="cb559"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb559-1"><a href="generalized-linear-models.html#cb559-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fm5, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## stan_glm
##  family:       poisson [identity]
##  formula:      matings ~ age
##  observations: 41
##  predictors:   2
## ------
##             Median MAD_SD
## (Intercept) -4.420  1.358
## age          0.198  0.041
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p>We can visualize the marginal posterior of the slope using <code>bayesplot::mcmc_areas</code>:</p>
<div class="sourceCode" id="cb561"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb561-1"><a href="generalized-linear-models.html#cb561-1" aria-hidden="true" tabindex="-1"></a>posterior.fm5 <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(fm5)</span>
<span id="cb561-2"><a href="generalized-linear-models.html#cb561-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb561-3"><a href="generalized-linear-models.html#cb561-3" aria-hidden="true" tabindex="-1"></a>bayesplot<span class="sc">::</span><span class="fu">mcmc_areas</span>(posterior.fm5,</span>
<span id="cb561-4"><a href="generalized-linear-models.html#cb561-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">pars =</span> <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>),</span>
<span id="cb561-5"><a href="generalized-linear-models.html#cb561-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">prob =</span> <span class="fl">0.95</span>) </span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Notice that the slope of the fitted regression line is slightly attenuated relative to the ML fit from the frequentist analysis. The reason is that the default priors selected by <code>rstanarm</code> are actually reasonably strong:</p>
<div class="sourceCode" id="cb562"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb562-1"><a href="generalized-linear-models.html#cb562-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prior_summary</span>(fm5)</span></code></pre></div>
<pre><code>## Priors for model &#39;fm5&#39; 
## ------
## Intercept (after predictors centered)
##  ~ normal(location = 0, scale = 2.5)
## 
## Coefficients
##   Specified prior:
##     ~ normal(location = 0, scale = 2.5)
##   Adjusted prior:
##     ~ normal(location = 0, scale = 0.38)
## ------
## See help(&#39;prior_summary.stanreg&#39;) for more details</code></pre>
<p><code>rstanarm</code> parameterizes the normal distribution by its mean and standard deviation. Thus, the prior for the slope has a mean of 0 and standard deviation of 2.5. (I think: I don’t yet understand the difference between the ‘specified prior’ and the ‘adjusted prior’.) This relatively strong prior reflects the views of the developers of <code>rstanarm</code>, who think there is benefit to shrinking most estimated effects slightly towards 0. If we want to override this default and use weaker priors, we can do so as follows.</p>
<div class="sourceCode" id="cb564"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb564-1"><a href="generalized-linear-models.html#cb564-1" aria-hidden="true" tabindex="-1"></a>fm5 <span class="ot">&lt;-</span> <span class="fu">stan_glm</span>(matings <span class="sc">~</span> age, </span>
<span id="cb564-2"><a href="generalized-linear-models.html#cb564-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">&quot;identity&quot;</span>), </span>
<span id="cb564-3"><a href="generalized-linear-models.html#cb564-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">data   =</span> elephant,</span>
<span id="cb564-4"><a href="generalized-linear-models.html#cb564-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">prior  =</span> <span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">100</span>), </span>
<span id="cb564-5"><a href="generalized-linear-models.html#cb564-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">prior_intercept =</span> <span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">100</span>),</span>
<span id="cb564-6"><a href="generalized-linear-models.html#cb564-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">seed   =</span> <span class="dv">1</span>)  </span></code></pre></div>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="generalized-linear-models.html#cb565-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fm5, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## stan_glm
##  family:       poisson [identity]
##  formula:      matings ~ age
##  observations: 41
##  predictors:   2
## ------
##             Median MAD_SD
## (Intercept) -4.444  1.320
## age          0.200  0.039
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p>Weakening the prior results in a posterior mean for the slope that is closer to the MLE from the frequentist analysis.</p>
<p>We can visualize the fit in the usual way, by plotting sample draws from the MCMC sampler.</p>
<div class="sourceCode" id="cb567"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb567-1"><a href="generalized-linear-models.html#cb567-1" aria-hidden="true" tabindex="-1"></a>mcmc.sims <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(fm5)</span>
<span id="cb567-2"><a href="generalized-linear-models.html#cb567-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb567-3"><a href="generalized-linear-models.html#cb567-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>))</span>
<span id="cb567-4"><a href="generalized-linear-models.html#cb567-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb567-5"><a href="generalized-linear-models.html#cb567-5" aria-hidden="true" tabindex="-1"></a>sample.sims <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(mcmc.sims), <span class="at">size =</span> <span class="dv">100</span>)</span>
<span id="cb567-6"><a href="generalized-linear-models.html#cb567-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> sample.sims) {</span>
<span id="cb567-7"><a href="generalized-linear-models.html#cb567-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">abline</span>(<span class="at">a =</span> mcmc.sims[i, <span class="dv">1</span>], <span class="at">b =</span> mcmc.sims[i, <span class="dv">2</span>], <span class="at">col =</span> <span class="st">&quot;skyblue&quot;</span>)</span>
<span id="cb567-8"><a href="generalized-linear-models.html#cb567-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb567-9"><a href="generalized-linear-models.html#cb567-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb567-10"><a href="generalized-linear-models.html#cb567-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> <span class="fu">coef</span>(fm5)[<span class="st">&#39;(Intercept)&#39;</span>], <span class="at">b =</span> <span class="fu">coef</span>(fm5)[<span class="st">&#39;age&#39;</span>], <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb567-11"><a href="generalized-linear-models.html#cb567-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb567-12"><a href="generalized-linear-models.html#cb567-12" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">points</span>(matings <span class="sc">~</span> age, <span class="at">pch =</span> <span class="dv">16</span>))</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="posterior-predictive-checks" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Posterior predictive checks<a href="generalized-linear-models.html#posterior-predictive-checks" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>How might we assess the quality of this fit? A Bayesian approach to assessing the quality of fit is to generate posterior predictive distributions. A “posterior predictive” data set is a new data set of hypothetical observations simulated using the parameter values from one of the samples of the MCMC sampler. By creating many such data sets, we can build up a distribution of data sets predicted by the posterior distribution of the model parameters. By comparing the actual observed data to this distribution, we can gain a sense of whether our data are consistent with the posterior fit.</p>
<p>The authors of <code>rstanarm</code> advocate using posterior predictive checks extensively to assess model adequacy. For that reason, they have included a number of tools that make posterior predictive checking simple. For example, the command <code>rstanarm::posterior_predict</code> generates a collection of hypothetical data sets by randomly sampling from the posterior distribution of the parameters. The default behavior is to generate a collection of 1000 such data sets.</p>
<div class="sourceCode" id="cb568"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb568-1"><a href="generalized-linear-models.html#cb568-1" aria-hidden="true" tabindex="-1"></a>post.predict <span class="ot">&lt;-</span> <span class="fu">posterior_predict</span>(fm5)</span></code></pre></div>
<p>For example, we can have a look at a few of these hypothetical data sets.</p>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="generalized-linear-models.html#cb569-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb569-2"><a href="generalized-linear-models.html#cb569-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb569-3"><a href="generalized-linear-models.html#cb569-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>) {</span>
<span id="cb569-4"><a href="generalized-linear-models.html#cb569-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb569-5"><a href="generalized-linear-models.html#cb569-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>))</span>
<span id="cb569-6"><a href="generalized-linear-models.html#cb569-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(elephant<span class="sc">$</span>age, post.predict[i, ], <span class="at">pch =</span> <span class="dv">1</span>)</span>
<span id="cb569-7"><a href="generalized-linear-models.html#cb569-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Our task is to determine if the real data set that we actually observed is consistent with this collection of hypothetical data sets. To do so, we can calculate a summary statistic that captures an interesting feature of each data set, and compare the value of that summary statistic for the real data set to the distribution of values across the simulated data sets.</p>
<p>What summary statistic would you use to compare the real elephant data set to these simulated ones? We’ll use the marginal standard deviation of the number of matings below, but there might be other or better examples that you could think of. Typically, one uses several posterior predictive statistics, not just one. First, we calculate the distribution of marginal standard deviations across the collection of simulated data sets. This R code illustrates the use of the handy R command <code>apply</code>, which applies a function to one of the margins (rows or columns) of an array. Here, because the individual data sets are stored as the rows of <code>post.predict</code>, we will calculate the standard deviation of the contents of each row.</p>
<div class="sourceCode" id="cb570"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb570-1"><a href="generalized-linear-models.html#cb570-1" aria-hidden="true" tabindex="-1"></a>post.predict.sd <span class="ot">&lt;-</span> <span class="fu">apply</span>(post.predict, <span class="dv">1</span>, sd)</span></code></pre></div>
<p>Now we plot a histogram of these standard deviations and compare the distribution to the marginal standard deviation of the real data.</p>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="generalized-linear-models.html#cb571-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(post.predict.sd, <span class="at">breaks =</span> <span class="dv">20</span>, <span class="at">xlab =</span> <span class="st">&quot;Marginal SD of response&quot;</span>)</span>
<span id="cb571-2"><a href="generalized-linear-models.html#cb571-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">sd</span>(elephant<span class="sc">$</span>matings), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>The actual standard deviation, shown by the red line, is consistent with the standard deviations of the simulated data sets, indicating that the model provides a reasonable description of the data, at least with regard to the marginal SD of the response variable. This is consistent with our previous conclusions that the extra-Poisson variation in these data is quite mild.</p>
<p>The authors of <code>rstanarm</code> have provided the function <code>pp_check</code> (for [p]osterior [p]redictive check) to do all of this in one fell swoop.</p>
<div class="sourceCode" id="cb572"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb572-1"><a href="generalized-linear-models.html#cb572-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(fm5, <span class="at">plotfun =</span> <span class="st">&quot;stat&quot;</span>, <span class="at">stat =</span> <span class="st">&quot;sd&quot;</span>, <span class="at">binwidth =</span> .<span class="dv">1</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
<div id="jags" class="section level3 hasAnchor" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> JAGS<a href="generalized-linear-models.html#jags" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can also code the model up directly in JAGS. Notice that the code here is barely more complicated than OLS regression. The code below shows the JAGS implementation of the elephant GLM with a Poisson distribution for the response and a log link.</p>
<div class="sourceCode" id="cb573"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb573-1"><a href="generalized-linear-models.html#cb573-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(R2jags)</span></code></pre></div>
<pre><code>## Loading required package: R2jags</code></pre>
<pre><code>## Loading required package: rjags</code></pre>
<pre><code>## Loading required package: coda</code></pre>
<pre><code>## Linked to JAGS 4.3.1</code></pre>
<pre><code>## Loaded modules: basemod,bugs</code></pre>
<pre><code>## 
## Attaching package: &#39;R2jags&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:coda&#39;:
## 
##     traceplot</code></pre>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="generalized-linear-models.html#cb581-1" aria-hidden="true" tabindex="-1"></a>elephant.model <span class="ot">&lt;-</span> <span class="cf">function</span>() {</span>
<span id="cb581-2"><a href="generalized-linear-models.html#cb581-2" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb581-3"><a href="generalized-linear-models.html#cb581-3" aria-hidden="true" tabindex="-1"></a>   <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>J) {             <span class="co"># J = number of data points</span></span>
<span id="cb581-4"><a href="generalized-linear-models.html#cb581-4" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb581-5"><a href="generalized-linear-models.html#cb581-5" aria-hidden="true" tabindex="-1"></a>      y[j] <span class="sc">~</span> <span class="fu">dpois</span>(mu[j])      <span class="co"># data model:  the likelihood </span></span>
<span id="cb581-6"><a href="generalized-linear-models.html#cb581-6" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb581-7"><a href="generalized-linear-models.html#cb581-7" aria-hidden="true" tabindex="-1"></a>      mu[j] <span class="ot">&lt;-</span> <span class="fu">exp</span>(eta[j])      <span class="co"># inverse link</span></span>
<span id="cb581-8"><a href="generalized-linear-models.html#cb581-8" aria-hidden="true" tabindex="-1"></a>      eta[j] <span class="ot">&lt;-</span> a <span class="sc">+</span> b <span class="sc">*</span> x[j]  <span class="co"># linear predictor</span></span>
<span id="cb581-9"><a href="generalized-linear-models.html#cb581-9" aria-hidden="true" tabindex="-1"></a>   }</span>
<span id="cb581-10"><a href="generalized-linear-models.html#cb581-10" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb581-11"><a href="generalized-linear-models.html#cb581-11" aria-hidden="true" tabindex="-1"></a>   a <span class="sc">~</span> <span class="fu">dnorm</span> (<span class="fl">0.0</span>, <span class="fl">1E-6</span>)       <span class="co"># prior for intercept</span></span>
<span id="cb581-12"><a href="generalized-linear-models.html#cb581-12" aria-hidden="true" tabindex="-1"></a>   b <span class="sc">~</span> <span class="fu">dnorm</span> (<span class="fl">0.0</span>, <span class="fl">1E-6</span>)       <span class="co"># prior for slope</span></span>
<span id="cb581-13"><a href="generalized-linear-models.html#cb581-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb581-14"><a href="generalized-linear-models.html#cb581-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb581-15"><a href="generalized-linear-models.html#cb581-15" aria-hidden="true" tabindex="-1"></a>jags.data <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">y =</span> elephant<span class="sc">$</span>matings, </span>
<span id="cb581-16"><a href="generalized-linear-models.html#cb581-16" aria-hidden="true" tabindex="-1"></a>                  <span class="at">x =</span> elephant<span class="sc">$</span>age,</span>
<span id="cb581-17"><a href="generalized-linear-models.html#cb581-17" aria-hidden="true" tabindex="-1"></a>                  <span class="at">J =</span> <span class="fu">nrow</span>(elephant))</span>
<span id="cb581-18"><a href="generalized-linear-models.html#cb581-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb581-19"><a href="generalized-linear-models.html#cb581-19" aria-hidden="true" tabindex="-1"></a>jags.params <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>)</span>
<span id="cb581-20"><a href="generalized-linear-models.html#cb581-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb581-21"><a href="generalized-linear-models.html#cb581-21" aria-hidden="true" tabindex="-1"></a>jags.inits <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb581-22"><a href="generalized-linear-models.html#cb581-22" aria-hidden="true" tabindex="-1"></a>   <span class="fu">list</span>(<span class="st">&quot;a&quot;</span> <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>), <span class="st">&quot;b&quot;</span> <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>))</span>
<span id="cb581-23"><a href="generalized-linear-models.html#cb581-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb581-24"><a href="generalized-linear-models.html#cb581-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb581-25"><a href="generalized-linear-models.html#cb581-25" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb581-26"><a href="generalized-linear-models.html#cb581-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb581-27"><a href="generalized-linear-models.html#cb581-27" aria-hidden="true" tabindex="-1"></a>jagsfit <span class="ot">&lt;-</span> <span class="fu">jags</span>(<span class="at">data               =</span> jags.data, </span>
<span id="cb581-28"><a href="generalized-linear-models.html#cb581-28" aria-hidden="true" tabindex="-1"></a>                <span class="at">inits              =</span> jags.inits, </span>
<span id="cb581-29"><a href="generalized-linear-models.html#cb581-29" aria-hidden="true" tabindex="-1"></a>                <span class="at">parameters.to.save =</span> jags.params,</span>
<span id="cb581-30"><a href="generalized-linear-models.html#cb581-30" aria-hidden="true" tabindex="-1"></a>                <span class="at">model.file         =</span> elephant.model,</span>
<span id="cb581-31"><a href="generalized-linear-models.html#cb581-31" aria-hidden="true" tabindex="-1"></a>                <span class="at">n.chains           =</span> <span class="dv">3</span>,</span>
<span id="cb581-32"><a href="generalized-linear-models.html#cb581-32" aria-hidden="true" tabindex="-1"></a>                <span class="at">n.iter             =</span> <span class="fl">5E4</span>,</span>
<span id="cb581-33"><a href="generalized-linear-models.html#cb581-33" aria-hidden="true" tabindex="-1"></a>                <span class="at">n.thin             =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## module glm loaded</code></pre>
<p>Let’s have a look at the posterior summaries:</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="generalized-linear-models.html#cb583-1" aria-hidden="true" tabindex="-1"></a>mcmc.output <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(jagsfit<span class="sc">$</span>BUGSoutput<span class="sc">$</span>sims.list)</span>
<span id="cb583-2"><a href="generalized-linear-models.html#cb583-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(mcmc.output, <span class="dv">2</span>, mean)</span></code></pre></div>
<pre><code>##            a            b     deviance 
##  -1.59257609   0.06871434 154.47531083</code></pre>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="generalized-linear-models.html#cb585-1" aria-hidden="true" tabindex="-1"></a><span class="fu">HPDinterval</span>(<span class="fu">as.mcmc</span>(mcmc.output), <span class="at">prob =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                 lower        upper
## a         -2.64905619  -0.54223141
## b          0.04194793   0.09511553
## deviance 152.45783408 158.39245393
## attr(,&quot;Probability&quot;)
## [1] 0.95</code></pre>
<p>Compare these to the values generated by the <code>glm</code> fit with the log link. We can also visualize the uncertainty in the fit by plotting the fit implied by a random sample of parameters from the posterior:</p>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="generalized-linear-models.html#cb587-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(matings <span class="sc">~</span> age, <span class="at">data =</span> elephant, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb587-2"><a href="generalized-linear-models.html#cb587-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb587-3"><a href="generalized-linear-models.html#cb587-3" aria-hidden="true" tabindex="-1"></a>subset.samples <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(mcmc.output), <span class="at">size =</span> <span class="dv">100</span>)</span>
<span id="cb587-4"><a href="generalized-linear-models.html#cb587-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb587-5"><a href="generalized-linear-models.html#cb587-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> subset.samples) {</span>
<span id="cb587-6"><a href="generalized-linear-models.html#cb587-6" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb587-7"><a href="generalized-linear-models.html#cb587-7" aria-hidden="true" tabindex="-1"></a>   a <span class="ot">&lt;-</span> mcmc.output<span class="sc">$</span>a[i]</span>
<span id="cb587-8"><a href="generalized-linear-models.html#cb587-8" aria-hidden="true" tabindex="-1"></a>   b <span class="ot">&lt;-</span> mcmc.output<span class="sc">$</span>b[i]</span>
<span id="cb587-9"><a href="generalized-linear-models.html#cb587-9" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb587-10"><a href="generalized-linear-models.html#cb587-10" aria-hidden="true" tabindex="-1"></a>   my.fit <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(a <span class="sc">+</span> b <span class="sc">*</span> x)</span>
<span id="cb587-11"><a href="generalized-linear-models.html#cb587-11" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb587-12"><a href="generalized-linear-models.html#cb587-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">curve</span>(my.fit, </span>
<span id="cb587-13"><a href="generalized-linear-models.html#cb587-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">from =</span> <span class="fu">min</span>(elephant<span class="sc">$</span>age), </span>
<span id="cb587-14"><a href="generalized-linear-models.html#cb587-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">to   =</span> <span class="fu">max</span>(elephant<span class="sc">$</span>age),</span>
<span id="cb587-15"><a href="generalized-linear-models.html#cb587-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">col  =</span> <span class="st">&quot;deepskyblue&quot;</span>, </span>
<span id="cb587-16"><a href="generalized-linear-models.html#cb587-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">lwd  =</span> <span class="dv">1</span>, </span>
<span id="cb587-17"><a href="generalized-linear-models.html#cb587-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">add  =</span> <span class="cn">TRUE</span>)</span>
<span id="cb587-18"><a href="generalized-linear-models.html#cb587-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb587-19"><a href="generalized-linear-models.html#cb587-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb587-20"><a href="generalized-linear-models.html#cb587-20" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">points</span>(matings <span class="sc">~</span> age, <span class="at">pch =</span> <span class="dv">16</span>))</span>
<span id="cb587-21"><a href="generalized-linear-models.html#cb587-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb587-22"><a href="generalized-linear-models.html#cb587-22" aria-hidden="true" tabindex="-1"></a>post.means <span class="ot">&lt;-</span> <span class="fu">apply</span>(mcmc.output, <span class="dv">2</span>, mean)</span>
<span id="cb587-23"><a href="generalized-linear-models.html#cb587-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb587-24"><a href="generalized-linear-models.html#cb587-24" aria-hidden="true" tabindex="-1"></a>my.fit <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(post.means[<span class="st">&#39;a&#39;</span>] <span class="sc">+</span> post.means[<span class="st">&#39;b&#39;</span>] <span class="sc">*</span> x)</span>
<span id="cb587-25"><a href="generalized-linear-models.html#cb587-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb587-26"><a href="generalized-linear-models.html#cb587-26" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(my.fit, </span>
<span id="cb587-27"><a href="generalized-linear-models.html#cb587-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">from =</span> <span class="fu">min</span>(elephant<span class="sc">$</span>age), </span>
<span id="cb587-28"><a href="generalized-linear-models.html#cb587-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">to   =</span> <span class="fu">max</span>(elephant<span class="sc">$</span>age),</span>
<span id="cb587-29"><a href="generalized-linear-models.html#cb587-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">col  =</span> <span class="st">&quot;blue&quot;</span>, </span>
<span id="cb587-30"><a href="generalized-linear-models.html#cb587-30" aria-hidden="true" tabindex="-1"></a>      <span class="at">lwd  =</span> <span class="dv">2</span>, </span>
<span id="cb587-31"><a href="generalized-linear-models.html#cb587-31" aria-hidden="true" tabindex="-1"></a>      <span class="at">add  =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Suppose we wanted to fit this model using JAGS with the identity link, so that the relationship between mean matings and age was linear. To do so, we would have to be careful, because we would have to make sure that the MCMC sampler did not stray into regions that generated negative values for the observation-level mean, <span class="math inline">\(\mu\)</span>. Mathematically, we simply want to construct a likelihood that evaluates to 0 whenever <span class="math inline">\(\mu \leq 0\)</span>. However, as of this writing, I haven’t figured out what the best approach is for implementing such a model in JAGS.</p>
</div>
<div id="observation-level-random-effects" class="section level3 hasAnchor" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> Observation-level random effects<a href="generalized-linear-models.html#observation-level-random-effects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use this opportunity to introduce an alternative approach to accommodating overdispersion in models with non-Gaussian responses. This alternative approach entails adding a latent Gaussian-distributed random effect to the linear predictor. Because this random effect takes a unique value for each observation, it is known as a “observation-level random effect”. Observation-level random effects are motivated by the idea that overdispersion is caused by additional inputs or factors that vary among observations and re not included in the model. For example, knowing next to nothing about elephants, we might speculate that there are additional factors that influence a male elephant’s mating success above and beyond age, such as (say) nutrition. The observation-level random effects are meant to capture this additional variation. Importantly, if we use an observation-level random effect, then we have no control on the sign of the linear predictor <span class="math inline">\(\eta\)</span>. Consequently, we must use a link function that maps any value of the linear predictor (<span class="math inline">\(\eta\)</span>) to a valid value of the observation-level mean (<span class="math inline">\(\mu\)</span>). (In other words, we can’t use the identity link for a Poisson response.) For the elephant data, adding an observation-level random effect changes the model to:
<span class="math display">\[\begin{align*}
y_i &amp; \sim \mathrm{Pois}(\mu_i)\\
\mu_i  &amp; = \exp({\eta_i}) \\
\eta_i &amp; \sim \mathcal{N}(a + b x_i, \sigma^2_\eta).
\end{align*}\]</span></p>
<p>Priors on <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, and <span class="math inline">\(\sigma^2_\eta\)</span> would complete the Bayesian specification. Implemeting the model in JAGS is straightforward:</p>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb588-1"><a href="generalized-linear-models.html#cb588-1" aria-hidden="true" tabindex="-1"></a>elephant.model<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="cf">function</span>() {</span>
<span id="cb588-2"><a href="generalized-linear-models.html#cb588-2" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb588-3"><a href="generalized-linear-models.html#cb588-3" aria-hidden="true" tabindex="-1"></a>   <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>J) {             <span class="co"># J = number of data points</span></span>
<span id="cb588-4"><a href="generalized-linear-models.html#cb588-4" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb588-5"><a href="generalized-linear-models.html#cb588-5" aria-hidden="true" tabindex="-1"></a>      y[j] <span class="sc">~</span> <span class="fu">dpois</span>(mu[j])      <span class="co"># data model:  the likelihood </span></span>
<span id="cb588-6"><a href="generalized-linear-models.html#cb588-6" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb588-7"><a href="generalized-linear-models.html#cb588-7" aria-hidden="true" tabindex="-1"></a>      mu[j] <span class="ot">&lt;-</span> <span class="fu">exp</span>(eta[j])      <span class="co"># inverse link</span></span>
<span id="cb588-8"><a href="generalized-linear-models.html#cb588-8" aria-hidden="true" tabindex="-1"></a>      eta[j] <span class="sc">~</span> <span class="fu">dnorm</span>(a <span class="sc">+</span> b <span class="sc">*</span> x[j], tau_eps)  <span class="co"># linear predictor, includes observation-level random effect</span></span>
<span id="cb588-9"><a href="generalized-linear-models.html#cb588-9" aria-hidden="true" tabindex="-1"></a>   }</span>
<span id="cb588-10"><a href="generalized-linear-models.html#cb588-10" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb588-11"><a href="generalized-linear-models.html#cb588-11" aria-hidden="true" tabindex="-1"></a>   a <span class="sc">~</span> <span class="fu">dnorm</span> (<span class="fl">0.0</span>, <span class="fl">1E-6</span>)       <span class="co"># prior for intercept</span></span>
<span id="cb588-12"><a href="generalized-linear-models.html#cb588-12" aria-hidden="true" tabindex="-1"></a>   b <span class="sc">~</span> <span class="fu">dnorm</span> (<span class="fl">0.0</span>, <span class="fl">1E-6</span>)       <span class="co"># prior for slope</span></span>
<span id="cb588-13"><a href="generalized-linear-models.html#cb588-13" aria-hidden="true" tabindex="-1"></a>   tau_eps <span class="sc">~</span> <span class="fu">dgamma</span> (<span class="fl">0.01</span>, <span class="fl">0.01</span>)</span>
<span id="cb588-14"><a href="generalized-linear-models.html#cb588-14" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb588-15"><a href="generalized-linear-models.html#cb588-15" aria-hidden="true" tabindex="-1"></a>   sd_eps <span class="ot">&lt;-</span> <span class="fu">pow</span>(tau_eps, <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb588-16"><a href="generalized-linear-models.html#cb588-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb588-17"><a href="generalized-linear-models.html#cb588-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb588-18"><a href="generalized-linear-models.html#cb588-18" aria-hidden="true" tabindex="-1"></a>jags.data <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">y =</span> elephant<span class="sc">$</span>matings, </span>
<span id="cb588-19"><a href="generalized-linear-models.html#cb588-19" aria-hidden="true" tabindex="-1"></a>                  <span class="at">x =</span> elephant<span class="sc">$</span>age,</span>
<span id="cb588-20"><a href="generalized-linear-models.html#cb588-20" aria-hidden="true" tabindex="-1"></a>                  <span class="at">J =</span> <span class="fu">nrow</span>(elephant))</span>
<span id="cb588-21"><a href="generalized-linear-models.html#cb588-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb588-22"><a href="generalized-linear-models.html#cb588-22" aria-hidden="true" tabindex="-1"></a>jags.params <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>, <span class="st">&quot;sd_eps&quot;</span>)</span>
<span id="cb588-23"><a href="generalized-linear-models.html#cb588-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb588-24"><a href="generalized-linear-models.html#cb588-24" aria-hidden="true" tabindex="-1"></a>jags.inits <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb588-25"><a href="generalized-linear-models.html#cb588-25" aria-hidden="true" tabindex="-1"></a>   <span class="fu">list</span>(<span class="st">&quot;a&quot;</span> <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>), <span class="st">&quot;b&quot;</span> <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>), <span class="st">&quot;tau_eps&quot;</span> <span class="ot">=</span> <span class="fu">runif</span>(<span class="dv">1</span>))</span>
<span id="cb588-26"><a href="generalized-linear-models.html#cb588-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb588-27"><a href="generalized-linear-models.html#cb588-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb588-28"><a href="generalized-linear-models.html#cb588-28" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb588-29"><a href="generalized-linear-models.html#cb588-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb588-30"><a href="generalized-linear-models.html#cb588-30" aria-hidden="true" tabindex="-1"></a>jagsfit2 <span class="ot">&lt;-</span> <span class="fu">jags</span>(<span class="at">data               =</span> jags.data, </span>
<span id="cb588-31"><a href="generalized-linear-models.html#cb588-31" aria-hidden="true" tabindex="-1"></a>                 <span class="at">inits              =</span> jags.inits, </span>
<span id="cb588-32"><a href="generalized-linear-models.html#cb588-32" aria-hidden="true" tabindex="-1"></a>                 <span class="at">parameters.to.save =</span> jags.params,</span>
<span id="cb588-33"><a href="generalized-linear-models.html#cb588-33" aria-hidden="true" tabindex="-1"></a>                 <span class="at">model.file         =</span> elephant.model<span class="fl">.2</span>,</span>
<span id="cb588-34"><a href="generalized-linear-models.html#cb588-34" aria-hidden="true" tabindex="-1"></a>                 <span class="at">n.chains           =</span> <span class="dv">3</span>,</span>
<span id="cb588-35"><a href="generalized-linear-models.html#cb588-35" aria-hidden="true" tabindex="-1"></a>                 <span class="at">n.iter             =</span> <span class="fl">5E4</span>,</span>
<span id="cb588-36"><a href="generalized-linear-models.html#cb588-36" aria-hidden="true" tabindex="-1"></a>                 <span class="at">n.thin             =</span> <span class="dv">5</span>)</span></code></pre></div>
<p>Again, we can have a look at the posterior summaries.</p>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="generalized-linear-models.html#cb589-1" aria-hidden="true" tabindex="-1"></a>mcmc.output <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(jagsfit2<span class="sc">$</span>BUGSoutput<span class="sc">$</span>sims.list)</span>
<span id="cb589-2"><a href="generalized-linear-models.html#cb589-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(mcmc.output, <span class="dv">2</span>, mean)</span></code></pre></div>
<pre><code>##            a            b     deviance       sd_eps 
##  -1.65360318   0.06934144 147.14813848   0.27075058</code></pre>
<div class="sourceCode" id="cb591"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb591-1"><a href="generalized-linear-models.html#cb591-1" aria-hidden="true" tabindex="-1"></a><span class="fu">HPDinterval</span>(<span class="fu">as.mcmc</span>(mcmc.output), <span class="at">prob =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                 lower       upper
## a         -2.85901410  -0.4407061
## b          0.03818321   0.1005042
## deviance 133.86486164 158.2878871
## sd_eps     0.06376511   0.5261329
## attr(,&quot;Probability&quot;)
## [1] 0.95</code></pre>
<p>Plotting the posterior fit in this case is more subtle. With the observation-level random effect, we now have a model that includes a random effect behind a non-linear link function. In other words, we have a generalizd linear mixed model (GLMM). The combination of a random effect and a non-linear link function means that there are two different ways to calculate the fitted value — the so-called “marginal means” and the “conditional means”. We will defer a discussion of this distinction until we discuss GLMMs in greater detail. Accordingly, we defer the plot as well.</p>
<!-- ```{r}
plot(matings ~ age, data = elephant, type = "n")

subset.samples <- sample(nrow(mcmc.output), size = 100)

for(i in subset.samples) {
   
   a <- mcmc.output$a[i]
   b <- mcmc.output$b[i]
   
   my.fit <- function(x) exp(a + b * x)
   
   curve(my.fit, 
         from = min(elephant$age), 
         to   = max(elephant$age),
         col  = "deepskyblue", 
         lwd  = 1, 
         add  = TRUE)
}

with(elephant, points(matings ~ age, pch = 16))

post.means <- apply(mcmc.output, 2, mean)

my.fit <- function(x) exp(post.means['a'] + post.means['b'] * x)

curve(my.fit, 
      from = min(elephant$age), 
      to   = max(elephant$age),
      col  = "blue", 
      lwd  = 2, 
      add  = TRUE)
```

Because the extra-Poisson variation in the elephant data is small, the effect of the observation-level random effect is slight.  However, an eagle-eyed observer might notice the following differences.  First, the posterior uncertainty in the slope parameter that captures the effect of age has increased slightly.  Second, and perhaps more meaningfully, the fitted curve has dropped slightly.    This makes sense, as the model with the observation-level random effect doesn't have to strain quite as hard to accommodate the few elephants with large and positive residuals.  Thus, adding an observation-level random effect has had the same effect on the fit as other approaches to accommodating extra-Poisson variaton.  
-->
<p>Formally, we can assess the need for the observation-level random effect by comparing the two models with the deviance information criterion (DIC), an information criterion that can be used to compare Bayesian models in the same way that AIC can be used to compare frequentist fits. DIC is provided as a portion to the output from the <code>print</code> command applied to a JAGS model fit.</p>
<div class="sourceCode" id="cb593"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb593-1"><a href="generalized-linear-models.html#cb593-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(jagsfit)</span></code></pre></div>
<pre><code>## Inference for Bugs model at &quot;C:/Users/krgross/AppData/Local/Temp/RtmpywblRj/model62a8671b38a3.txt&quot;, fit using jags,
##  3 chains, each with 50000 iterations (first 25000 discarded), n.thin = 5
##  n.sims = 15000 iterations saved
##          mu.vect sd.vect    2.5%     25%     50%     75%   97.5%  Rhat n.eff
## a         -1.593   0.544  -2.656  -1.961  -1.582  -1.223  -0.546 1.001 12000
## b          0.069   0.014   0.042   0.059   0.069   0.078   0.095 1.001  9200
## deviance 154.475   2.737 152.508 153.036 153.848 155.210 159.742 1.001 15000
## 
## For each parameter, n.eff is a crude measure of effective sample size,
## and Rhat is the potential scale reduction factor (at convergence, Rhat=1).
## 
## DIC info (using the rule, pD = var(deviance)/2)
## pD = 3.7 and DIC = 158.2
## DIC is an estimate of expected predictive error (lower deviance is better).</code></pre>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb595-1"><a href="generalized-linear-models.html#cb595-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(jagsfit2)</span></code></pre></div>
<pre><code>## Inference for Bugs model at &quot;C:/Users/krgross/AppData/Local/Temp/RtmpywblRj/model62a83a311810.txt&quot;, fit using jags,
##  3 chains, each with 50000 iterations (first 25000 discarded), n.thin = 5
##  n.sims = 15000 iterations saved
##          mu.vect sd.vect    2.5%     25%     50%     75%   97.5%  Rhat n.eff
## a         -1.654   0.622  -2.913  -2.065  -1.640  -1.233  -0.482 1.004   680
## b          0.069   0.016   0.039   0.059   0.069   0.080   0.101 1.003   850
## sd_eps     0.271   0.132   0.081   0.167   0.252   0.352   0.574 1.001 15000
## deviance 147.148   6.377 133.573 142.883 147.837 151.760 158.083 1.001 15000
## 
## For each parameter, n.eff is a crude measure of effective sample size,
## and Rhat is the potential scale reduction factor (at convergence, Rhat=1).
## 
## DIC info (using the rule, pD = var(deviance)/2)
## pD = 20.3 and DIC = 167.5
## DIC is an estimate of expected predictive error (lower deviance is better).</code></pre>
<p>In this case, the DIC favors the model without the observation-level random effect.</p>
<p>Before moving on, it is worth noting that this Poisson regression with an observation-level random effect is the type of model that is much easier to fit from a Bayesian perspective. To approach this model from the frequentist perspective, we would have to write down, and maximize, the likelihood, which is a function of the model’s three parameters: <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, and <span class="math inline">\(\sigma^2_\eta\)</span>. However, to write down the likelihood, we would have to integrate out the observation-level random effects. For the elephant data, this would correspond to an integral with 41 dimensions! While we could conceivably write this down, for all intents and purposes the likelihood would be impossible to compute, let alone to maximize. From a Bayesian perspective, though, adding latent random effects to a model with a non-normal response is nearly trivial.</p>
<p>The above discussion begs the question of just how programs like <code>lme4::lmer</code> fit mixed-effect models in the first place. It turns out that, with a Gaussian response, the high-dimensional integral in the likelihood can be simplified without having to compute the entire integral numerically. This simplification flows from the fact that Gaussian random variates have a natural multivariate form. With a non-Gaussian response, things become substantially harder. When we study generalized linear mixed models, we will see some ideas for computing these likelihood functions, but all such approaches ultimately rely on computational approximations instead of evaluating the underlying integrals directly.</p>
</div>
</div>
<div id="binary-responses" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Binary responses<a href="generalized-linear-models.html#binary-responses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We generally distinguish between two types of data with binary responses: Data in which each individual record is a separate a binary response, and data in which each record consists of a group of binary observations. The same methods can be used for either type of data. We will begin by studying a data set with individual binary responses, and then use the industrial melanism data to illustrate grouped binary responses.</p>
<div id="individual-binary-responses-tb-in-boar" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Individual binary responses: TB in boar<a href="generalized-linear-models.html#individual-binary-responses-tb-in-boar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To illustrate individual binary data, we will use a data set analyzed by Zuur et al. (2009) in their Ch. 10. As explained by Zuur et al., these data describe the incidence of “tuberculosis-like lesions in wild boar <em>Sus scrofa</em>” in southern Spain, and were originally collected by Vicente et al. (2006). The potential explanatory variables in the data set include a measure of the animal’s size, it’s sex, and a grouping into one of four age classes.</p>
<p>Preparatory work:</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb597-1"><a href="generalized-linear-models.html#cb597-1" aria-hidden="true" tabindex="-1"></a>boar <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/boar.txt&quot;</span>, <span class="at">head =</span> T)</span>
<span id="cb597-2"><a href="generalized-linear-models.html#cb597-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb597-3"><a href="generalized-linear-models.html#cb597-3" aria-hidden="true" tabindex="-1"></a><span class="co"># remove incomplete records</span></span>
<span id="cb597-4"><a href="generalized-linear-models.html#cb597-4" aria-hidden="true" tabindex="-1"></a>boar <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(boar)</span>
<span id="cb597-5"><a href="generalized-linear-models.html#cb597-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb597-6"><a href="generalized-linear-models.html#cb597-6" aria-hidden="true" tabindex="-1"></a><span class="co"># convert sex to a factor</span></span>
<span id="cb597-7"><a href="generalized-linear-models.html#cb597-7" aria-hidden="true" tabindex="-1"></a>boar<span class="sc">$</span>SEX <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(boar<span class="sc">$</span>SEX)</span>
<span id="cb597-8"><a href="generalized-linear-models.html#cb597-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb597-9"><a href="generalized-linear-models.html#cb597-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(boar) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;tb&quot;</span>, <span class="st">&quot;sex&quot;</span>, <span class="st">&quot;age&quot;</span>, <span class="st">&quot;length&quot;</span>)</span>
<span id="cb597-10"><a href="generalized-linear-models.html#cb597-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(boar)</span></code></pre></div>
<pre><code>##        tb         sex          age            length     
##  Min.   :0.0000   1:206   Min.   :1.000   Min.   : 46.5  
##  1st Qu.:0.0000   2:288   1st Qu.:3.000   1st Qu.:107.0  
##  Median :0.0000           Median :3.000   Median :122.0  
##  Mean   :0.4575           Mean   :3.142   Mean   :117.3  
##  3rd Qu.:1.0000           3rd Qu.:4.000   3rd Qu.:130.4  
##  Max.   :1.0000           Max.   :4.000   Max.   :165.0</code></pre>
<p>We’ll fit the usual logistic regression model first, considering only the animal’s size as a predictor. Size in this case is a measure of the length of the animal, in cm.</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb599-1"><a href="generalized-linear-models.html#cb599-1" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(tb <span class="sc">~</span> length, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>), <span class="at">data =</span> boar)</span>
<span id="cb599-2"><a href="generalized-linear-models.html#cb599-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = tb ~ length, family = binomial(link = &quot;logit&quot;), 
##     data = boar)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -4.137107   0.695381  -5.949 2.69e-09 ***
## length       0.033531   0.005767   5.814 6.09e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 681.25  on 493  degrees of freedom
## Residual deviance: 641.23  on 492  degrees of freedom
## AIC: 645.23
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb601-1"><a href="generalized-linear-models.html#cb601-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(boar, <span class="fu">plot</span>(tb <span class="sc">~</span> length))</span>
<span id="cb601-2"><a href="generalized-linear-models.html#cb601-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb601-3"><a href="generalized-linear-models.html#cb601-3" aria-hidden="true" tabindex="-1"></a><span class="co"># add a line for the fitted probabilities of tb</span></span>
<span id="cb601-4"><a href="generalized-linear-models.html#cb601-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb601-5"><a href="generalized-linear-models.html#cb601-5" aria-hidden="true" tabindex="-1"></a>new.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">length =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(boar<span class="sc">$</span>length),</span>
<span id="cb601-6"><a href="generalized-linear-models.html#cb601-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">to   =</span> <span class="fu">max</span>(boar<span class="sc">$</span>length),</span>
<span id="cb601-7"><a href="generalized-linear-models.html#cb601-7" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">length =</span> <span class="dv">100</span>))</span>
<span id="cb601-8"><a href="generalized-linear-models.html#cb601-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb601-9"><a href="generalized-linear-models.html#cb601-9" aria-hidden="true" tabindex="-1"></a>predict.fm1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm1, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb601-10"><a href="generalized-linear-models.html#cb601-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb601-11"><a href="generalized-linear-models.html#cb601-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>length, <span class="at">y =</span> predict.fm1<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb601-12"><a href="generalized-linear-models.html#cb601-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb601-13"><a href="generalized-linear-models.html#cb601-13" aria-hidden="true" tabindex="-1"></a><span class="co"># add lines for standard errors</span></span>
<span id="cb601-14"><a href="generalized-linear-models.html#cb601-14" aria-hidden="true" tabindex="-1"></a><span class="co"># use critical value from z distribution here because</span></span>
<span id="cb601-15"><a href="generalized-linear-models.html#cb601-15" aria-hidden="true" tabindex="-1"></a><span class="co"># the scale parameter is not estimated</span></span>
<span id="cb601-16"><a href="generalized-linear-models.html#cb601-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb601-17"><a href="generalized-linear-models.html#cb601-17" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>length, </span>
<span id="cb601-18"><a href="generalized-linear-models.html#cb601-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm1<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm1<span class="sc">$</span>se.fit, </span>
<span id="cb601-19"><a href="generalized-linear-models.html#cb601-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb601-20"><a href="generalized-linear-models.html#cb601-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb601-21"><a href="generalized-linear-models.html#cb601-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb601-22"><a href="generalized-linear-models.html#cb601-22" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>length, </span>
<span id="cb601-23"><a href="generalized-linear-models.html#cb601-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm1<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm1<span class="sc">$</span>se.fit, </span>
<span id="cb601-24"><a href="generalized-linear-models.html#cb601-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb601-25"><a href="generalized-linear-models.html#cb601-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Regression coefficients in logistic regression can be a bit hard to interpret. One interpretation flows from exponentiating the regression coefficient to obtain an odds ratio. For the boar data, the regression coefficient of 0.0335 corresponds to an odds ratio of <span class="math inline">\(e^{0.0335}\)</span> = 1.034. This means that for two boars that differ by one cm in length, the larger boar’s odds of having a TB-like lesion will be 1.034 times the smaller boar’s odds of having such a lesion.</p>
<p>Overdispersion is typically not an issue with individual binary response data. Nonetheless, the pseudo-<span class="math inline">\(R^2\)</span> here is fairly low. We can try the probit and complementary log-log links to see if we obtain a better fit:</p>
<div class="sourceCode" id="cb602"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb602-1"><a href="generalized-linear-models.html#cb602-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probit link</span></span>
<span id="cb602-2"><a href="generalized-linear-models.html#cb602-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb602-3"><a href="generalized-linear-models.html#cb602-3" aria-hidden="true" tabindex="-1"></a>fm1a <span class="ot">&lt;-</span> <span class="fu">glm</span>(tb <span class="sc">~</span> length, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;probit&quot;</span>), <span class="at">data =</span> boar)</span>
<span id="cb602-4"><a href="generalized-linear-models.html#cb602-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb602-5"><a href="generalized-linear-models.html#cb602-5" aria-hidden="true" tabindex="-1"></a><span class="co"># complementary log-log link</span></span>
<span id="cb602-6"><a href="generalized-linear-models.html#cb602-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb602-7"><a href="generalized-linear-models.html#cb602-7" aria-hidden="true" tabindex="-1"></a>fm1b <span class="ot">&lt;-</span> <span class="fu">glm</span>(tb <span class="sc">~</span> length, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;cloglog&quot;</span>), <span class="at">data =</span> boar)</span>
<span id="cb602-8"><a href="generalized-linear-models.html#cb602-8" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fm1, fm1a, fm1b)</span></code></pre></div>
<pre><code>##      df      AIC
## fm1   2 645.2265
## fm1a  2 645.2665
## fm1b  2 645.6100</code></pre>
<div class="sourceCode" id="cb604"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb604-1"><a href="generalized-linear-models.html#cb604-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a plot to compare the fits with the different links</span></span>
<span id="cb604-2"><a href="generalized-linear-models.html#cb604-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb604-3"><a href="generalized-linear-models.html#cb604-3" aria-hidden="true" tabindex="-1"></a>predict.fm1a <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm1a, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb604-4"><a href="generalized-linear-models.html#cb604-4" aria-hidden="true" tabindex="-1"></a>predict.fm1b <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm1b, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb604-5"><a href="generalized-linear-models.html#cb604-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb604-6"><a href="generalized-linear-models.html#cb604-6" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(boar, <span class="fu">plot</span>(tb <span class="sc">~</span> length))</span>
<span id="cb604-7"><a href="generalized-linear-models.html#cb604-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb604-8"><a href="generalized-linear-models.html#cb604-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>length, <span class="at">y =</span> predict.fm1<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb604-9"><a href="generalized-linear-models.html#cb604-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>length, <span class="at">y =</span> predict.fm1a<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb604-10"><a href="generalized-linear-models.html#cb604-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>length, <span class="at">y =</span> predict.fm1b<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;forestgreen&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb604-11"><a href="generalized-linear-models.html#cb604-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb604-12"><a href="generalized-linear-models.html#cb604-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;left&quot;</span>, </span>
<span id="cb604-13"><a href="generalized-linear-models.html#cb604-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">leg =</span> <span class="fu">c</span>(<span class="st">&quot;logit&quot;</span>, <span class="st">&quot;probit&quot;</span>, <span class="st">&quot;cloglog&quot;</span>), </span>
<span id="cb604-14"><a href="generalized-linear-models.html#cb604-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;forestgreen&quot;</span>), </span>
<span id="cb604-15"><a href="generalized-linear-models.html#cb604-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>The logit and probit links are nearly identical. The complementary log-log link differs slightly, but the logit link is AIC-best.</p>
<p>Try adding sex and age class as predictors. Some of the MLEs cannot be found, because none of the individuals with and are infected, thus the MLE of the log odds of infection for this group (which happens to be the baseline) is <span class="math inline">\(-\infty\)</span>. This phenomenon is known as “complete separation”.</p>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="generalized-linear-models.html#cb605-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a model with sex, age (as a categorical predictor) and their interaction</span></span>
<span id="cb605-2"><a href="generalized-linear-models.html#cb605-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-3"><a href="generalized-linear-models.html#cb605-3" aria-hidden="true" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(tb <span class="sc">~</span> length <span class="sc">+</span> sex <span class="sc">*</span> <span class="fu">as.factor</span>(age),</span>
<span id="cb605-4"><a href="generalized-linear-models.html#cb605-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> binomial,</span>
<span id="cb605-5"><a href="generalized-linear-models.html#cb605-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> boar)</span>
<span id="cb605-6"><a href="generalized-linear-models.html#cb605-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-7"><a href="generalized-linear-models.html#cb605-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = tb ~ length + sex * as.factor(age), family = binomial, 
##     data = boar)
## 
## Coefficients:
##                       Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)          -16.55356  724.50177  -0.023    0.982
## length                 0.01840    0.01253   1.469    0.142
## sex2                  14.19739  724.50190   0.020    0.984
## as.factor(age)2       13.83446  724.50169   0.019    0.985
## as.factor(age)3       14.31136  724.50191   0.020    0.984
## as.factor(age)4       14.68141  724.50219   0.020    0.984
## sex2:as.factor(age)2 -14.53254  724.50204  -0.020    0.984
## sex2:as.factor(age)3 -14.36861  724.50196  -0.020    0.984
## sex2:as.factor(age)4 -14.53354  724.50196  -0.020    0.984
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 681.25  on 493  degrees of freedom
## Residual deviance: 635.43  on 485  degrees of freedom
## AIC: 653.43
## 
## Number of Fisher Scoring iterations: 14</code></pre>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb607-1"><a href="generalized-linear-models.html#cb607-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(boar, <span class="fu">table</span>(tb, age, sex))</span></code></pre></div>
<pre><code>## , , sex = 1
## 
##    age
## tb   1  2  3  4
##   0  4 37 37 28
##   1  0 14 34 52
## 
## , , sex = 2
## 
##    age
## tb   1  2  3  4
##   0  7 40 62 53
##   1  2 11 48 65</code></pre>
<p>There are several possible remedies here. The first is to try to reduce the number of parameters in the model, perhaps by eliminating the interaction between sex and age class.</p>
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb609-1"><a href="generalized-linear-models.html#cb609-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a model with sex, age (as a categorical predictor) and their interaction</span></span>
<span id="cb609-2"><a href="generalized-linear-models.html#cb609-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb609-3"><a href="generalized-linear-models.html#cb609-3" aria-hidden="true" tabindex="-1"></a>fm3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(tb <span class="sc">~</span> length <span class="sc">+</span> sex <span class="sc">+</span> <span class="fu">as.factor</span>(age),</span>
<span id="cb609-4"><a href="generalized-linear-models.html#cb609-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">family =</span> binomial,</span>
<span id="cb609-5"><a href="generalized-linear-models.html#cb609-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> boar)</span>
<span id="cb609-6"><a href="generalized-linear-models.html#cb609-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb609-7"><a href="generalized-linear-models.html#cb609-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm3)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = tb ~ length + sex + as.factor(age), family = binomial, 
##     data = boar)
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)     -2.67730    1.07306  -2.495   0.0126 *
## length           0.01959    0.01237   1.584   0.1133  
## sex2            -0.24297    0.19354  -1.255   0.2093  
## as.factor(age)2 -0.19847    0.92641  -0.214   0.8304  
## as.factor(age)3  0.33908    1.06938   0.317   0.7512  
## as.factor(age)4  0.59041    1.20582   0.490   0.6244  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 681.25  on 493  degrees of freedom
## Residual deviance: 637.41  on 488  degrees of freedom
## AIC: 649.41
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>A second option is to use so-called ``exact’’ methods for inference. There doesn’t appear to be a good package available for implementing these methods in R. Other software packages might be necessary.</p>
</div>
<div id="grouped-binary-data-industrial-melanism" class="section level3 hasAnchor" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> Grouped binary data: Industrial melanism<a href="generalized-linear-models.html#grouped-binary-data-industrial-melanism" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ll start with the standard logistic regression model for the industrial melanism data. We are primarily interested in determining if the effect of color morph on removal rate changes with distance from Liverpool. For grouped binary data, we need to specify both the number of “successes” and number of “failures” as the response variable in the model. Here, we use <code>cbind</code> to create a two-column matrix with the number of “successes” (moths removed) in the first column, and the number of “failures” (moths not removed) in the second column. See the help documentation for <code>glm</code> for more details.</p>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb611-1"><a href="generalized-linear-models.html#cb611-1" aria-hidden="true" tabindex="-1"></a>moth <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/moth.txt&quot;</span>, <span class="at">head =</span> <span class="cn">TRUE</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb611-2"><a href="generalized-linear-models.html#cb611-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb611-3"><a href="generalized-linear-models.html#cb611-3" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(removed, placed <span class="sc">-</span> removed) <span class="sc">~</span> morph <span class="sc">*</span> distance, </span>
<span id="cb611-4"><a href="generalized-linear-models.html#cb611-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>),</span>
<span id="cb611-5"><a href="generalized-linear-models.html#cb611-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> moth)</span>
<span id="cb611-6"><a href="generalized-linear-models.html#cb611-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb611-7"><a href="generalized-linear-models.html#cb611-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cbind(removed, placed - removed) ~ morph * distance, 
##     family = binomial(link = &quot;logit&quot;), data = moth)
## 
## Coefficients:
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         -1.128987   0.197906  -5.705 1.17e-08 ***
## morphlight           0.411257   0.274490   1.498 0.134066    
## distance             0.018502   0.005645   3.277 0.001048 ** 
## morphlight:distance -0.027789   0.008085  -3.437 0.000588 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 35.385  on 13  degrees of freedom
## Residual deviance: 13.230  on 10  degrees of freedom
## AIC: 83.904
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Grouped binary data are often overdispersed relative to the variance implied by a binomial distribution. In this case, we would call the overdispersion “extra-binomial” variation. As with count data, we can deal with overdispersion through a quasi-likelihood approach:</p>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb613-1"><a href="generalized-linear-models.html#cb613-1" aria-hidden="true" tabindex="-1"></a>fm1q <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(removed, placed <span class="sc">-</span> removed) <span class="sc">~</span> morph <span class="sc">*</span> distance, </span>
<span id="cb613-2"><a href="generalized-linear-models.html#cb613-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> <span class="fu">quasibinomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>),</span>
<span id="cb613-3"><a href="generalized-linear-models.html#cb613-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> moth)</span>
<span id="cb613-4"><a href="generalized-linear-models.html#cb613-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb613-5"><a href="generalized-linear-models.html#cb613-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1q)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cbind(removed, placed - removed) ~ morph * distance, 
##     family = quasibinomial(link = &quot;logit&quot;), data = moth)
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         -1.128987   0.223104  -5.060 0.000492 ***
## morphlight           0.411257   0.309439   1.329 0.213360    
## distance             0.018502   0.006364   2.907 0.015637 *  
## morphlight:distance -0.027789   0.009115  -3.049 0.012278 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasibinomial family taken to be 1.270859)
## 
##     Null deviance: 35.385  on 13  degrees of freedom
## Residual deviance: 13.230  on 10  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>As with count data, using quasi-likelihood to estimate the scale (or dispersion) parameter increases the estimates of the standard errors of the coefficients by an amount equal to the square root of the estimated scale parameter.</p>
<p>The <span class="math inline">\(t\)</span>-test of the interaction between color morph and distance indicates that there is a statistically significant difference in how the proportion of moth removes changes over the distance transect between the two color morphs.</p>
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb615-1"><a href="generalized-linear-models.html#cb615-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> moth<span class="sc">$</span>distance, </span>
<span id="cb615-2"><a href="generalized-linear-models.html#cb615-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> <span class="fu">residuals</span>(fm1q, <span class="at">type =</span> <span class="st">&quot;deviance&quot;</span>),</span>
<span id="cb615-3"><a href="generalized-linear-models.html#cb615-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;distance&quot;</span>,</span>
<span id="cb615-4"><a href="generalized-linear-models.html#cb615-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Deviance residuals&quot;</span>)</span>
<span id="cb615-5"><a href="generalized-linear-models.html#cb615-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb615-6"><a href="generalized-linear-models.html#cb615-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>The plot of the residuals suggests that we should include a random effect for the sampling station. This makes complete sense. The data for the two color morphs at each station share whatever other characteristics make the station unique, and are thus correlated. To account for this correlation, we need to introduce a random effect for the station. This again gets us into the world of generalized linear mixed models. Before proceeding, we’ll write the model down. Let <span class="math inline">\(i=1,2\)</span> index the two color morphs, and let <span class="math inline">\(j = 1, \ldots, 7\)</span> index the stations. Let <span class="math inline">\(y_{ij}\)</span> be the number of moths removed, let <span class="math inline">\(n_{ij}\)</span> be the number of moths placed, and let <span class="math inline">\(x_j\)</span> be the distance of the station from Liverpool. We wish to fit the model
<span class="math display">\[\begin{align*}
y_{ij} &amp; \sim \mathrm{Binom}(p_{ij}, n_{ij})\\
\mathrm{logit}(p_{ij})  &amp; = \eta_{ij} \\
\eta_{ij} &amp; = a_i + b_i x_j + L_j \\
L_j &amp; \sim \mathcal{N}(0, \sigma^2_L)
\end{align*}\]</span></p>
<p>The <span class="math inline">\(L_j\)</span>’s are our [l]ocation-specific random effects that capture any other station-to-station differences above and beyond the station’s distance from Liverpool. (It turns out that an observation-level random effect does not improve the model, at least as indicated by DIC.) Because this model includes both a random effect for the station and a non-Gaussian response, it is a generalized linear mixed model (GLMM). We postpone our discussion accordingly.</p>
<!-- We have already mentioned that the $t$-statistics reported in `summary.glm` are based on standard errors calculated from the curvature (Hessian) of the negative log-likelihood at the MLEs, with df determined by the df available for the residual deviance.  An alternative approach for testing for the significance of model terms is to use the residual deviance to compare nested models, much as one would use $F$-tests to compare nested models in ordinary least squares.  Here is a bit of theory.  Let $D$ denote the residual deviance for a model.  Suppose we are comparing two nested models: a parameter poor model that we call model 0, and a parameter rich model that we call model 1.  The parameter-rich model nests the parameter poor model.  Let $p_0$ and $p_1$ be the number of estimated parameters in the linear predictor of models 0 and 1, respectively, and let $D_0$ and $D_1$ denote the (residual) deviances of both models.  In the usual way, we wish to test whether or not the parameter-rich model provides a statistically significant improvement in fit over the parameter-poor model. -->
<!-- There are two separate approaches here depending on whether the scale parameter is known, or is estimated from the data.  If the scale parameter is known to be $\phi$, then define the scaled deviance as $D^* = D / \phi$.  The LRT to compare the two models is equal to the drop in the scaled deviance, $D^*_0 - D^*_1$.  Under the null hypothesis that the parameter-poor model generated the data, the test statistic has a $\chi^2$ distribution with $p_1 - p_0$ degrees of freedom. -->
<!-- If the scale parameter is estimated from the data, then we work with the (residual) deviances directly.  In this case, we calculate the $F$-statistic -->
<!-- $$ -->
<!-- F = \frac{(D_0 - D_1)/(p_1 - p_0)}{D_1 / (n - p_1)}. -->
<!-- $$ -->
<!-- Note that this is generalization of the usual $F$-statistic for comparing nested models from OLS.  Under the null hypothesis, the test statistic has an $F_{p_1 - p_0, n - p_1}$ distribution. -->
<!-- # test for interaction between distance and morph -->
<!-- ```{r} -->
<!-- fm2q <- glm(cbind(removed, placed - removed) ~ morph + distance,  -->
<!--             family = quasibinomial(link = "logit"), -->
<!--             data = moth) -->
<!-- anova(fm2q, fm1q, test = "F") -->
<!-- ``` -->
</div>
</div>
<div id="zero-adjusted-models-for-count-data" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Zero-adjusted models for count data<a href="generalized-linear-models.html#zero-adjusted-models-for-count-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In count data, the frequency of zeros often differs from what the standard Poisson or negative binomial distributions would predict. This occurs because the processes that lead to zero counts are often separate from the processes that govern the intensity of non-zero counts. For example, when counting parasite loads of animals, one process may determine if an individual animal is infected at all, and a second process may determine the intensity of the parasite load for those animals that are infected. This section discusses models for count data in which the proportion of zeros is modeled separately from the rest of the distribution. Any of these models may be paired with Poisson or negative binomial models for the non-zero counts.</p>
<div id="zero-truncated-models" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Zero-truncated models<a href="generalized-linear-models.html#zero-truncated-models" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Zero-truncated distributions are simply those that condition on the count variable being greater than 0. They are appropriate when the sampling procedure makes zeros unobservable. Zero-truncated Poisson and negative binomial distributions are available as something of a side benefit the R library <code>VGAM</code> (an acronym for vector generalized additive models). This package provides the function <code>vglm</code> (a version of <code>glm</code> that allows for vector-valued responses), which in turn accommodates the distribution families <code>pospoisson</code> and <code>posnegbinomial</code>. The “pos” portion of each refers to the fact that the counts must be strictly positive.</p>
<p>We illustrate the use of a zero-truncated distribution with a species-abundance data set for butterflies provided in the <code>VGAM</code> package. The description of the data set in <code>VGAM</code> reads: “About 3300 individual butterflies were caught in Malaya by naturalist Corbet trapping butterflies. They were classified to about 500 species.” The data give the frequencies in a species abundance distribution.</p>
<div class="sourceCode" id="cb616"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb616-1"><a href="generalized-linear-models.html#cb616-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(VGAM)</span></code></pre></div>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb617-1"><a href="generalized-linear-models.html#cb617-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(corbet)</span>
<span id="cb617-2"><a href="generalized-linear-models.html#cb617-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(corbet)</span></code></pre></div>
<pre><code>##   ofreq species
## 1     1     118
## 2     2      74
## 3     3      44
## 4     4      24
## 5     5      29
## 6     6      22</code></pre>
<div class="sourceCode" id="cb619"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb619-1"><a href="generalized-linear-models.html#cb619-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(corbet, <span class="fu">barplot</span>(species, <span class="at">names =</span> ofreq,</span>
<span id="cb619-2"><a href="generalized-linear-models.html#cb619-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xlab =</span> <span class="st">&quot;no. of individuals&quot;</span>,</span>
<span id="cb619-3"><a href="generalized-linear-models.html#cb619-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">ylab =</span> <span class="st">&quot;frequency&quot;</span>))</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>We will fit a zero-truncated negative binomial distribution to these data, and compare the fitted zero-truncated distribution to the data.</p>
<!-- Note: Something is weird here.  The ratio of the first two fitted probabilities is NOT the same as the ratio of the probability masses obtained by dnbinom evaluated at the parameter estimates.  Check into this. -->
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="generalized-linear-models.html#cb620-1" aria-hidden="true" tabindex="-1"></a>corbet.fit <span class="ot">&lt;-</span> <span class="fu">vglm</span>(ofreq <span class="sc">~</span> <span class="dv">1</span>, <span class="at">family =</span> posnegbinomial, <span class="at">weights =</span> species, <span class="at">data =</span> corbet)</span>
<span id="cb620-2"><a href="generalized-linear-models.html#cb620-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Coef</span>(corbet.fit)</span></code></pre></div>
<pre><code>##      munb      size 
## 4.4802271 0.4906395</code></pre>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="generalized-linear-models.html#cb622-1" aria-hidden="true" tabindex="-1"></a>mu.hat <span class="ot">&lt;-</span> <span class="fu">Coef</span>(corbet.fit)[<span class="st">&quot;munb&quot;</span>]</span>
<span id="cb622-2"><a href="generalized-linear-models.html#cb622-2" aria-hidden="true" tabindex="-1"></a>k.hat  <span class="ot">&lt;-</span> <span class="fu">Coef</span>(corbet.fit)[<span class="st">&quot;size&quot;</span>]</span>
<span id="cb622-3"><a href="generalized-linear-models.html#cb622-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb622-4"><a href="generalized-linear-models.html#cb622-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2023-05-26: dgainnbinom seems to have been deprecated from VGAM</span></span>
<span id="cb622-5"><a href="generalized-linear-models.html#cb622-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb622-6"><a href="generalized-linear-models.html#cb622-6" aria-hidden="true" tabindex="-1"></a><span class="co"># fitted.probs &lt;- dgaitnbinom(x = corbet$ofreq, k.hat, munb.p = fitted(corbet.fit), truncate = 0)</span></span>
<span id="cb622-7"><a href="generalized-linear-models.html#cb622-7" aria-hidden="true" tabindex="-1"></a><span class="co"># fitted.vals &lt;- sum(corbet$species) * fitted.probs</span></span>
<span id="cb622-8"><a href="generalized-linear-models.html#cb622-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb622-9"><a href="generalized-linear-models.html#cb622-9" aria-hidden="true" tabindex="-1"></a><span class="co"># barplot(cbind(corbet$species, fitted.vals), beside = T, names = c(&quot;actual&quot;, &quot;fitted&quot;))</span></span></code></pre></div>
</div>
<div id="zero-inflated-models" class="section level3 hasAnchor" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Zero-inflated models<a href="generalized-linear-models.html#zero-inflated-models" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As the name suggests, zero-inflated (henceforth ZI) models are appropriate when zeros are more frequent than the distribution of the non-zero counts would suggest. ZI models have two components. In the “zero-inflation” component, a logistic regression (or some other generalized linear model for a binary response) captures whether the response is a “false” zero or a realization from a proper count distribution. In the “count” component, a generalized linear model for count data (such as Poisson regression) is used to model the distribution of the non-false-zero counts. The ZI model accords with the thinking that the data arise from a combination of two separate mechanisms: a first mechanism that determines whether or not the count is a “false” zero, and a second that determines the count if it is not a false zero. In ecology, the zero-inflation component might correspond to (true) presence vs. absence, and the count component might correspond to the detected intensity conditional on presence.</p>
<p>To illustrate ZI models, we will use the cod parasite data described in <span class="math inline">\(\S\)</span> 11.3.2 of <span class="citation">Zuur et al. (<a href="#ref-zuur2009" role="doc-biblioref">2009</a>)</span>. These data are counts of the number of trypanosome blood parasites in individual cod, and were initially reported in Hemmingsen et al. (2005). First we load the data and do some housekeeping.</p>
<div class="sourceCode" id="cb623"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb623-1"><a href="generalized-linear-models.html#cb623-1" aria-hidden="true" tabindex="-1"></a>cod <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/ParasiteCod.txt&quot;</span>, <span class="at">head =</span> T)</span>
<span id="cb623-2"><a href="generalized-linear-models.html#cb623-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb623-3"><a href="generalized-linear-models.html#cb623-3" aria-hidden="true" tabindex="-1"></a><span class="co"># remove observations with missing data</span></span>
<span id="cb623-4"><a href="generalized-linear-models.html#cb623-4" aria-hidden="true" tabindex="-1"></a>cod <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(cod)</span>
<span id="cb623-5"><a href="generalized-linear-models.html#cb623-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cod)</span></code></pre></div>
<pre><code>##      Sample         Intensity         Prevalence          Year     
##  Min.   :   1.0   Min.   :  0.000   Min.   :0.0000   Min.   :1999  
##  1st Qu.: 299.5   1st Qu.:  0.000   1st Qu.:0.0000   1st Qu.:1999  
##  Median : 598.0   Median :  0.000   Median :0.0000   Median :2000  
##  Mean   : 613.7   Mean   :  6.209   Mean   :0.4534   Mean   :2000  
##  3rd Qu.: 955.5   3rd Qu.:  4.000   3rd Qu.:1.0000   3rd Qu.:2001  
##  Max.   :1254.0   Max.   :257.000   Max.   :1.0000   Max.   :2001  
##      Depth           Weight         Length            Sex       
##  Min.   : 50.0   Min.   :  34   Min.   : 17.00   Min.   :0.000  
##  1st Qu.:110.0   1st Qu.: 769   1st Qu.: 44.00   1st Qu.:1.000  
##  Median :180.0   Median :1446   Median : 54.00   Median :1.000  
##  Mean   :176.3   Mean   :1718   Mean   : 53.53   Mean   :1.427  
##  3rd Qu.:236.0   3rd Qu.:2232   3rd Qu.: 62.00   3rd Qu.:2.000  
##  Max.   :293.0   Max.   :9990   Max.   :101.00   Max.   :2.000  
##      Stage            Age              Area      
##  Min.   :0.000   Min.   : 0.000   Min.   :1.000  
##  1st Qu.:1.000   1st Qu.: 3.000   1st Qu.:2.000  
##  Median :1.000   Median : 4.000   Median :3.000  
##  Mean   :1.426   Mean   : 4.118   Mean   :2.568  
##  3rd Qu.:2.000   3rd Qu.: 5.000   3rd Qu.:3.000  
##  Max.   :4.000   Max.   :10.000   Max.   :4.000</code></pre>
<p>There are a large number of potential predictors. Following the analysis in Zuur et al., we will focus on the effects of length (a measure of the fish’s size), year (which we will treat as a categorical predictor for flexibility), and “area”, a categorical predictor for one of four areas in which the fish was sampled. Before beginning, we will plot the data. In the plot below, each row of the plot corresponds to a year, and each column (unlabeled) corresponds to one of the four areas, going from area 1 (the leftmost column) to area 4 (the rightmost column). Because most of the parasite loads are zero or close to zero, we plot parasite load on a log(y + 1) scale.</p>
<div class="sourceCode" id="cb625"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb625-1"><a href="generalized-linear-models.html#cb625-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb625-2"><a href="generalized-linear-models.html#cb625-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb625-3"><a href="generalized-linear-models.html#cb625-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">unique</span>(cod<span class="sc">$</span>Year)) {</span>
<span id="cb625-4"><a href="generalized-linear-models.html#cb625-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="fu">sort</span>(<span class="fu">unique</span>(cod<span class="sc">$</span>Area))) {</span>
<span id="cb625-5"><a href="generalized-linear-models.html#cb625-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb625-6"><a href="generalized-linear-models.html#cb625-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">with</span>(<span class="fu">subset</span>(cod, Year <span class="sc">==</span> i <span class="sc">&amp;</span> Area <span class="sc">==</span> j), </span>
<span id="cb625-7"><a href="generalized-linear-models.html#cb625-7" aria-hidden="true" tabindex="-1"></a>         <span class="fu">plot</span>(<span class="fu">log</span>(Intensity <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">~</span> Length, <span class="at">xlim =</span> <span class="fu">range</span>(cod<span class="sc">$</span>Length), <span class="at">ylim =</span> <span class="fu">log</span>(<span class="fu">range</span>(cod<span class="sc">$</span>Intensity) <span class="sc">+</span> <span class="dv">1</span>),</span>
<span id="cb625-8"><a href="generalized-linear-models.html#cb625-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">xlab =</span> <span class="st">&quot;&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;&quot;</span>, <span class="at">yaxt =</span> <span class="st">&quot;n&quot;</span>))</span>
<span id="cb625-9"><a href="generalized-linear-models.html#cb625-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb625-10"><a href="generalized-linear-models.html#cb625-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span> <span class="fu">log</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">100</span>) <span class="sc">+</span> <span class="dv">1</span>), <span class="at">lab =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">100</span>))</span>
<span id="cb625-11"><a href="generalized-linear-models.html#cb625-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb625-12"><a href="generalized-linear-models.html#cb625-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (j <span class="sc">==</span> <span class="dv">1</span>) <span class="fu">mtext</span>(i, <span class="at">side =</span> <span class="dv">2</span>, <span class="at">line  =</span> <span class="dv">3</span>)</span>
<span id="cb625-13"><a href="generalized-linear-models.html#cb625-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb625-14"><a href="generalized-linear-models.html#cb625-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb625-15"><a href="generalized-linear-models.html#cb625-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb625-16"><a href="generalized-linear-models.html#cb625-16" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;length&quot;</span>, <span class="at">side =</span> <span class="dv">1</span>, <span class="at">outer =</span> T, <span class="at">line =</span> <span class="dv">2</span>)</span>
<span id="cb625-17"><a href="generalized-linear-models.html#cb625-17" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;parasite intensity&quot;</span>, <span class="at">side =</span> <span class="dv">2</span>, <span class="at">outer =</span> T, <span class="at">line =</span> <span class="dv">5</span>, <span class="at">las =</span> <span class="dv">0</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>With ZI models, one can use separate model combinations of predictors for the two components. Indeed, if we think of the two components as capturing two different natural processes, then there is no reason that the predictors should have the same affect on both components. Following Zuur et al., however, we will start with a ZINB model that includes length, year, area, and an interaction between year and area for both components. Because both components are generalized linear models, both include a link function. Here, we will use the default logit link for the zero-inflation component and log link for the count component.</p>
<p>To fit ZI models, we will use the <code>pscl</code> library from R. The name <code>pscl</code> is an acronym for political science computing laboratory. The <code>pscl</code> library includes functions for ZI poisson and negative binomial models (henceforth abbreviated ZIP and ZINB models).</p>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="generalized-linear-models.html#cb626-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(pscl)</span></code></pre></div>
<pre><code>## Loading required package: pscl</code></pre>
<pre><code>## Classes and Methods for R developed in the
## Political Science Computational Laboratory
## Department of Political Science
## Stanford University
## Simon Jackman
## hurdle and zeroinfl functions by Achim Zeileis</code></pre>
<div class="sourceCode" id="cb629"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb629-1"><a href="generalized-linear-models.html#cb629-1" aria-hidden="true" tabindex="-1"></a>formula<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">formula</span>(Intensity <span class="sc">~</span> Length <span class="sc">+</span> <span class="fu">as.factor</span>(Year) <span class="sc">*</span> <span class="fu">as.factor</span>(Area))</span>
<span id="cb629-2"><a href="generalized-linear-models.html#cb629-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb629-3"><a href="generalized-linear-models.html#cb629-3" aria-hidden="true" tabindex="-1"></a>cod.nb.fm1 <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(formula<span class="fl">.1</span>, <span class="at">data  =</span> cod, <span class="at">dist =</span> <span class="st">&quot;negbin&quot;</span>) </span>
<span id="cb629-4"><a href="generalized-linear-models.html#cb629-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cod.nb.fm1)</span></code></pre></div>
<pre><code>## 
## Call:
## zeroinfl(formula = formula.1, data = cod, dist = &quot;negbin&quot;)
## 
## Pearson residuals:
##     Min      1Q  Median      3Q     Max 
## -0.6142 -0.4429 -0.3581 -0.1252 11.4529 
## 
## Count model coefficients (negbin with log link):
##                                       Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                           3.733905   0.344398  10.842  &lt; 2e-16 ***
## Length                               -0.036410   0.005108  -7.128 1.02e-12 ***
## as.factor(Year)2000                   0.063894   0.295639   0.216  0.82889    
## as.factor(Year)2001                  -0.939183   0.606056  -1.550  0.12122    
## as.factor(Area)2                      0.197761   0.329133   0.601  0.54794    
## as.factor(Area)3                     -0.646736   0.277793  -2.328  0.01991 *  
## as.factor(Area)4                      0.707493   0.252266   2.805  0.00504 ** 
## as.factor(Year)2000:as.factor(Area)2 -0.653983   0.535418  -1.221  0.22192    
## as.factor(Year)2001:as.factor(Area)2  0.967305   0.718165   1.347  0.17801    
## as.factor(Year)2000:as.factor(Area)3  1.024957   0.429599   2.386  0.01704 *  
## as.factor(Year)2001:as.factor(Area)3  1.002732   0.677502   1.480  0.13886    
## as.factor(Year)2000:as.factor(Area)4  0.534524   0.414976   1.288  0.19772    
## as.factor(Year)2001:as.factor(Area)4  0.855195   0.654394   1.307  0.19126    
## Log(theta)                           -0.966631   0.096345 -10.033  &lt; 2e-16 ***
## 
## Zero-inflation model coefficients (binomial with logit link):
##                                        Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                             0.19094    0.78133   0.244 0.806941    
## Length                                 -0.03884    0.01203  -3.227 0.001249 ** 
## as.factor(Year)2000                    -1.07163    2.00007  -0.536 0.592100    
## as.factor(Year)2001                     3.29316    0.71043   4.635 3.56e-06 ***
## as.factor(Area)2                        2.01367    0.57289   3.515 0.000440 ***
## as.factor(Area)3                        1.90528    0.54988   3.465 0.000530 ***
## as.factor(Area)4                       -0.73626    0.86228  -0.854 0.393187    
## as.factor(Year)2000:as.factor(Area)2    0.46531    2.07876   0.224 0.822883    
## as.factor(Year)2001:as.factor(Area)2   -3.20740    0.83596  -3.837 0.000125 ***
## as.factor(Year)2000:as.factor(Area)3   -0.79465    2.15756  -0.368 0.712642    
## as.factor(Year)2001:as.factor(Area)3   -3.50409    0.83000  -4.222 2.42e-05 ***
## as.factor(Year)2000:as.factor(Area)4  -13.65190 1572.67468  -0.009 0.993074    
## as.factor(Year)2001:as.factor(Area)4   -2.91045    1.10462  -2.635 0.008419 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Theta = 0.3804 
## Number of iterations in BFGS optimization: 50 
## Log-likelihood: -2450 on 27 Df</code></pre>
<p>The neatly organized output gives coefficients for each component of the model, with the count component presented first and the zero-inflation component presented second. The output for the zero-inflation component shows a very large standard error associated with the coefficient for area 4 in the year 2000. Let’s take a look at the frequency of zeros, as broken down by year and area.</p>
<div class="sourceCode" id="cb631"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb631-1"><a href="generalized-linear-models.html#cb631-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(cod, <span class="fu">table</span>(Year, Area, Intensity <span class="sc">&gt;</span> <span class="dv">0</span>))</span></code></pre></div>
<pre><code>## , ,  = FALSE
## 
##       Area
## Year     1   2   3   4
##   1999  57  65 121  34
##   2000  16  31  32   6
##   2001  63  72 112  42
## 
## , ,  = TRUE
## 
##       Area
## Year     1   2   3   4
##   1999  89  27  45  69
##   2000  39  18  43  44
##   2001   7  34  45  80</code></pre>
<p>We see that there are only a few zeros in area 4 for 2000. Thus, the zero-inflation component is trying to fit a zero probability of zero inflation for area 4 in year 2000, leading to complete separation. We need to reduce the number of parameters somehow. Lacking any better ideas, we’ll follow Zuur et al. and remove the interaction between year and area for the zero-inflation portion of the model. To do so, we need a model formula that differs between the two model components. In <code>pscl</code>, we implement this model by providing a model formula where the differing predictor combinations for the two components are separated by a vertical bar.</p>
<div class="sourceCode" id="cb633"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb633-1"><a href="generalized-linear-models.html#cb633-1" aria-hidden="true" tabindex="-1"></a>formula<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">formula</span>(Intensity <span class="sc">~</span> Length <span class="sc">+</span> <span class="fu">as.factor</span>(Year) <span class="sc">*</span> <span class="fu">as.factor</span>(Area) <span class="sc">|</span> Length </span>
<span id="cb633-2"><a href="generalized-linear-models.html#cb633-2" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">+</span> <span class="fu">as.factor</span>(Year) <span class="sc">+</span> <span class="fu">as.factor</span>(Area))</span>
<span id="cb633-3"><a href="generalized-linear-models.html#cb633-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb633-4"><a href="generalized-linear-models.html#cb633-4" aria-hidden="true" tabindex="-1"></a>cod.nb.fm2 <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(formula<span class="fl">.2</span>, <span class="at">data  =</span> cod, <span class="at">dist =</span> <span class="st">&quot;negbin&quot;</span>)</span>
<span id="cb633-5"><a href="generalized-linear-models.html#cb633-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cod.nb.fm2)</span></code></pre></div>
<pre><code>## 
## Call:
## zeroinfl(formula = formula.2, data = cod, dist = &quot;negbin&quot;)
## 
## Pearson residuals:
##     Min      1Q  Median      3Q     Max 
## -0.5911 -0.4480 -0.3794 -0.1258 12.0795 
## 
## Count model coefficients (negbin with log link):
##                                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                           3.78614    0.34093  11.105  &lt; 2e-16 ***
## Length                               -0.03669    0.00502  -7.309 2.70e-13 ***
## as.factor(Year)2000                   0.03438    0.29188   0.118  0.90624    
## as.factor(Year)2001                  -2.32204    0.38125  -6.091 1.12e-09 ***
## as.factor(Area)2                      0.12404    0.32906   0.377  0.70621    
## as.factor(Area)3                     -0.82582    0.27838  -2.966  0.00301 ** 
## as.factor(Area)4                      0.65502    0.25266   2.592  0.00953 ** 
## as.factor(Year)2000:as.factor(Area)2 -0.75547    0.50817  -1.487  0.13711    
## as.factor(Year)2001:as.factor(Area)2  2.39047    0.52066   4.591 4.41e-06 ***
## as.factor(Year)2000:as.factor(Area)3  1.21457    0.42003   2.892  0.00383 ** 
## as.factor(Year)2001:as.factor(Area)3  2.52720    0.45772   5.521 3.36e-08 ***
## as.factor(Year)2000:as.factor(Area)4  0.59338    0.41572   1.427  0.15347    
## as.factor(Year)2001:as.factor(Area)4  2.23077    0.44602   5.001 5.69e-07 ***
## Log(theta)                           -1.01444    0.09655 -10.507  &lt; 2e-16 ***
## 
## Zero-inflation model coefficients (binomial with logit link):
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)          0.92837    0.70657   1.314 0.188873    
## Length              -0.04686    0.01252  -3.744 0.000181 ***
## as.factor(Year)2000 -1.25039    0.50281  -2.487 0.012889 *  
## as.factor(Year)2001  0.25485    0.32785   0.777 0.436962    
## as.factor(Area)2     1.62679    0.48056   3.385 0.000711 ***
## as.factor(Area)3     1.19153    0.49143   2.425 0.015324 *  
## as.factor(Area)4    -1.26323    0.64393  -1.962 0.049792 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Theta = 0.3626 
## Number of iterations in BFGS optimization: 29 
## Log-likelihood: -2460 on 21 Df</code></pre>
<p>There’s a lot of output here to process. One observation we might make is that there seems to be a strongly significant negative association between length and both the probability of a false zero in the first model component, and the parasite abundance in the second model component. To visualize the model, we might plot the fitted probability of a false zero vs. length for each combination of area and year, and then plot the fitted intensity (mean) of the count process vs. length, also for each combination of area and year. See Ch. 11 of Zuur et al. for such plots.</p>
<p>Alternatively, we might merge the two model components to generate predicted values as a function of length for each year and area. The library <code>pscl</code> provides methods to extract predicted values directly; see the help documentation for <code>pscl::predict.zeroinfl</code>. We use that method here to generate predicted mean parasite counts (merging the zero-inflation and count components) for each combination of year and area. In the plot below, bear in mind that because the data are shown on a log scale, the fitted line will not necessarily pass through the center of the plotted data cloud.</p>
<div class="sourceCode" id="cb635"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb635-1"><a href="generalized-linear-models.html#cb635-1" aria-hidden="true" tabindex="-1"></a>length.vals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(cod<span class="sc">$</span>Length), <span class="at">to =</span> <span class="fu">max</span>(cod<span class="sc">$</span>Length), <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb635-2"><a href="generalized-linear-models.html#cb635-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb635-3"><a href="generalized-linear-models.html#cb635-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb635-4"><a href="generalized-linear-models.html#cb635-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">unique</span>(cod<span class="sc">$</span>Year)) {</span>
<span id="cb635-5"><a href="generalized-linear-models.html#cb635-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="fu">sort</span>(<span class="fu">unique</span>(cod<span class="sc">$</span>Area))) {</span>
<span id="cb635-6"><a href="generalized-linear-models.html#cb635-6" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb635-7"><a href="generalized-linear-models.html#cb635-7" aria-hidden="true" tabindex="-1"></a>    new.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Length =</span> length.vals, <span class="at">Year =</span> i, <span class="at">Area =</span> j)</span>
<span id="cb635-8"><a href="generalized-linear-models.html#cb635-8" aria-hidden="true" tabindex="-1"></a>    predicted.vals <span class="ot">&lt;-</span> <span class="fu">predict</span>(cod.nb.fm2, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb635-9"><a href="generalized-linear-models.html#cb635-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb635-10"><a href="generalized-linear-models.html#cb635-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(<span class="at">x =</span> <span class="fu">range</span>(cod<span class="sc">$</span>Length), <span class="at">y =</span> <span class="fu">log</span>(<span class="fu">range</span>(cod<span class="sc">$</span>Intensity) <span class="sc">+</span> <span class="dv">1</span>), <span class="at">xlab =</span> <span class="st">&quot;&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;&quot;</span>, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>, <span class="at">yaxt =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb635-11"><a href="generalized-linear-models.html#cb635-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lines</span>(<span class="fu">log</span>(predicted.vals <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">~</span> length.vals)</span>
<span id="cb635-12"><a href="generalized-linear-models.html#cb635-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb635-13"><a href="generalized-linear-models.html#cb635-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">with</span>(<span class="fu">subset</span>(cod, Year <span class="sc">==</span> i <span class="sc">&amp;</span> Area <span class="sc">==</span> j), <span class="fu">points</span>(<span class="fu">log</span>(Intensity <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">~</span> Length))</span>
<span id="cb635-14"><a href="generalized-linear-models.html#cb635-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at =</span> <span class="fu">log</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">100</span>) <span class="sc">+</span> <span class="dv">1</span>), <span class="at">lab =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">100</span>))</span>
<span id="cb635-15"><a href="generalized-linear-models.html#cb635-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb635-16"><a href="generalized-linear-models.html#cb635-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (j <span class="sc">==</span> <span class="dv">1</span>) <span class="fu">mtext</span>(i, <span class="at">side =</span> <span class="dv">2</span>, <span class="at">line  =</span> <span class="dv">3</span>)</span>
<span id="cb635-17"><a href="generalized-linear-models.html#cb635-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb635-18"><a href="generalized-linear-models.html#cb635-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb635-19"><a href="generalized-linear-models.html#cb635-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb635-20"><a href="generalized-linear-models.html#cb635-20" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;length&quot;</span>, <span class="at">side =</span> <span class="dv">1</span>, <span class="at">outer =</span> T, <span class="at">line =</span> <span class="dv">2</span>)</span>
<span id="cb635-21"><a href="generalized-linear-models.html#cb635-21" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;parasite intensity&quot;</span>, <span class="at">side =</span> <span class="dv">2</span>, <span class="at">outer =</span> T, <span class="at">line =</span> <span class="dv">6</span>, <span class="at">las =</span> <span class="dv">0</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
</div>
<div id="zero-altered-or-hurdle-models" class="section level3 hasAnchor" number="7.4.3">
<h3><span class="header-section-number">7.4.3</span> Zero-altered, or “hurdle”, models<a href="generalized-linear-models.html#zero-altered-or-hurdle-models" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Zero-altered (ZA) models, also known as hurdle models, are similar to ZI models in the sense that there are two components. However, in ZA models, the binary component models whether the response is 0 or greater than 0. This binary component of the model is called the hurdle component. The count component is then modeled using a zero-truncated distribution. Consequently, in ZA models, the proportion of zeros may be either greater or less than the distribution of the non-zero counts suggests.</p>
<p>The analysis path for ZA models is the same as it is for ZI models. The two components of the model can be contemplated independently of one another, and either a zero-truncated Poisson or negative binomial distribution can be used for the count component.</p>
<p>The <code>pscl</code> library contains the <code>hurdle</code> function for fitting ZA modes. However, in ZA models, the two components are entirely separate from one another, so one doesn’t really need additional specialized software. ZA models could be fit just as readily by bolting together a logistic regression for the hurdle component with a model for zero-truncated responses in the count component. This is not true for ZI models, though. For ZI models, the estimated proportion of false zeros affects the estimate of the intensity for the non-false-zero counts, so the two components cannot be fit separately from one another.</p>
<p>We will use the cod parasite data to illustrate hurdle models also. This is something of an artificial example, however, because the fact that some infected fish will probably yield samples with zero counts suggests that a ZI model has a more natural ecological interpretation. We will proceed directly to the final model chosen by Zuur et al., which includes additive effects of length, year, and area in the intensity component, and an interaction between area and year (but no effect of length) in the hurdle component.</p>
<div class="sourceCode" id="cb636"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb636-1"><a href="generalized-linear-models.html#cb636-1" aria-hidden="true" tabindex="-1"></a>formula<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">formula</span>(Intensity <span class="sc">~</span> Length <span class="sc">+</span> <span class="fu">as.factor</span>(Year) <span class="sc">+</span> <span class="fu">as.factor</span>(Area) <span class="sc">|</span> <span class="fu">as.factor</span>(Year) <span class="sc">*</span> <span class="fu">as.factor</span>(Area))</span>
<span id="cb636-2"><a href="generalized-linear-models.html#cb636-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb636-3"><a href="generalized-linear-models.html#cb636-3" aria-hidden="true" tabindex="-1"></a>cod.hurdle.fm3 <span class="ot">&lt;-</span> <span class="fu">hurdle</span>(formula<span class="fl">.3</span>, <span class="at">data =</span> cod, <span class="at">dist =</span> <span class="st">&quot;negbin&quot;</span>)</span>
<span id="cb636-4"><a href="generalized-linear-models.html#cb636-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cod.hurdle.fm3)</span></code></pre></div>
<pre><code>## 
## Call:
## hurdle(formula = formula.3, data = cod, dist = &quot;negbin&quot;)
## 
## Pearson residuals:
##     Min      1Q  Median      3Q     Max 
## -0.6387 -0.3825 -0.3312 -0.1209 11.9366 
## 
## Count model coefficients (truncated negbin with log link):
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)          3.127498   0.387197   8.077 6.62e-16 ***
## Length              -0.036524   0.005678  -6.432 1.26e-10 ***
## as.factor(Year)2000  0.384774   0.202231   1.903   0.0571 .  
## as.factor(Year)2001 -0.153655   0.198692  -0.773   0.4393    
## as.factor(Area)2     0.404208   0.265277   1.524   0.1276    
## as.factor(Area)3     0.021424   0.231773   0.092   0.9264    
## as.factor(Area)4     1.060123   0.223756   4.738 2.16e-06 ***
## Log(theta)          -1.591345   0.256348  -6.208 5.37e-10 ***
## Zero hurdle model coefficients (binomial with logit link):
##                                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                            0.4456     0.1696   2.627  0.00863 ** 
## as.factor(Year)2000                    0.4454     0.3419   1.303  0.19273    
## as.factor(Year)2001                   -2.6428     0.4330  -6.103 1.04e-09 ***
## as.factor(Area)2                      -1.3241     0.2850  -4.647 3.37e-06 ***
## as.factor(Area)3                      -1.4347     0.2434  -5.893 3.78e-09 ***
## as.factor(Area)4                       0.2622     0.2696   0.972  0.33085    
## as.factor(Year)2000:as.factor(Area)2  -0.1105     0.5071  -0.218  0.82758    
## as.factor(Year)2001:as.factor(Area)2   2.7711     0.5322   5.207 1.92e-07 ***
## as.factor(Year)2000:as.factor(Area)3   0.8392     0.4493   1.868  0.06182 .  
## as.factor(Year)2001:as.factor(Area)3   2.7201     0.4991   5.450 5.05e-08 ***
## as.factor(Year)2000:as.factor(Area)4   0.8393     0.5918   1.418  0.15612    
## as.factor(Year)2001:as.factor(Area)4   2.5794     0.5174   4.985 6.19e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Theta: count = 0.2037
## Number of iterations in BFGS optimization: 21 
## Log-likelihood: -2448 on 20 Df</code></pre>
</div>
</div>
<div id="generalized-additive-models-gams-1" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Generalized additive models (GAMs)<a href="generalized-linear-models.html#generalized-additive-models-gams-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall that splines are essentially just another way of specifying the predictors in a regression model. Generalized additive models (GAMs) are to additive models what generalized linear models are to (general) linear models. In other words, GAMs use splines to create a linear predictor in a GLM that is a smooth function of a covariate.</p>
<p>We illustrate GAMs by considering a data set that gives the size and annual survival of colonies of the stony coral <em>Acropora millepora</em>. (Recall that stony corals are a colonial organism, so here a coral “colony” means a colony of polyps. A colony is what most naive observers would recognize as an individual coral.) We wish to understand how the size of the colony is related to its survival. The size of the colony is measured as planar (top-down) area. The units of area are unclear; perhaps it is m<span class="math inline">\(^2\)</span>? In the data file, the variable “mortality” is a binary response coded as a 0 if the colony survived, and as a 1 if the colony died. The size data have been log-transformed. These data are from <span class="citation">Madin et al. (<a href="#ref-madin2014" role="doc-biblioref">2014</a>)</span>. In R, we fit the GAM with the function <code>mgcv::gam</code>.</p>
<!-- Note: The original data file has size labeled as "ln_area_cm2", but if this is true, some of the colonies would be <0.01 cm^2 in size.  Can this be true?  Goddammit, Josh. -->
<div class="sourceCode" id="cb638"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb638-1"><a href="generalized-linear-models.html#cb638-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(mgcv)</span></code></pre></div>
<pre><code>## Loading required package: mgcv</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## This is mgcv 1.8-42. For overview type &#39;help(&quot;mgcv-package&quot;)&#39;.</code></pre>
<pre><code>## 
## Attaching package: &#39;mgcv&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:VGAM&#39;:
## 
##     s</code></pre>
<div class="sourceCode" id="cb644"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb644-1"><a href="generalized-linear-models.html#cb644-1" aria-hidden="true" tabindex="-1"></a>coral <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/coral.csv&quot;</span>, <span class="at">head =</span> <span class="cn">TRUE</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb644-2"><a href="generalized-linear-models.html#cb644-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coral)</span></code></pre></div>
<pre><code>##              species growth_form   ln_area mortality
## 1 Acropora millepora   corymbose -3.427419         0
## 2 Acropora millepora   corymbose -3.964138         0
## 3 Acropora millepora   corymbose -3.682131         0
## 4 Acropora millepora   corymbose -5.144650         0
## 5 Acropora millepora   corymbose -3.814405         0
## 6 Acropora millepora   corymbose -3.661057         0</code></pre>
<div class="sourceCode" id="cb646"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb646-1"><a href="generalized-linear-models.html#cb646-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(coral, <span class="fu">plot</span>(<span class="fu">jitter</span>(mortality, <span class="at">amount =</span> <span class="fl">0.02</span>) <span class="sc">~</span> ln_area, <span class="at">xlab =</span> <span class="st">&quot;log area&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;mortality&quot;</span>))</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>We fit a GAM with a binomial response, logit link, and use a smoothing spline to capture the relationship between log size and (the log odds of) mortality. Recall that a smoothing spline determines the degree of smoothness by generalized cross-validation.</p>
<div class="sourceCode" id="cb647"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb647-1"><a href="generalized-linear-models.html#cb647-1" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">gam</span>(mortality <span class="sc">~</span> <span class="fu">s</span>(ln_area), <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>), <span class="at">data =</span> coral)</span>
<span id="cb647-2"><a href="generalized-linear-models.html#cb647-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb647-3"><a href="generalized-linear-models.html#cb647-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## 
## Family: binomial 
## Link function: logit 
## 
## Formula:
## mortality ~ s(ln_area)
## 
## Parametric coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.6068     0.1667  -9.636   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##              edf Ref.df Chi.sq p-value   
## s(ln_area) 1.921  2.433  10.52  0.0089 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.0532   Deviance explained = 4.79%
## UBRE = -0.098118  Scale est. = 1         n = 270</code></pre>
<div class="sourceCode" id="cb649"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb649-1"><a href="generalized-linear-models.html#cb649-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot data with fit overlaid</span></span>
<span id="cb649-2"><a href="generalized-linear-models.html#cb649-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb649-3"><a href="generalized-linear-models.html#cb649-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(coral, <span class="fu">plot</span>(<span class="fu">jitter</span>(mortality, <span class="at">amount =</span> <span class="fl">0.02</span>) <span class="sc">~</span> ln_area, <span class="at">xlab =</span> <span class="st">&quot;log area&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;mortality&quot;</span>))</span>
<span id="cb649-4"><a href="generalized-linear-models.html#cb649-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb649-5"><a href="generalized-linear-models.html#cb649-5" aria-hidden="true" tabindex="-1"></a>x.vals <span class="ot">&lt;-</span> <span class="fu">with</span>(coral, <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(ln_area), <span class="at">to =</span> <span class="fu">max</span>(ln_area), <span class="at">length =</span> <span class="dv">100</span>))</span>
<span id="cb649-6"><a href="generalized-linear-models.html#cb649-6" aria-hidden="true" tabindex="-1"></a>fm1.fit <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm1, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">ln_area =</span> x.vals), <span class="at">se =</span> <span class="cn">TRUE</span>)</span>
<span id="cb649-7"><a href="generalized-linear-models.html#cb649-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb649-8"><a href="generalized-linear-models.html#cb649-8" aria-hidden="true" tabindex="-1"></a>inv.logit <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(x) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(x))</span>
<span id="cb649-9"><a href="generalized-linear-models.html#cb649-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb649-10"><a href="generalized-linear-models.html#cb649-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.vals, <span class="fu">inv.logit</span>(fm1.fit<span class="sc">$</span>fit))</span>
<span id="cb649-11"><a href="generalized-linear-models.html#cb649-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.vals, <span class="fu">inv.logit</span>(fm1.fit<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> fm1.fit<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb649-12"><a href="generalized-linear-models.html#cb649-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.vals, <span class="fu">inv.logit</span>(fm1.fit<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> fm1.fit<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/coral-gam-1.png" width="672" /></p>
<p>We might also try a complementary log-log link.</p>
<div class="sourceCode" id="cb650"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb650-1"><a href="generalized-linear-models.html#cb650-1" aria-hidden="true" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> <span class="fu">gam</span>(mortality <span class="sc">~</span> <span class="fu">s</span>(ln_area), <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;cloglog&quot;</span>), <span class="at">data =</span> coral)</span>
<span id="cb650-2"><a href="generalized-linear-models.html#cb650-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb650-3"><a href="generalized-linear-models.html#cb650-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(coral, <span class="fu">plot</span>(<span class="fu">jitter</span>(mortality, <span class="at">amount =</span> <span class="fl">0.02</span>) <span class="sc">~</span> ln_area, <span class="at">xlab =</span> <span class="st">&quot;log area&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;mortality&quot;</span>))</span>
<span id="cb650-4"><a href="generalized-linear-models.html#cb650-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb650-5"><a href="generalized-linear-models.html#cb650-5" aria-hidden="true" tabindex="-1"></a>fm2.fit <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm2, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">ln_area =</span> x.vals), <span class="at">se =</span> <span class="cn">TRUE</span>)</span>
<span id="cb650-6"><a href="generalized-linear-models.html#cb650-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb650-7"><a href="generalized-linear-models.html#cb650-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.vals, <span class="fu">inv.logit</span>(fm2.fit<span class="sc">$</span>fit), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb650-8"><a href="generalized-linear-models.html#cb650-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.vals, <span class="fu">inv.logit</span>(fm2.fit<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> fm2.fit<span class="sc">$</span>se.fit), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb650-9"><a href="generalized-linear-models.html#cb650-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.vals, <span class="fu">inv.logit</span>(fm2.fit<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> fm2.fit<span class="sc">$</span>se.fit), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="07-GeneralizedLinearModels_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<div class="sourceCode" id="cb651"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb651-1"><a href="generalized-linear-models.html#cb651-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fm1, fm2)</span></code></pre></div>
<pre><code>##           df      AIC
## fm1 2.920822 243.5082
## fm2 2.947335 243.0539</code></pre>
<p>The AIC slightly favors the complementary log-log link.</p>

</div>
</div>
<h3>Bibliography<a href="bibliography.html#bibliography" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-madin2014" class="csl-entry">
Madin, Joshua S, Andrew H Baird, Maria Dornelas, and Sean R Connolly. 2014. <span>“Mechanical Vulnerability Explains Size-Dependent Mortality of Reef Corals.”</span> <em>Ecology Letters</em> 17 (8): 1008–15.
</div>
<div id="ref-zuur2009" class="csl-entry">
Zuur, Alain F, Elena N Ieno, Neil J Walker, Anatoly A Saveliev, Graham M Smith, et al. 2009. <em>Mixed Effects Models and Extensions in Ecology with <span>R</span></em>. Vol. 574. Springer.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hierarchical-mixed-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="generalized-linear-mixed-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
