<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Hierarchical (mixed) models | BMA / ST 590 course notes</title>
  <meta name="description" content="This is a proto-textbook for BMA / ST 590, Statistical Modeling in Ecology, taught at NCSU in Fall 2023." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Hierarchical (mixed) models | BMA / ST 590 course notes" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a proto-textbook for BMA / ST 590, Statistical Modeling in Ecology, taught at NCSU in Fall 2023." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Hierarchical (mixed) models | BMA / ST 590 course notes" />
  
  <meta name="twitter:description" content="This is a proto-textbook for BMA / ST 590, Statistical Modeling in Ecology, taught at NCSU in Fall 2023." />
  

<meta name="author" content="Kevin Gross" />


<meta name="date" content="2023-10-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="generalized-least-squares.html"/>
<link rel="next" href="generalized-linear-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Maximum likelihood estimation</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#mathematical-basics"><i class="fa fa-check"></i><b>1.1</b> Mathematical basics</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#horse-kick-data"><i class="fa fa-check"></i><b>1.2</b> Horse-kick data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#calculate-and-plot-the-log-likelihood-function"><i class="fa fa-check"></i><b>1.2.1</b> Calculate and plot the log-likelihood function</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#find-the-mle-numerically-using-optimize"><i class="fa fa-check"></i><b>1.2.2</b> Find the MLE numerically using ‘optimize’</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#pulse-rate-data"><i class="fa fa-check"></i><b>1.3</b> Pulse rate data</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#tadpole-data"><i class="fa fa-check"></i><b>1.4</b> Tadpole data</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#transformable-constraints"><i class="fa fa-check"></i><b>1.5</b> Transformable constraints</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><i class="fa fa-check"></i><b>2</b> Beyond the MLE: Confidence regions and hypothesis tests using the likelihood function</a>
<ul>
<li class="chapter" data-level="2.1" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#confidence-intervals-for-single-parameters"><i class="fa fa-check"></i><b>2.1</b> Confidence intervals for single parameters</a></li>
<li class="chapter" data-level="2.2" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#two-param-mle"><i class="fa fa-check"></i><b>2.2</b> Confidence regions, profile likelihoods, and associated univariate intervals</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#profile-likelihoods"><i class="fa fa-check"></i><b>2.2.1</b> Profile likelihoods</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#locally-quadratic-approximations-to-confidence-intervals-and-regions"><i class="fa fa-check"></i><b>2.3</b> Locally quadratic approximations to confidence intervals and regions</a></li>
<li class="chapter" data-level="2.4" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#comparing-models-likelihood-ratio-test-and-aic"><i class="fa fa-check"></i><b>2.4</b> Comparing models: Likelihood ratio test and AIC</a></li>
<li class="chapter" data-level="2.5" data-path="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html"><a href="beyond-the-mle-confidence-regions-and-hypothesis-tests-using-the-likelihood-function.html#the-negative-binomial-distriution-revisited"><i class="fa fa-check"></i><b>2.5</b> The negative binomial distriution, revisited</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bayesian-computation.html"><a href="bayesian-computation.html"><i class="fa fa-check"></i><b>3</b> Bayesian computation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bayesian-computation.html"><a href="bayesian-computation.html#computations-with-conjugate-priors"><i class="fa fa-check"></i><b>3.1</b> Computations with conjugate priors</a></li>
<li class="chapter" data-level="3.2" data-path="bayesian-computation.html"><a href="bayesian-computation.html#jags-in-r"><i class="fa fa-check"></i><b>3.2</b> JAGS in R</a></li>
<li class="chapter" data-level="3.3" data-path="bayesian-computation.html"><a href="bayesian-computation.html#rstanarm"><i class="fa fa-check"></i><b>3.3</b> rstanarm</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="smooth-regression.html"><a href="smooth-regression.html"><i class="fa fa-check"></i><b>4</b> Smooth regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="smooth-regression.html"><a href="smooth-regression.html#loess-smoothers"><i class="fa fa-check"></i><b>4.1</b> Loess smoothers</a></li>
<li class="chapter" data-level="4.2" data-path="smooth-regression.html"><a href="smooth-regression.html#splines"><i class="fa fa-check"></i><b>4.2</b> Splines</a></li>
<li class="chapter" data-level="4.3" data-path="smooth-regression.html"><a href="smooth-regression.html#GAMs"><i class="fa fa-check"></i><b>4.3</b> Generalized additive models (GAMs)</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="generalized-least-squares.html"><a href="generalized-least-squares.html"><i class="fa fa-check"></i><b>5</b> Generalized Least Squares</a>
<ul>
<li class="chapter" data-level="5.1" data-path="generalized-least-squares.html"><a href="generalized-least-squares.html#heterogeneous-variance"><i class="fa fa-check"></i><b>5.1</b> Heterogeneous variance</a></li>
<li class="chapter" data-level="5.2" data-path="generalized-least-squares.html"><a href="generalized-least-squares.html#temporal-serial-correlation"><i class="fa fa-check"></i><b>5.2</b> Temporal (serial) correlation</a></li>
<li class="chapter" data-level="5.3" data-path="generalized-least-squares.html"><a href="generalized-least-squares.html#spatial-data"><i class="fa fa-check"></i><b>5.3</b> Spatial data</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html"><i class="fa fa-check"></i><b>6</b> Hierarchical (mixed) models</a>
<ul>
<li class="chapter" data-level="6.1" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#one-factor-layout-dyestuff-data"><i class="fa fa-check"></i><b>6.1</b> One-factor layout: Dyestuff data</a></li>
<li class="chapter" data-level="6.2" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#bayesian-analysis"><i class="fa fa-check"></i><b>6.2</b> Bayesian analysis</a></li>
<li class="chapter" data-level="6.3" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#negative-within-group-correlations"><i class="fa fa-check"></i><b>6.3</b> Negative within-group correlations</a></li>
<li class="chapter" data-level="6.4" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#random-coefficient-models-rikz-data"><i class="fa fa-check"></i><b>6.4</b> Random coefficient models: RIKZ data</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#analysis-without-beach-level-covariate"><i class="fa fa-check"></i><b>6.4.1</b> Analysis without beach-level covariate</a></li>
<li class="chapter" data-level="6.4.2" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#adding-a-beach-level-covariate"><i class="fa fa-check"></i><b>6.4.2</b> Adding a beach-level covariate</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#nested-and-crossed-random-effects"><i class="fa fa-check"></i><b>6.5</b> Nested and crossed random effects</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#nested-random-effects"><i class="fa fa-check"></i><b>6.5.1</b> Nested random effects</a></li>
<li class="chapter" data-level="6.5.2" data-path="hierarchical-mixed-models.html"><a href="hierarchical-mixed-models.html#crossed-random-effects"><i class="fa fa-check"></i><b>6.5.2</b> Crossed random effects</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>7</b> Generalized linear models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression"><i class="fa fa-check"></i><b>7.1</b> Poisson regression</a></li>
<li class="chapter" data-level="7.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#bayesian-interlude"><i class="fa fa-check"></i><b>7.2</b> Bayesian interlude</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#rstanarm-1"><i class="fa fa-check"></i><b>7.2.1</b> rstanarm</a></li>
<li class="chapter" data-level="7.2.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#posterior-predictive-checks"><i class="fa fa-check"></i><b>7.2.2</b> Posterior predictive checks</a></li>
<li class="chapter" data-level="7.2.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#jags"><i class="fa fa-check"></i><b>7.2.3</b> JAGS</a></li>
<li class="chapter" data-level="7.2.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#observation-level-random-effects"><i class="fa fa-check"></i><b>7.2.4</b> Observation-level random effects</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#binary-responses"><i class="fa fa-check"></i><b>7.3</b> Binary responses</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#individual-binary-responses-tb-in-boar"><i class="fa fa-check"></i><b>7.3.1</b> Individual binary responses: TB in boar</a></li>
<li class="chapter" data-level="7.3.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#grouped-binary-data-industrial-melanism"><i class="fa fa-check"></i><b>7.3.2</b> Grouped binary data: Industrial melanism</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-adjusted-models-for-count-data"><i class="fa fa-check"></i><b>7.4</b> Zero-adjusted models for count data</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-truncated-models"><i class="fa fa-check"></i><b>7.4.1</b> Zero-truncated models</a></li>
<li class="chapter" data-level="7.4.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-inflated-models"><i class="fa fa-check"></i><b>7.4.2</b> Zero-inflated models</a></li>
<li class="chapter" data-level="7.4.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-altered-or-hurdle-models"><i class="fa fa-check"></i><b>7.4.3</b> Zero-altered, or “hurdle”, models</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#generalized-additive-models-gams"><i class="fa fa-check"></i><b>7.5</b> Generalized additive models (GAMs)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html"><i class="fa fa-check"></i><b>8</b> Generalized linear mixed models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#example-1-industrial-melanism-data"><i class="fa fa-check"></i><b>8.1</b> Example 1: Industrial melanism data</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#gees"><i class="fa fa-check"></i><b>8.1.1</b> GEEs</a></li>
<li class="chapter" data-level="8.1.2" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#glmms"><i class="fa fa-check"></i><b>8.1.2</b> GLMMs</a></li>
<li class="chapter" data-level="8.1.3" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#bayesian-fit"><i class="fa fa-check"></i><b>8.1.3</b> Bayesian fit</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#example-2-ticks-on-red-grouse"><i class="fa fa-check"></i><b>8.2</b> Example 2: Ticks on red grouse</a></li>
<li class="chapter" data-level="8.3" data-path="generalized-linear-mixed-models.html"><a href="generalized-linear-mixed-models.html#GAMMs"><i class="fa fa-check"></i><b>8.3</b> GAMMs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i>Bibliography</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BMA / ST 590 course notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hierarchical-mixed-models" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> Hierarchical (mixed) models<a href="hierarchical-mixed-models.html#hierarchical-mixed-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="one-factor-layout-dyestuff-data" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> One-factor layout: Dyestuff data<a href="hierarchical-mixed-models.html#one-factor-layout-dyestuff-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We will illustrate the basic ideas of hierarchical models with the <code>Dyestuff</code> data contained in <code>lme4</code>. According to Bates (2012+), these data originally appeared in Davies (1947), and “are described in Davies and Goldsmith (1972, Table 6.3, p. 131) … as coming from ‘an investigation to find out how much the variation from batch to bach in the quality of an intermediate product contributes to the variation in the yield of the dyestuff made from it’”. The data consist of 6 batches, each of which gives rise to 5 observations.</p>
<p>Preparatory work:</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="hierarchical-mixed-models.html#cb388-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lme4)</span></code></pre></div>
<pre><code>## Loading required package: lme4</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="hierarchical-mixed-models.html#cb391-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Dyestuff)</span>
<span id="cb391-2"><a href="hierarchical-mixed-models.html#cb391-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Dyestuff)</span></code></pre></div>
<pre><code>##  Batch     Yield     
##  A:5   Min.   :1440  
##  B:5   1st Qu.:1469  
##  C:5   Median :1530  
##  D:5   Mean   :1528  
##  E:5   3rd Qu.:1575  
##  F:5   Max.   :1635</code></pre>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="hierarchical-mixed-models.html#cb393-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(Dyestuff, <span class="fu">stripchart</span>(Yield <span class="sc">~</span> Batch, <span class="at">pch =</span> <span class="dv">16</span>))</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>To develop some notation, let <span class="math inline">\(i = 1, \ldots, 6\)</span> index the batches, let <span class="math inline">\(j = 1, \ldots, 5\)</span> index the observations within each batch, and let <span class="math inline">\(y_{ij}\)</span> denote observation <span class="math inline">\(j\)</span> from batch <span class="math inline">\(i\)</span>.</p>
<p>As a starting point, we will fit the usual one-factor ANOVA model to these data. This model is
<span class="math display">\[\begin{align}
y_{ij} &amp; \sim \mathcal{N}(\mu_i, \sigma^2)
\end{align}\]</span></p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="hierarchical-mixed-models.html#cb394-1" aria-hidden="true" tabindex="-1"></a>fm0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Yield <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> Dyestuff)          <span class="co"># model with common mean</span></span>
<span id="cb394-2"><a href="hierarchical-mixed-models.html#cb394-2" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Yield <span class="sc">~</span> Batch <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span> Dyestuff)  <span class="co"># mean varies by group</span></span>
<span id="cb394-3"><a href="hierarchical-mixed-models.html#cb394-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm0, fm1)  <span class="co"># usual F-test for differences among group means</span></span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Yield ~ 1
## Model 2: Yield ~ Batch - 1
##   Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1     29 115187                                
## 2     24  58830  5     56358 4.5983 0.004398 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="hierarchical-mixed-models.html#cb396-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)  <span class="co"># eliminating the intercept gives sample means for each group</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Yield ~ Batch - 1, data = Dyestuff)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -85.00 -33.00   3.00  31.75  97.00 
## 
## Coefficients:
##        Estimate Std. Error t value Pr(&gt;|t|)    
## BatchA  1505.00      22.14   67.97   &lt;2e-16 ***
## BatchB  1528.00      22.14   69.01   &lt;2e-16 ***
## BatchC  1564.00      22.14   70.64   &lt;2e-16 ***
## BatchD  1498.00      22.14   67.66   &lt;2e-16 ***
## BatchE  1600.00      22.14   72.26   &lt;2e-16 ***
## BatchF  1470.00      22.14   66.39   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 49.51 on 24 degrees of freedom
## Multiple R-squared:  0.9992, Adjusted R-squared:  0.999 
## F-statistic:  4763 on 6 and 24 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now we will use <code>nlme::gls</code> to fit a model that assumes that the data within each batch are correlated. In other words, we fit the model
<span class="math display">\[\begin{align}
y_{ij} &amp; \sim \mathcal{N}(\mu_i, \sigma^2) \\
\mathrm{Corr}(y_{ij}, y_{ik}) &amp; = \rho
\end{align}\]</span></p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="hierarchical-mixed-models.html#cb398-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(nlme)</span></code></pre></div>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## 
## Attaching package: &#39;nlme&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:lme4&#39;:
## 
##     lmList</code></pre>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="hierarchical-mixed-models.html#cb402-1" aria-hidden="true" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> <span class="fu">gls</span>(Yield <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> Dyestuff, <span class="at">correlation =</span> <span class="fu">corCompSymm</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Batch))</span>
<span id="cb402-2"><a href="hierarchical-mixed-models.html#cb402-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm2)</span></code></pre></div>
<pre><code>## Generalized least squares fit by REML
##   Model: Yield ~ 1 
##   Data: Dyestuff 
##        AIC      BIC    logLik
##   325.6543 329.7562 -159.8271
## 
## Correlation Structure: Compound symmetry
##  Formula: ~1 | Batch 
##  Parameter estimate(s):
##       Rho 
## 0.4184874 
## 
## Coefficients:
##              Value Std.Error  t-value p-value
## (Intercept) 1527.5  19.38341 78.80449       0
## 
## Standardized residuals:
##         Min          Q1         Med          Q3         Max 
## -1.34770180 -0.90488550  0.03850577  0.73160955  1.65574793 
## 
## Residual standard error: 64.92534 
## Degrees of freedom: 30 total; 29 residual</code></pre>
<p>The most salient components of this output are the estimate of the overall mean, and the estimate of the within-batch correlation (<span class="math inline">\(\hat{\rho} = 0.42\)</span>).</p>
<p>Now we will fit a hierarchical model that includes a random effect for the batch. We can write the model as
<span class="math display">\[\begin{align}
y_{ij} &amp; \sim \mathcal{N}(B_i, \sigma_\varepsilon^2) \\
B_i &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(\mu, \sigma_B^2).
\end{align}\]</span></p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="hierarchical-mixed-models.html#cb404-1" aria-hidden="true" tabindex="-1"></a>fm3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Yield <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Batch), <span class="at">data =</span> Dyestuff)</span>
<span id="cb404-2"><a href="hierarchical-mixed-models.html#cb404-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm3)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: Yield ~ 1 + (1 | Batch)
##    Data: Dyestuff
## 
## REML criterion at convergence: 319.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.4117 -0.7634  0.1418  0.7792  1.8296 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Batch    (Intercept) 1764     42.00   
##  Residual             2451     49.51   
## Number of obs: 30, groups:  Batch, 6
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  1527.50      19.38    78.8</code></pre>
<p>The estimate of the overall mean is the same as it is in the GLS fit. Note also that we can recover the estimate of the within-batch correlation from the estimates of the variances of the random effects:</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="hierarchical-mixed-models.html#cb406-1" aria-hidden="true" tabindex="-1"></a>var.B   <span class="ot">&lt;-</span> <span class="dv">1764</span></span>
<span id="cb406-2"><a href="hierarchical-mixed-models.html#cb406-2" aria-hidden="true" tabindex="-1"></a>var.eps <span class="ot">&lt;-</span> <span class="dv">2451</span></span>
<span id="cb406-3"><a href="hierarchical-mixed-models.html#cb406-3" aria-hidden="true" tabindex="-1"></a>var.B <span class="sc">/</span> (var.B <span class="sc">+</span> var.eps)</span></code></pre></div>
<pre><code>## [1] 0.4185053</code></pre>
<p>To obtain the conditional modes (BLUPs) of the batch-level random effect, we can use the command <code>ranef</code>:</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="hierarchical-mixed-models.html#cb408-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(fm3)</span></code></pre></div>
<pre><code>## $Batch
##   (Intercept)
## A -17.6068514
## B   0.3912634
## C  28.5622256
## D -23.0845385
## E  56.7331877
## F -44.9952868
## 
## with conditional variances for &quot;Batch&quot;</code></pre>
<p>The conditional modes given here correspond to the differences between the mean for each batch and the overall mean (<span class="math inline">\(\mu\)</span>). To convert these to best guesses for the mean of each batch, we have to the overall mean back. This can be done by using the command <code>fixef</code> to extract the lone fixed-effect estimate from the model:</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="hierarchical-mixed-models.html#cb410-1" aria-hidden="true" tabindex="-1"></a>(batch.conditional.modes <span class="ot">&lt;-</span> (<span class="fu">fixef</span>(fm3) <span class="sc">+</span> <span class="fu">ranef</span>(fm3)<span class="sc">$</span>Batch<span class="sc">$</span><span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>))</span></code></pre></div>
<pre><code>## [1] 1509.893 1527.891 1556.062 1504.415 1584.233 1482.505</code></pre>
<p>It is informative to compare the conditional models for each batch to the sample means. We can calculate the sample means with the <code>tapply</code> function</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="hierarchical-mixed-models.html#cb412-1" aria-hidden="true" tabindex="-1"></a>(batch.means <span class="ot">&lt;-</span> <span class="fu">with</span>(Dyestuff, <span class="fu">tapply</span>(Yield, Batch, mean)))</span></code></pre></div>
<pre><code>##    A    B    C    D    E    F 
## 1505 1528 1564 1498 1600 1470</code></pre>
<p>These are the same as the LS estimates of the batch-specific means in the ANOVA model, <code>fm1</code>. Now plot the sample means against the conditional modes:</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="hierarchical-mixed-models.html#cb414-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(batch.means, batch.conditional.modes)</span></code></pre></div>
<pre><code>##   batch.means batch.conditional.modes
## A        1505                1509.893
## B        1528                1527.891
## C        1564                1556.062
## D        1498                1504.415
## E        1600                1584.233
## F        1470                1482.505</code></pre>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="hierarchical-mixed-models.html#cb416-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x    =</span> batch.means, </span>
<span id="cb416-2"><a href="hierarchical-mixed-models.html#cb416-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y    =</span> batch.conditional.modes, </span>
<span id="cb416-3"><a href="hierarchical-mixed-models.html#cb416-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(batch.means), </span>
<span id="cb416-4"><a href="hierarchical-mixed-models.html#cb416-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">range</span>(batch.means), </span>
<span id="cb416-5"><a href="hierarchical-mixed-models.html#cb416-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;sample means&quot;</span>,</span>
<span id="cb416-6"><a href="hierarchical-mixed-models.html#cb416-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;conditional modes&quot;</span>,</span>
<span id="cb416-7"><a href="hierarchical-mixed-models.html#cb416-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch  =</span> LETTERS[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>])</span>
<span id="cb416-8"><a href="hierarchical-mixed-models.html#cb416-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb416-9"><a href="hierarchical-mixed-models.html#cb416-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> <span class="dv">0</span>, <span class="at">b =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The conditional modes are “shrunken” towards the global mean relative to the sample means. Why is this so?</p>
<p>To conduct inferences about the parameters in the hierarchical model, <code>lme4::lmer</code> offers likelihood profiling. This is the same idea that we encountered when we were using the likelihood to calculate profile-based confidence intervals earlier in the course. <code>lme4::lmer</code> does all its profiling on the ML fit, so we begin by refitting our hierarchical model using ML. To do so, set the optional argument <code>REML</code> to <code>FALSE</code>.</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="hierarchical-mixed-models.html#cb417-1" aria-hidden="true" tabindex="-1"></a>fm3ML <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Yield <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Batch), <span class="at">data =</span> Dyestuff, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb417-2"><a href="hierarchical-mixed-models.html#cb417-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm3ML)</span></code></pre></div>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: Yield ~ 1 + (1 | Batch)
##    Data: Dyestuff
## 
##      AIC      BIC   logLik deviance df.resid 
##    333.3    337.5   -163.7    327.3       27 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.4315 -0.7972  0.1480  0.7721  1.8037 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Batch    (Intercept) 1388     37.26   
##  Residual             2451     49.51   
## Number of obs: 30, groups:  Batch, 6
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  1527.50      17.69   86.33</code></pre>
<p>Switching to ML has decreased our estimate of the batch-level variance, and decreased it by quite a bit. To construct profile-based intervals, we use the <code>lme4::profile</code> function. We will use the <code>xyplot</code> function from the <code>lattice</code> package to display the profiles.</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="hierarchical-mixed-models.html#cb419-1" aria-hidden="true" tabindex="-1"></a>pr <span class="ot">&lt;-</span> <span class="fu">profile</span>(fm3ML)</span>
<span id="cb419-2"><a href="hierarchical-mixed-models.html#cb419-2" aria-hidden="true" tabindex="-1"></a>lattice<span class="sc">::</span><span class="fu">xyplot</span>(pr)</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>There are three panels here, one for each of the parameters in the model. These parameters are labeled as <span class="math inline">\(\sigma_1\)</span> for the standard deviation of the block-level random effect (what we have written <span class="math inline">\(\sigma_B\)</span>), <span class="math inline">\(\sigma\)</span> for the standard deviation of the errors (what we have written as <span class="math inline">\(\sigma_\varepsilon\)</span>), and “(Intercept)” for the global mean (what we have written as <span class="math inline">\(\mu\)</span>).</p>
<p>Within each panel, the values plotted on the vertical axis are the signed square roots of the likelihood ratio test statistic. This value is denoted by the Greek letter <span class="math inline">\(\zeta\)</span> (“zeta”); hence, the plots we are viewing are called zeta-plots.</p>
<p>I do not know how widely used zeta-plots are. They may be more common in other realms of science, although I have never encountered them outside <code>lme4</code>. Basically, they are a visualization of profile-likelihood based confidence intervals. The vertical lines in each panel give the limits of (working from the inside out) 50%, 80%, 90%, 95%, and 99% confidence intervals for each parameter. We can also extract these confidence limits using the <code>confint</code> function. Below, we show 95% confidence intervals; of course, one can change the confidence level as needed.</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="hierarchical-mixed-models.html#cb420-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(pr, <span class="at">level =</span> .<span class="dv">95</span>)</span></code></pre></div>
<pre><code>##                  2.5 %     97.5 %
## .sig01        12.19854   84.06305
## .sigma        38.22998   67.65770
## (Intercept) 1486.45150 1568.54849</code></pre>
<p>So, a 95% confidence interval for <span class="math inline">\(\mu\)</span> ranges from 1486 to 1569.</p>
<p>Here is a bit more about the logic behind zeta plots (feel free to skip this paragraph if you wish). Recall that negative log-likelihood profiles are convex and approximately quadratic. Plotting the LRT statistic instead of the likelihood itself has the effect of placing the nadir of these curves at 0, instead of at the value of the negative log-likelihood. Taking the square root of the LRT statistic converts a quadratic curve (a u-shape) into a linear one (a v-shape). We can see this v-shape by using the optional argument <code>absVal = TRUE</code>:</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="hierarchical-mixed-models.html#cb422-1" aria-hidden="true" tabindex="-1"></a>lattice<span class="sc">::</span><span class="fu">xyplot</span>(pr, <span class="at">absVal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The purpose of using a signed square root is to turn these V-shaped plots into straight lines. Straight lines are useful in turn because if the profile log likelihood is actually quadratic, then the zeta plot will yield a perfectly straight line, and thus a local approximation to the confidence interval will be appropriate. If the zeta-plot is non-linear, then the confidence interval becomes more asymmetric, and a local approximation fares more poorly.</p>
<p>(Start reading again if you skipped the above detail). There is an interesting detail to the zeta-plots. Consider the zeta-plot for <span class="math inline">\(\sigma_1\)</span> (the standard deviation of the batch-level random effects), and try to find the lower limit of a 99% confidence interval. You’ll notice that the zeta-plot hits 0 (the lowest possible value for a standard deviation) before the interval is completed. Thus, the lower limit of this interval is 0:</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="hierarchical-mixed-models.html#cb423-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(pr, <span class="at">level =</span> <span class="fl">0.99</span>)</span></code></pre></div>
<pre><code>##                  0.5 %     99.5 %
## .sig01         0.00000  113.68769
## .sigma        35.56317   75.66803
## (Intercept) 1465.87401 1589.12602</code></pre>
<p>Although we are not much in the habit of conducting hypothesis tests in this course, we would conclude that we would fail to reject the null hypothesis that the batch-level variance equals 0 with a 99% level test.</p>
<p>We can also obtain bivariate confidence regions from the profile likelihood using the <code>lattice::splom</code> command.</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="hierarchical-mixed-models.html#cb425-1" aria-hidden="true" tabindex="-1"></a>lattice<span class="sc">::</span><span class="fu">splom</span>(pr)</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/dyestuff%20bivariate%20confidence%20regions-1.png" width="672" /></p>
<p>Panels above the diagonal show bivariate, profile-based confidence regions for each pair of parameters. Within each panel, we see 50%, 80%, 90%, 95%, and 99% confidence regions. (You should be able to figure out which is which.) The panels show, for example, that the estimate of the observation-level standard deviation is slightly negatively correlated with the estimate of the batch-level standard deviation. Panels below the diagonal show the same plots on the <span class="math inline">\(\zeta\)</span> scale. See Bates (2012+) 1.5.3 for a detailed description of how to interpret these plots.</p>
<p>There is a second approach to calculating confidence intervals and/or conducting hypothesis tests for fixed-effect parameters. Famously, <code>lme4::lmer</code> does not provide degrees of freedom for the estimates of the fixed effects. The package <code>lmerTest</code> uses the Satterthwaite approximation to estimate these df.</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="hierarchical-mixed-models.html#cb426-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lmerTest)</span></code></pre></div>
<pre><code>## Loading required package: lmerTest</code></pre>
<pre><code>## 
## Attaching package: &#39;lmerTest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:lme4&#39;:
## 
##     lmer</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     step</code></pre>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="hierarchical-mixed-models.html#cb431-1" aria-hidden="true" tabindex="-1"></a>fm5 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(Yield <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Batch), <span class="at">data =</span> Dyestuff)</span>
<span id="cb431-2"><a href="hierarchical-mixed-models.html#cb431-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm5)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: Yield ~ 1 + (1 | Batch)
##    Data: Dyestuff
## 
## REML criterion at convergence: 319.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.4117 -0.7634  0.1418  0.7792  1.8296 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Batch    (Intercept) 1764     42.00   
##  Residual             2451     49.51   
## Number of obs: 30, groups:  Batch, 6
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)  1527.50      19.38    5.00    78.8 6.23e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><code>lmerTest::lmer</code> gives the associated df for the estimate of the intercept as 5. If this were a class in experimental design, we would regard the individual measurements from each batch as subsamples, in which case the correct df for inferences about the intercept should be <span class="math inline">\(6 - 1 = 5\)</span>. In this case, the calculation from <code>lmerTest::lmer</code> matches our intuition.</p>
<p>Equipped with this information, we could construct a 95% confidence interval for the overall mean as</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="hierarchical-mixed-models.html#cb433-1" aria-hidden="true" tabindex="-1"></a><span class="fl">1527.5</span> <span class="sc">+</span> <span class="fl">19.38</span> <span class="sc">*</span>  <span class="fu">qt</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">df =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 1477.682 1577.318</code></pre>
<p>Compare this interval with the profile interval generated by <code>lme4::profile</code>.</p>
</div>
<div id="bayesian-analysis" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Bayesian analysis<a href="hierarchical-mixed-models.html#bayesian-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The mixed-model formulation is our first encounter with a hierarchical model. One often hears the phrase “Bayesian hierarchical model” in ecology. It is important to realize that not all Bayesian models are hierarchical, and not all hierarchical models are Bayesian. Indeed, we have seen examples of both: none of the Bayesian examples that we have seen in earlier chapters were hierarchical, and the mixed-model analysis of the Dyestuff data is a hierarchical model analyzed from a frequentist perspective. However, we can certainly analyze hierarchical models from a Bayesian perspective as well, leading to a Bayesian hierarchical model.</p>
<p>The above paragraph begs the question: What defines a hierarchical model? One can find definitions in the literature, though it isn’t clear to me that any of these definitions are fully precise, although I may just be ignorant. As best I can tell, a hierarchical model is one that includes so-called “latent” variables. Latent variables are unobservable quantities on which the data depend, that in turn are related to model parameters via a statistical model. This “layered” construction of the model (observables depend on latent variables, and latent variables depend on model parameters) gives rise to the “hierarchy” that gives hierarchical models their name.</p>
<p>This hierarchical perspective can be emphasized by how the model is written. For the dyestuff data, when we write
<span class="math display">\[\begin{align}
y_{ij} &amp; \sim \mathcal{N}(B_i, \sigma^2_\varepsilon) \\
B_i &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(\mu, \sigma^2_B) \\
\end{align}\]</span></p>
<p>we emphasize that the distribution of the data depends in part on the latent variables <span class="math inline">\(B_i\)</span>, and the distribution of the latent variables depends in turn on some of the model parameters.</p>
<p>To complete the Bayesian specification, we need to place priors on our three parameters: <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma^2_B\)</span>, and <span class="math inline">\(\sigma^2_\varepsilon\)</span>. In the absence of any information, we might choose a vague normal prior for <span class="math inline">\(\mu\)</span>, and vague gamma priors for <span class="math inline">\(1/\sigma^2_B\)</span> and <span class="math inline">\(1/\sigma^2_\varepsilon\)</span>. The following <code>R2Jags</code> code implements such a model.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="hierarchical-mixed-models.html#cb435-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(R2jags)</span></code></pre></div>
<pre><code>## Loading required package: R2jags</code></pre>
<pre><code>## Loading required package: rjags</code></pre>
<pre><code>## Loading required package: coda</code></pre>
<pre><code>## Linked to JAGS 4.3.1</code></pre>
<pre><code>## Loaded modules: basemod,bugs</code></pre>
<pre><code>## 
## Attaching package: &#39;R2jags&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:coda&#39;:
## 
##     traceplot</code></pre>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="hierarchical-mixed-models.html#cb443-1" aria-hidden="true" tabindex="-1"></a>dyestuff.model <span class="ot">&lt;-</span> <span class="cf">function</span>() {</span>
<span id="cb443-2"><a href="hierarchical-mixed-models.html#cb443-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb443-3"><a href="hierarchical-mixed-models.html#cb443-3" aria-hidden="true" tabindex="-1"></a>  <span class="do">## likelihood</span></span>
<span id="cb443-4"><a href="hierarchical-mixed-models.html#cb443-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb443-5"><a href="hierarchical-mixed-models.html#cb443-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>J) {            </span>
<span id="cb443-6"><a href="hierarchical-mixed-models.html#cb443-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb443-7"><a href="hierarchical-mixed-models.html#cb443-7" aria-hidden="true" tabindex="-1"></a>    y[j]    <span class="sc">~</span> <span class="fu">dnorm</span>(B[batch[j]], tau_eps)  <span class="co"># data distribution</span></span>
<span id="cb443-8"><a href="hierarchical-mixed-models.html#cb443-8" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb443-9"><a href="hierarchical-mixed-models.html#cb443-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb443-10"><a href="hierarchical-mixed-models.html#cb443-10" aria-hidden="true" tabindex="-1"></a>  <span class="do">## latent variables</span></span>
<span id="cb443-11"><a href="hierarchical-mixed-models.html#cb443-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb443-12"><a href="hierarchical-mixed-models.html#cb443-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (b <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>){</span>
<span id="cb443-13"><a href="hierarchical-mixed-models.html#cb443-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb443-14"><a href="hierarchical-mixed-models.html#cb443-14" aria-hidden="true" tabindex="-1"></a>    B[b] <span class="sc">~</span> <span class="fu">dnorm</span>(mu, tauB)</span>
<span id="cb443-15"><a href="hierarchical-mixed-models.html#cb443-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb443-16"><a href="hierarchical-mixed-models.html#cb443-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb443-17"><a href="hierarchical-mixed-models.html#cb443-17" aria-hidden="true" tabindex="-1"></a>  mu <span class="sc">~</span> <span class="fu">dnorm</span> (<span class="fl">0.0</span>, <span class="fl">1E-6</span>)  <span class="co"># prior for the overall mean</span></span>
<span id="cb443-18"><a href="hierarchical-mixed-models.html#cb443-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb443-19"><a href="hierarchical-mixed-models.html#cb443-19" aria-hidden="true" tabindex="-1"></a>  tau_eps <span class="sc">~</span> <span class="fu">dgamma</span> (<span class="fl">0.01</span>, <span class="fl">0.01</span>)</span>
<span id="cb443-20"><a href="hierarchical-mixed-models.html#cb443-20" aria-hidden="true" tabindex="-1"></a>  tauB    <span class="sc">~</span> <span class="fu">dgamma</span> (<span class="fl">0.01</span>, <span class="fl">0.01</span>)</span>
<span id="cb443-21"><a href="hierarchical-mixed-models.html#cb443-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb443-22"><a href="hierarchical-mixed-models.html#cb443-22" aria-hidden="true" tabindex="-1"></a>  sd_eps <span class="ot">&lt;-</span> <span class="fu">pow</span>(tau_eps, <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb443-23"><a href="hierarchical-mixed-models.html#cb443-23" aria-hidden="true" tabindex="-1"></a>  sdB    <span class="ot">&lt;-</span> <span class="fu">pow</span>(tauB, <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb443-24"><a href="hierarchical-mixed-models.html#cb443-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb443-25"><a href="hierarchical-mixed-models.html#cb443-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb443-26"><a href="hierarchical-mixed-models.html#cb443-26" aria-hidden="true" tabindex="-1"></a>jags.data <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">y     =</span> Dyestuff<span class="sc">$</span>Yield, </span>
<span id="cb443-27"><a href="hierarchical-mixed-models.html#cb443-27" aria-hidden="true" tabindex="-1"></a>                  <span class="at">batch =</span> <span class="fu">as.numeric</span>(Dyestuff<span class="sc">$</span>Batch), </span>
<span id="cb443-28"><a href="hierarchical-mixed-models.html#cb443-28" aria-hidden="true" tabindex="-1"></a>                  <span class="at">J     =</span> <span class="fu">nrow</span>(Dyestuff))</span>
<span id="cb443-29"><a href="hierarchical-mixed-models.html#cb443-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb443-30"><a href="hierarchical-mixed-models.html#cb443-30" aria-hidden="true" tabindex="-1"></a>jags.params <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;mu&quot;</span>, <span class="st">&quot;sd_eps&quot;</span>, <span class="st">&quot;sdB&quot;</span>, <span class="st">&quot;B[1]&quot;</span>, <span class="st">&quot;B[2]&quot;</span>)</span>
<span id="cb443-31"><a href="hierarchical-mixed-models.html#cb443-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb443-32"><a href="hierarchical-mixed-models.html#cb443-32" aria-hidden="true" tabindex="-1"></a>jags.inits <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb443-33"><a href="hierarchical-mixed-models.html#cb443-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">&quot;mu&quot;</span> <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, .<span class="dv">01</span>), <span class="st">&quot;tauB&quot;</span> <span class="ot">=</span> <span class="fu">runif</span>(<span class="dv">1</span>), <span class="st">&quot;tau_eps&quot;</span> <span class="ot">=</span> <span class="fu">runif</span>(<span class="dv">1</span>))</span>
<span id="cb443-34"><a href="hierarchical-mixed-models.html#cb443-34" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb443-35"><a href="hierarchical-mixed-models.html#cb443-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb443-36"><a href="hierarchical-mixed-models.html#cb443-36" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb443-37"><a href="hierarchical-mixed-models.html#cb443-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb443-38"><a href="hierarchical-mixed-models.html#cb443-38" aria-hidden="true" tabindex="-1"></a>jagsfit <span class="ot">&lt;-</span> <span class="fu">jags</span>(<span class="at">data               =</span> jags.data, </span>
<span id="cb443-39"><a href="hierarchical-mixed-models.html#cb443-39" aria-hidden="true" tabindex="-1"></a>                <span class="at">inits              =</span> jags.inits, </span>
<span id="cb443-40"><a href="hierarchical-mixed-models.html#cb443-40" aria-hidden="true" tabindex="-1"></a>                <span class="at">parameters.to.save =</span> jags.params,</span>
<span id="cb443-41"><a href="hierarchical-mixed-models.html#cb443-41" aria-hidden="true" tabindex="-1"></a>                <span class="at">model.file         =</span> dyestuff.model,</span>
<span id="cb443-42"><a href="hierarchical-mixed-models.html#cb443-42" aria-hidden="true" tabindex="-1"></a>                <span class="at">n.chains           =</span> <span class="dv">3</span>,</span>
<span id="cb443-43"><a href="hierarchical-mixed-models.html#cb443-43" aria-hidden="true" tabindex="-1"></a>                <span class="at">n.iter             =</span> <span class="fl">1e5</span>)</span></code></pre></div>
<pre><code>## module glm loaded</code></pre>
<p>The code above requires a way to associate each observation with the batch from which the observation was drawn. We accomplish this by creating the variable <code>batch</code> that associates each observation with the numerical index of the batch. (That is, batch “A” is associated with the index 1, etc.) In the code, this happens with the line</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="hierarchical-mixed-models.html#cb445-1" aria-hidden="true" tabindex="-1"></a>batch <span class="ot">=</span> <span class="fu">as.numeric</span>(Dyestuff<span class="sc">$</span>Batch)</span></code></pre></div>
<p>The <code>as.numeric</code> command returns numerical values for each level of the factor <code>Batch</code>.</p>
<p>Note also that we have only asked for the posterior draws for the latent means of the first two batches, <span class="math inline">\(B_1\)</span> and <span class="math inline">\(B_2\)</span>. This is merely to keep the output small for this example. We could of course ask for the means of the other batches as well.</p>
<p>Let’s have a look at the output:</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="hierarchical-mixed-models.html#cb446-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(jagsfit)</span></code></pre></div>
<pre><code>## Inference for Bugs model at &quot;C:/Users/krgross/AppData/Local/Temp/RtmpaWLNew/model1d53c7e14772e.txt&quot;, fit using jags,
##  3 chains, each with 1e+05 iterations (first 50000 discarded), n.thin = 50
##  n.sims = 3000 iterations saved
##           mu.vect sd.vect     2.5%      25%      50%      75%    97.5%  Rhat
## B[1]     1513.362  22.375 1471.329 1500.347 1514.592 1527.349 1551.127 1.008
## B[2]     1527.140  21.282 1488.362 1515.118 1527.513 1539.242 1565.028 1.008
## mu       1525.971  23.850 1481.395 1514.107 1526.465 1538.276 1569.052 1.006
## sdB        38.744  26.358    0.269   23.345   36.521   51.151  101.022 1.002
## sd_eps     54.105  12.349   39.388   47.081   52.538   59.337   75.857 1.001
## deviance  323.591   7.099  314.873  318.505  321.822  327.461  337.074 1.001
##          n.eff
## B[1]      3000
## B[2]      1500
## mu        3000
## sdB       3000
## sd_eps    3000
## deviance  3000
## 
## For each parameter, n.eff is a crude measure of effective sample size,
## and Rhat is the potential scale reduction factor (at convergence, Rhat=1).
## 
## DIC info (using the rule, pD = var(deviance)/2)
## pD = 25.2 and DIC = 348.8
## DIC is an estimate of expected predictive error (lower deviance is better).</code></pre>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="hierarchical-mixed-models.html#cb448-1" aria-hidden="true" tabindex="-1"></a><span class="fu">traceplot</span>(jagsfit)  </span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-21-1.png" width="672" /><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-21-2.png" width="672" /><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-21-3.png" width="672" /><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-21-4.png" width="672" /><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-21-5.png" width="672" /><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-21-6.png" width="672" /></p>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="hierarchical-mixed-models.html#cb449-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lattice)</span></code></pre></div>
<pre><code>## Loading required package: lattice</code></pre>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="hierarchical-mixed-models.html#cb451-1" aria-hidden="true" tabindex="-1"></a>jagsfit.mcmc <span class="ot">&lt;-</span> <span class="fu">as.mcmc</span>(jagsfit)</span>
<span id="cb451-2"><a href="hierarchical-mixed-models.html#cb451-2" aria-hidden="true" tabindex="-1"></a><span class="fu">densityplot</span>(jagsfit.mcmc)</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-21-7.png" width="672" /></p>
<p>As of this writing, there are some aspects of the output that I don’t understand. The traceplots show that one chain starts far away from the region of high posterior density and then rapidly converges to it. This behavior seems to persist regardless of how long the burn-in period is, which doesn’t make sense to me. I also do not understand why <code>densityplot</code> produces a 6-by-1 stack of panels instead of a more useful layout.</p>
<p>One especially appealing aspect of analyzing this model from a Bayesian perspective is that there is no awkwardness in analyzing the posterior distributions of the latent variables, namely, the batch-specific means. From the frequentist perspective, it is somewhat awkward (though not prohibitively so) to define the conditional modes (BLUPs). We also lack straightforward methods for quantifying the uncertainty in these conditional modes. From the Bayesian viewpoint, this awkwardness disappears, because the distinction between model parameters and latent variables vanishes. Both are simply unobserved quantities. Consequently, it is natural to summarize our posterior knowledge about the latent variables by their (marginal) posterior distributions, in the same way that we use marginal posteriors to summarize our inferences about the model parameters.</p>
</div>
<div id="negative-within-group-correlations" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Negative within-group correlations<a href="hierarchical-mixed-models.html#negative-within-group-correlations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The hierarchical model formulation, regardless of whether analyzed from a frequentist or Bayesian perspective, is just a model. All models are wrong, but some models are useful. One can encounter grouped data where the hierarchical formulation is not useful. To illustrate, we consider the <code>Dyestuff2</code> data provided in <code>lme4</code>. These are synthetic (fake) data that have been created by Box &amp; Tiao (1973) for the sake of illustration. The Dyestuff2 data have the same structure as the original Dyestuff data, that is, 5 observations from each of 6 batches.</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="hierarchical-mixed-models.html#cb452-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Dyestuff2)</span>
<span id="cb452-2"><a href="hierarchical-mixed-models.html#cb452-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Dyestuff2)</span></code></pre></div>
<pre><code>##  Batch     Yield       
##  A:5   Min.   :-0.892  
##  B:5   1st Qu.: 2.765  
##  C:5   Median : 5.365  
##  D:5   Mean   : 5.666  
##  E:5   3rd Qu.: 8.151  
##  F:5   Max.   :13.434</code></pre>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="hierarchical-mixed-models.html#cb454-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(Dyestuff2, <span class="fu">stripchart</span>(Yield <span class="sc">~</span> Batch, <span class="at">pch =</span> <span class="dv">16</span>))</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>We’ll begin by fitting a GLS model that includes a within-batch correlation:</p>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="hierarchical-mixed-models.html#cb455-1" aria-hidden="true" tabindex="-1"></a>fm6 <span class="ot">&lt;-</span> <span class="fu">gls</span>(Yield <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> Dyestuff2, <span class="at">correlation =</span> <span class="fu">corCompSymm</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Batch))</span>
<span id="cb455-2"><a href="hierarchical-mixed-models.html#cb455-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm6)</span></code></pre></div>
<pre><code>## Generalized least squares fit by REML
##   Model: Yield ~ 1 
##   Data: Dyestuff2 
##        AIC      BIC    logLik
##   167.2092 171.3111 -80.60461
## 
## Correlation Structure: Compound symmetry
##  Formula: ~1 | Batch 
##  Parameter estimate(s):
##        Rho 
## -0.0970284 
## 
## Coefficients:
##              Value Std.Error  t-value p-value
## (Intercept) 5.6656 0.5271409 10.74779       0
## 
## Standardized residuals:
##         Min          Q1         Med          Q3         Max 
## -1.77661357 -0.78584319 -0.08143986  0.67335540  2.10464878 
## 
## Residual standard error: 3.691067 
## Degrees of freedom: 30 total; 29 residual</code></pre>
<p>Notice that the within-batch correlation is negative. What does this imply about the structure of the data?</p>
<p>Let’s have a look at a hierarchical model, fit with <code>lmer</code>.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="hierarchical-mixed-models.html#cb457-1" aria-hidden="true" tabindex="-1"></a>fm6 <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmer</span>(Yield <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Batch), <span class="at">data =</span> Dyestuff2)</span></code></pre></div>
<pre><code>## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="hierarchical-mixed-models.html#cb459-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm6)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: Yield ~ 1 + (1 | Batch)
##    Data: Dyestuff2
## 
## REML criterion at convergence: 161.8
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.7648 -0.7806 -0.0809  0.6689  2.0907 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Batch    (Intercept)  0.00    0.000   
##  Residual             13.81    3.716   
## Number of obs: 30, groups:  Batch, 6
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   5.6656     0.6784   8.352
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<p>The estimate of the among-batch variance, <span class="math inline">\(\sigma^2_B\)</span>, is 0. The warning generated by R tells us that our fit is singular: one of the estimated parameters lies on the boundary of its possible values. To quote Bates (2012+, using our notation):</p>
<blockquote>
<p>“An estimate of 0 for <span class="math inline">\(\sigma_B\)</span> does not mean that there is no variation between the groups. Indeed, … there is some small amount of variability between the groups. The estimate, <span class="math inline">\(\hat{\sigma}_B=0\)</span>, simply indicates that the level of ‘between-group’ variability is not sufficient to warrant incorporating random effects in the model.</p>
</blockquote>
<blockquote>
<p>“The important point … is that we must allow for the estimates of variance components to be zero. We describe such a model as being degenerate, in the sense that it corresponds to a linear model in which we have removed the randdom effects associated with Batch. Degenerate models can and do occur in practice. Eveen when the final fitted model is not degenerate, we must allow for such models when determining the parameter estimates through numerical optimization.”</p>
</blockquote>
<p>Can you think of any ecological mechanisms that might give rise to negative within-group correlations?</p>
</div>
<div id="random-coefficient-models-rikz-data" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Random coefficient models: RIKZ data<a href="hierarchical-mixed-models.html#random-coefficient-models-rikz-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So-called random coefficient models are popular modeling structures in ecology. Random-coefficient models are useful when data are grouped, like the Dyestuff data. However, unlike the Dyestuff data, random-coefficient models refer to scenarios where the statistical model that we want to entertain within each group is more complex than just a simple random sample with a group-specific mean.</p>
<p>To illustrate random-coefficient models, we will consider the RIKZ data from Zuur et al. (2009). These data were first analyzed in an earlier textbook (Zuur et al. 2007). Zuur et al. (2009, p. 101) describe the data as follows:</p>
<blockquote>
<p>“Zuur et al. (2007) used marine benthic data from nine inter-tidal areas along the Dutch coast. The data were collected by the Dutch institute RIKZ in the summer of 2002. In each inter-tidal area (denoted by ‘beach’), five samples were taken, and the macro-fauna and abiotic variables were measured. … The underlying question for these data is whether there is a relationship between species richness, exposure, and NAP (the height of a sampling station compared to mean tidal level). Exposure is an index composed of the following elements: wave action, length of the surf zone, slope, grain size, and the depth of the anaerobic layer.”</p>
</blockquote>
<p>In other words, there are 9 beaches, and 5 samples from each beach. The response, measured at each sample, is the macrofaunal species richness. There are two covariates: NAP, which is a sample-level covariate, and exposure, which is a beach-level covariate. Because species richness is a count variable and includes the occasional zero (and because we have not yet discussed hierarchical models for non-Gaussian responses) we will use the square-root of richness as a variance-stabilizing transformation. Using the square root of species richness as the response has the added benefit of making our analysis different from the analysis in Zuur et al. (2009).</p>
<p>We are going to analyze these data exhaustively, considering various approaches for their analysis and comparing the pros and cons. In our first pass, we will ignore the exposure covariate, and seek only to model the relationship between species richness and NAP. Once that analysis is complete, we will circle back and consider how the analysis changes when we consider the beach-level covariate as well.</p>
<p>Like all data from Zuur et al. (2009), the data are available for download from the book’s associated webpage. We will read in the data and do some housekeeping first.</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="hierarchical-mixed-models.html#cb461-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lme4)</span>
<span id="cb461-2"><a href="hierarchical-mixed-models.html#cb461-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lmerTest)</span>
<span id="cb461-3"><a href="hierarchical-mixed-models.html#cb461-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb461-4"><a href="hierarchical-mixed-models.html#cb461-4" aria-hidden="true" tabindex="-1"></a>rikz <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/RIKZ.txt&quot;</span>, <span class="at">head =</span> T)</span>
<span id="cb461-5"><a href="hierarchical-mixed-models.html#cb461-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb461-6"><a href="hierarchical-mixed-models.html#cb461-6" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(rikz, <span class="fu">plot</span>(Richness <span class="sc">~</span> NAP, <span class="at">pch =</span> Beach))  <span class="co"># raw response; note the non-constant variance</span></span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="hierarchical-mixed-models.html#cb462-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(rikz, <span class="fu">plot</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> NAP, <span class="at">pch =</span> Beach))  <span class="co"># transformation stabilizes the variance</span></span>
<span id="cb462-2"><a href="hierarchical-mixed-models.html#cb462-2" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">leg =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">pch =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>)</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-23-2.png" width="672" /></p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="hierarchical-mixed-models.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="co"># change the Beach variable to a factor</span></span>
<span id="cb463-2"><a href="hierarchical-mixed-models.html#cb463-2" aria-hidden="true" tabindex="-1"></a><span class="co"># would have been better to code the beaches as b1, b2, ...</span></span>
<span id="cb463-3"><a href="hierarchical-mixed-models.html#cb463-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb463-4"><a href="hierarchical-mixed-models.html#cb463-4" aria-hidden="true" tabindex="-1"></a>rikz<span class="sc">$</span>fBeach <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(rikz<span class="sc">$</span>Beach)</span></code></pre></div>
<div id="analysis-without-beach-level-covariate" class="section level3 hasAnchor" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> Analysis without beach-level covariate<a href="hierarchical-mixed-models.html#analysis-without-beach-level-covariate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="using-fixed-effects-for-among-beach-differences" class="section level4 hasAnchor" number="6.4.1.1">
<h4><span class="header-section-number">6.4.1.1</span> Using fixed effects for among-beach differences<a href="hierarchical-mixed-models.html#using-fixed-effects-for-among-beach-differences" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To develop some notation for modeling, let <span class="math inline">\(i=1, \ldots, 9\)</span> index the different beaches, let <span class="math inline">\(j = 1, \ldots, 5\)</span> index the different samples at each beach, let <span class="math inline">\(y_{ij}\)</span> be the square root of the species richness at sample <span class="math inline">\(j\)</span> at beach <span class="math inline">\(i\)</span>, and let <span class="math inline">\(x_{ij}\)</span> be the NAP covariate at sample <span class="math inline">\(j\)</span> at beach <span class="math inline">\(i\)</span>.</p>
<p>In a standard linear models course, we would identify this as a two-factor design with a categorical factor (the beaches) and a numerical factor (NAP). Suppose we wish to characterize the relationship between NAP and (the square root of) species richness, while controlling for differences among the beaches. To do so, we might entertain the additive model
<span class="math display">\[\begin{align*}
y_{ij} &amp; = a_i + b x_{ij} + \varepsilon_{ij} \\
\varepsilon_{ij} &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(0, \sigma_\varepsilon^2).
\end{align*}\]</span></p>
<p>As usual, there are several different ways in which we could write the same model. We might instead write
<span class="math display">\[\begin{align*}
y_{ij} &amp; = \mu_{ij} + \varepsilon_{ij} \\
\mu_{ij} &amp; = a_i + b x_{ij} \\
\varepsilon_{ij} &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(0, \sigma_\varepsilon^2)
\end{align*}\]</span></p>
<p>to emphasize that the mean of each observation (<span class="math inline">\(\mu_{ij}\)</span>) is equal to the sum of a beach-level intercept (<span class="math inline">\(a_i\)</span>) and a common slope times the NAP value (<span class="math inline">\(b x_{ij}\)</span>). Alternatively, we might write
<span class="math display">\[\begin{equation}
y_{ij} \sim \mathcal{N}(a_i + b x_{ij}, \sigma_\varepsilon^2).
\end{equation}\]</span></p>
<p>In any case, the model states that each observation is drawn independently from a Gaussian distribution. The fitted value (or mean) for each datum is determined by a regression line with beach-specific intercepts and a common slope. (The additive model has the same structure has a parallel-lines ANCOVA.) The error variance is the same for all observations.</p>
<p>Let’s fit the model and see what it yields.</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="hierarchical-mixed-models.html#cb464-1" aria-hidden="true" tabindex="-1"></a>fm0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> fBeach <span class="sc">+</span> NAP, <span class="at">data =</span> rikz)</span>
<span id="cb464-2"><a href="hierarchical-mixed-models.html#cb464-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm0)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sqrt(Richness) ~ fBeach + NAP, data = rikz)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.58544 -0.28653 -0.06544  0.23657  1.69043 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.99457    0.26711  11.211 3.92e-13 ***
## fBeach2      0.61544    0.37909   1.623  0.11346    
## fBeach3     -1.21158    0.37491  -3.232  0.00268 ** 
## fBeach4     -1.13596    0.38510  -2.950  0.00564 ** 
## fBeach5     -0.32863    0.38648  -0.850  0.40093    
## fBeach6     -0.90219    0.37835  -2.385  0.02265 *  
## fBeach7     -0.98741    0.39419  -2.505  0.01705 *  
## fBeach8     -0.89080    0.38392  -2.320  0.02628 *  
## fBeach9     -0.79350    0.38561  -2.058  0.04712 *  
## NAP         -0.66410    0.09655  -6.878 5.49e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5882 on 35 degrees of freedom
## Multiple R-squared:  0.7596, Adjusted R-squared:  0.6978 
## F-statistic: 12.29 on 9 and 35 DF,  p-value: 1.744e-08</code></pre>
<p>This analysis gives us an estimate for the common slope (-0.664) and a basis to draw inferences about this slope. For example, we can get a confidence interval in the usual way:</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="hierarchical-mixed-models.html#cb466-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fm0, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                  2.5 %      97.5 %
## (Intercept)  2.4523092  3.53682298
## fBeach2     -0.1541506  1.38502150
## fBeach3     -1.9726894 -0.45047493
## fBeach4     -1.9177509 -0.35416521
## fBeach5     -1.1132200  0.45596483
## fBeach6     -1.6702860 -0.13408870
## fBeach7     -1.7876580 -0.18716421
## fBeach8     -1.6702073 -0.11139365
## fBeach9     -1.5763374 -0.01066776
## NAP         -0.8601180 -0.46808725</code></pre>
<p>We can also use the <code>anova</code> command to test for whether the differences among the beaches are statistically significant, after accounting for the effect of NAP. Note that such a test makes sense in this case, because we have used fixed-effects to capture the differences among the beaches, and thus can carry out inference about these 9 beaches specifically.</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="hierarchical-mixed-models.html#cb468-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm0)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: sqrt(Richness)
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## fBeach     8 21.900  2.7375  7.9109 5.119e-06 ***
## NAP        1 16.370 16.3701 47.3073 5.492e-08 ***
## Residuals 35 12.111  0.3460                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Finally, we can visualize the model by plotting each of the beach-specific fits. We’ll use the R trick of re-fitting the model without the intercept to obtain the beach-specific intercepts directly as model parameters, instead of having to back out those intercepts from the contrasts.</p>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="hierarchical-mixed-models.html#cb470-1" aria-hidden="true" tabindex="-1"></a>fm0.temp <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> fBeach <span class="sc">+</span> NAP <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span> rikz)</span>
<span id="cb470-2"><a href="hierarchical-mixed-models.html#cb470-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fm0.temp)</span></code></pre></div>
<pre><code>##    fBeach1    fBeach2    fBeach3    fBeach4    fBeach5    fBeach6    fBeach7 
##  2.9945661  3.6100015  1.7829839  1.8586080  2.6659385  2.0923787  2.0071550 
##    fBeach8    fBeach9        NAP 
##  2.1037656  2.2010635 -0.6641026</code></pre>
<p>For later comparison, we’ll make a note of the intercept for beach 1, which in this case is 2.995.</p>
<p>Now we’ll proceed to make the plot.</p>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb472-1"><a href="hierarchical-mixed-models.html#cb472-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(rikz, <span class="fu">plot</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> NAP, <span class="at">pch =</span> Beach, <span class="at">main =</span> <span class="st">&quot;Fixed-effects fit, additive model&quot;</span>))</span>
<span id="cb472-2"><a href="hierarchical-mixed-models.html#cb472-2" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">leg =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">pch =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>)</span>
<span id="cb472-3"><a href="hierarchical-mixed-models.html#cb472-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb472-4"><a href="hierarchical-mixed-models.html#cb472-4" aria-hidden="true" tabindex="-1"></a><span class="co"># add a line for each beach</span></span>
<span id="cb472-5"><a href="hierarchical-mixed-models.html#cb472-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb472-6"><a href="hierarchical-mixed-models.html#cb472-6" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">coef</span>(fm0)[<span class="st">&quot;NAP&quot;</span>]</span>
<span id="cb472-7"><a href="hierarchical-mixed-models.html#cb472-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb472-8"><a href="hierarchical-mixed-models.html#cb472-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>){</span>
<span id="cb472-9"><a href="hierarchical-mixed-models.html#cb472-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">a =</span> <span class="fu">coef</span>(fm0.temp)[i], <span class="at">b =</span> b, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>) </span>
<span id="cb472-10"><a href="hierarchical-mixed-models.html#cb472-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Continuing with the fixed-effects analysis, we might also consider a model in which the relationship between NAP and species richness varies among beaches. In other words, we might fit a model with a beach-by-NAP interaction. This model is
<span class="math display">\[\begin{align*}
y_{ij} &amp; \sim \mathcal{N}(a_i + b_i x_{ij}, \sigma_\varepsilon^2).
\end{align*}\]</span></p>
<p>We fit this model in the usual way:</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="hierarchical-mixed-models.html#cb473-1" aria-hidden="true" tabindex="-1"></a>fm0b <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> fBeach <span class="sc">*</span> NAP, <span class="at">data =</span> rikz)</span>
<span id="cb473-2"><a href="hierarchical-mixed-models.html#cb473-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm0b)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sqrt(Richness) ~ fBeach * NAP, data = rikz)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.84831 -0.16080 -0.03091  0.14909  0.98737 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.28835    0.24259  13.555 1.45e-13 ***
## fBeach2      0.30239    0.32158   0.940 0.355394    
## fBeach3     -1.50542    0.31542  -4.773 5.61e-05 ***
## fBeach4     -1.56073    0.33715  -4.629 8.25e-05 ***
## fBeach5      0.11078    0.35432   0.313 0.756947    
## fBeach6     -1.25466    0.31812  -3.944 0.000513 ***
## fBeach7     -1.39537    0.41116  -3.394 0.002144 ** 
## fBeach8     -1.17907    0.32697  -3.606 0.001242 ** 
## fBeach9     -0.85912    0.33879  -2.536 0.017314 *  
## NAP         -0.05077    0.28172  -0.180 0.858319    
## fBeach2:NAP -0.54313    0.36261  -1.498 0.145780    
## fBeach3:NAP -0.47943    0.37104  -1.292 0.207267    
## fBeach4:NAP -0.37552    0.35511  -1.057 0.299666    
## fBeach5:NAP -1.82561    0.38805  -4.705 6.74e-05 ***
## fBeach6:NAP -0.36229    0.33258  -1.089 0.285636    
## fBeach7:NAP -0.48212    0.41379  -1.165 0.254155    
## fBeach8:NAP -0.62429    0.32975  -1.893 0.069089 .  
## fBeach9:NAP -1.01278    0.35527  -2.851 0.008256 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4508 on 27 degrees of freedom
## Multiple R-squared:  0.8911, Adjusted R-squared:  0.8225 
## F-statistic:    13 on 17 and 27 DF,  p-value: 7.079e-09</code></pre>
<p>We can test for whether the differences among the slopes for the beaches are statistically significant with the usual <span class="math inline">\(F\)</span>-test:</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="hierarchical-mixed-models.html#cb475-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm0, fm0b)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: sqrt(Richness) ~ fBeach + NAP
## Model 2: sqrt(Richness) ~ fBeach * NAP
##   Res.Df     RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1     35 12.1113                                
## 2     27  5.4865  8    6.6248 4.0753 0.002742 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We’ll save the model of the beach-specific intercepts and slopes, and use them to visualize the fit. We’ll do the usual trick of refitting the model without the intercept to make it easy to extract the beach-level intercepts and slopes</p>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="hierarchical-mixed-models.html#cb477-1" aria-hidden="true" tabindex="-1"></a>fm0b.temp <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> fBeach <span class="sc">+</span> fBeach<span class="sc">:</span>NAP <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span> rikz)</span>
<span id="cb477-2"><a href="hierarchical-mixed-models.html#cb477-2" aria-hidden="true" tabindex="-1"></a>(fixed.params <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">beach     =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>,</span>
<span id="cb477-3"><a href="hierarchical-mixed-models.html#cb477-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">intercept =</span> <span class="fu">coef</span>(fm0b.temp)[<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>], </span>
<span id="cb477-4"><a href="hierarchical-mixed-models.html#cb477-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">slope     =</span> <span class="fu">coef</span>(fm0b.temp)[<span class="dv">10</span><span class="sc">:</span><span class="dv">18</span>]))</span></code></pre></div>
<pre><code>##         beach intercept       slope
## fBeach1     1  3.288351 -0.05077384
## fBeach2     2  3.590739 -0.59390495
## fBeach3     3  1.782930 -0.53019915
## fBeach4     4  1.727622 -0.42629196
## fBeach5     5  3.399128 -1.87638770
## fBeach6     6  2.033687 -0.41306694
## fBeach7     7  1.892979 -0.53289652
## fBeach8     8  2.109276 -0.67506643
## fBeach9     9  2.429231 -1.06355553</code></pre>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="hierarchical-mixed-models.html#cb479-1" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(fixed.params) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb479-2"><a href="hierarchical-mixed-models.html#cb479-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb479-3"><a href="hierarchical-mixed-models.html#cb479-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(rikz, <span class="fu">plot</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> NAP, <span class="at">pch =</span> Beach, <span class="at">main =</span> <span class="st">&quot;Fixed-effects fit, with beach-NAP interaction&quot;</span>))</span>
<span id="cb479-4"><a href="hierarchical-mixed-models.html#cb479-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">leg =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">pch =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>)</span>
<span id="cb479-5"><a href="hierarchical-mixed-models.html#cb479-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb479-6"><a href="hierarchical-mixed-models.html#cb479-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>){</span>
<span id="cb479-7"><a href="hierarchical-mixed-models.html#cb479-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">a =</span> fixed.params<span class="sc">$</span>intercept[i], <span class="at">b =</span> fixed.params<span class="sc">$</span>slope[i], </span>
<span id="cb479-8"><a href="hierarchical-mixed-models.html#cb479-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>) </span>
<span id="cb479-9"><a href="hierarchical-mixed-models.html#cb479-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
</div>
<div id="using-random-effects-for-among-beach-differences" class="section level4 hasAnchor" number="6.4.1.2">
<h4><span class="header-section-number">6.4.1.2</span> Using random-effects for among-beach differences<a href="hierarchical-mixed-models.html#using-random-effects-for-among-beach-differences" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Now let’s use random effects to capture the differences among beaches. A random effect is appropriate if we want to treat these beaches as a representative sample from a larger collection of beaches, and draw inferences about this larger collection. We’ll start with the additive model again, so that the random beach effect only affects the intercept. Using the notational style of mixed modeling, we could write our model as
<span class="math display">\[\begin{align*}
y_{ij} &amp; \sim \mathcal{N}(A_i + b x_{ij}, \sigma_\varepsilon^2)  \\
A_i &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(a, \sigma_a^2).
\end{align*}\]</span></p>
<p>Here, the <span class="math inline">\(A_i\)</span>’s are the random beach-level intercept.</p>
<p>We’ll fit the model using <code>lmerTest::lmer</code>.</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="hierarchical-mixed-models.html#cb480-1" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> NAP <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> fBeach), <span class="at">data =</span> rikz)</span>
<span id="cb480-2"><a href="hierarchical-mixed-models.html#cb480-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb480-3"><a href="hierarchical-mixed-models.html#cb480-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sqrt(Richness) ~ 1 + NAP + (1 | fBeach)
##    Data: rikz
## 
## REML criterion at convergence: 97.1
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.5693 -0.4286 -0.1869  0.3230  2.9399 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  fBeach   (Intercept) 0.2957   0.5438  
##  Residual             0.3460   0.5882  
## Number of obs: 45, groups:  fBeach, 9
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept)  2.37424    0.20405  8.36034  11.635 1.88e-06 ***
## NAP         -0.68063    0.09501 37.15971  -7.163 1.68e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##     (Intr)
## NAP -0.162</code></pre>
<p>Note that the random-intercepts model includes the parameter <span class="math inline">\(a\)</span>, which is the average intercept across the population of beaches. This is the parameter listed as “(Intercept)” in the fixed-effects portion of the model output above. The model with fixed-effect for the beach-level intercepts has no such parameter. This makes sense, because that model did not envision a larger population of beaches.</p>
<p>We can go further by finding the conditional modes of the intercepts for each beach.</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="hierarchical-mixed-models.html#cb482-1" aria-hidden="true" tabindex="-1"></a>(beach.conditional.modes <span class="ot">&lt;-</span> (<span class="fu">fixef</span>(fm1)[<span class="st">&quot;(Intercept)&quot;</span>] <span class="sc">+</span> <span class="fu">ranef</span>(fm1)<span class="sc">$</span>fBeach<span class="sc">$</span><span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>))</span></code></pre></div>
<pre><code>## [1] 2.870511 3.379324 1.895117 1.963771 2.618721 2.148964 2.088426 2.161791
## [9] 2.241556</code></pre>
<p>In particular, note the conditional mode for the intercept for beach 1, which is 2.871. This conditional mode is shrunken back towards the average intercept, compared to the intercept for this beach in the fixed-effects model.</p>
<p>To visualize the model, we will again make a plot that shows the conditional modes of the fit for each beach. We can also add a line for the average relationship across the population of beaches.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="hierarchical-mixed-models.html#cb484-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(rikz, <span class="fu">plot</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> NAP, <span class="at">pch =</span> Beach, <span class="at">main =</span> <span class="st">&quot;Random intercepts fit&quot;</span>))</span>
<span id="cb484-2"><a href="hierarchical-mixed-models.html#cb484-2" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">leg =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">pch =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>)</span>
<span id="cb484-3"><a href="hierarchical-mixed-models.html#cb484-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb484-4"><a href="hierarchical-mixed-models.html#cb484-4" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(fm1))[<span class="dv">1</span>, <span class="dv">1</span>]</span>
<span id="cb484-5"><a href="hierarchical-mixed-models.html#cb484-5" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(fm1))[<span class="dv">2</span>, <span class="dv">1</span>]</span>
<span id="cb484-6"><a href="hierarchical-mixed-models.html#cb484-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb484-7"><a href="hierarchical-mixed-models.html#cb484-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> a, <span class="at">b =</span> b, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb484-8"><a href="hierarchical-mixed-models.html#cb484-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb484-9"><a href="hierarchical-mixed-models.html#cb484-9" aria-hidden="true" tabindex="-1"></a><span class="co"># make a plot with a line for each beach</span></span>
<span id="cb484-10"><a href="hierarchical-mixed-models.html#cb484-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb484-11"><a href="hierarchical-mixed-models.html#cb484-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>){</span>
<span id="cb484-12"><a href="hierarchical-mixed-models.html#cb484-12" aria-hidden="true" tabindex="-1"></a> <span class="fu">abline</span>(<span class="at">a =</span> beach.conditional.modes[i], <span class="at">b =</span> b, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>) </span>
<span id="cb484-13"><a href="hierarchical-mixed-models.html#cb484-13" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>Though it’s subtle, notice again that the implied fits for each beach have been shrunken back to the overall mean.</p>
<p>Now let’s consider a model that includes both separate intercepts and slopes for each beach, while continuing to model the among-beach differences in both with random effects. In other words, we’ll fit a “random coefficients” model with random intercepts and slopes for each beach. We have two options here. Either we can allow for the random intercept and slope for each beach to be a draw from a bivariate normal distribution with possible correlations, or we can insist that the random intercepts and slopes are independent. To write the first model in mixed-model notation, we might write
<span class="math display">\[\begin{align*}
y_{ij} &amp; \sim \mathcal{N}(A_i + B_i x_{ij}, \sigma_\varepsilon^2) \\
\left(\begin{array}{c} A \\ B \end{array} \right)_i &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}_2 \left(\left(\begin{array}{c} a \\ b \end{array} \right), \left(\begin{array}{cc} \sigma_A^2 &amp; \sigma_{AB} \\ \sigma_{AB} &amp; \sigma_B^2 \end{array} \right) \right).
\end{align*}\]</span></p>
<p>To fit the model using <code>lmerTest::lmer</code>, we use</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="hierarchical-mixed-models.html#cb485-1" aria-hidden="true" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> NAP <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> NAP <span class="sc">|</span> fBeach), <span class="at">data =</span> rikz)  </span>
<span id="cb485-2"><a href="hierarchical-mixed-models.html#cb485-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm2)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sqrt(Richness) ~ 1 + NAP + (1 + NAP | fBeach)
##    Data: rikz
## 
## REML criterion at convergence: 92.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.6245 -0.4430 -0.1095  0.3023  2.1610 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  fBeach   (Intercept) 0.4389   0.6625        
##           NAP         0.1582   0.3978   -0.41
##  Residual             0.2159   0.4647        
## Number of obs: 45, groups:  fBeach, 9
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)   2.4369     0.2348  7.9127  10.379 6.97e-06 ***
## NAP          -0.7026     0.1543  6.7971  -4.552  0.00283 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##     (Intr)
## NAP -0.390</code></pre>
<p>Because this model nests the random-intercept model, we can compare the two directly with a LRT:</p>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="hierarchical-mixed-models.html#cb487-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm1, fm2)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: rikz
## Models:
## fm1: sqrt(Richness) ~ 1 + NAP + (1 | fBeach)
## fm2: sqrt(Richness) ~ 1 + NAP + (1 + NAP | fBeach)
##     npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
## fm1    4 100.83 108.06 -46.416   92.833                     
## fm2    6 101.26 112.10 -44.630   89.259 3.5736  2     0.1675</code></pre>
<p>Interestingly, both the LRT and ANOVA suggest that the random-coefficients model does not provide a statistically significant improvement over the random-intercepts model. In other words, we cannot reject the null hypothesis that <span class="math inline">\(\sigma_B^2 = 0\)</span>.</p>
<p>Alternatively, we could try a model with independent random effects for intercepts and slopes. This model is
<span class="math display">\[\begin{align*}
y_{ij} &amp; \sim \mathcal{N}(A_i + B_i x_{ij}, \sigma_\varepsilon^2) \\
A_i &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(a, \sigma^2_A) \\
B_i &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(b, \sigma^2_B).
\end{align*}\]</span></p>
<p>To fit it in R, we use</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="hierarchical-mixed-models.html#cb490-1" aria-hidden="true" tabindex="-1"></a>fm3 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> NAP <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> fBeach) <span class="sc">+</span> (<span class="dv">0</span> <span class="sc">+</span> NAP <span class="sc">|</span> fBeach), <span class="at">data =</span> rikz)</span>
<span id="cb490-2"><a href="hierarchical-mixed-models.html#cb490-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm3)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sqrt(Richness) ~ 1 + NAP + (1 | fBeach) + (0 + NAP | fBeach)
##    Data: rikz
## 
## REML criterion at convergence: 93.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.5841 -0.4070 -0.1042  0.2804  2.2006 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  fBeach   (Intercept) 0.4247   0.6517  
##  fBeach.1 NAP         0.1489   0.3858  
##  Residual             0.2168   0.4657  
## Number of obs: 45, groups:  fBeach, 9
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)   2.4413     0.2314  7.8858  10.552 6.32e-06 ***
## NAP          -0.6912     0.1510  6.6684  -4.576  0.00289 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##     (Intr)
## NAP -0.061</code></pre>
<p>Because each of these random-effect models are nested within one another, we can compare them directly with LRTs:</p>
<div class="sourceCode" id="cb492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb492-1"><a href="hierarchical-mixed-models.html#cb492-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm1, fm3, fm2)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: rikz
## Models:
## fm1: sqrt(Richness) ~ 1 + NAP + (1 | fBeach)
## fm3: sqrt(Richness) ~ 1 + NAP + (1 | fBeach) + (0 + NAP | fBeach)
## fm2: sqrt(Richness) ~ 1 + NAP + (1 + NAP | fBeach)
##     npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
## fm1    4 100.83 108.06 -46.416   92.833                     
## fm3    5 100.16 109.19 -45.078   90.156 2.6767  1     0.1018
## fm2    6 101.26 112.10 -44.630   89.259 0.8969  1     0.3436</code></pre>
<p>Here we see a conflict between AIC and the LRT. AIC favors the model with random but independent intercepts and slopes, whereas the LRT continues to suggest that we cannot reject the null hypothesis that <span class="math inline">\(\sigma_B^2 = 0\)</span>.</p>
<p>Finally, let’s compare the conditional modes for the intercepts and slopes from model <code>fm3</code> with the beach-specific intercept and slopes from the fixed-effects model.</p>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="hierarchical-mixed-models.html#cb495-1" aria-hidden="true" tabindex="-1"></a>(conditional.modes  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">beach     =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>,</span>
<span id="cb495-2"><a href="hierarchical-mixed-models.html#cb495-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">intercept =</span> <span class="fu">fixef</span>(fm3)[<span class="st">&quot;(Intercept)&quot;</span>] <span class="sc">+</span> <span class="fu">ranef</span>(fm3)<span class="sc">$</span>fBeach<span class="sc">$</span><span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>, </span>
<span id="cb495-3"><a href="hierarchical-mixed-models.html#cb495-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">slope     =</span> <span class="fu">fixef</span>(fm3)[<span class="st">&quot;NAP&quot;</span>] <span class="sc">+</span> <span class="fu">ranef</span>(fm3)<span class="sc">$</span>fBeach<span class="sc">$</span><span class="st">`</span><span class="at">NAP</span><span class="st">`</span>))</span></code></pre></div>
<pre><code>##   beach intercept      slope
## 1     1  3.091736 -0.3225870
## 2     2  3.484038 -0.5930830
## 3     3  1.843949 -0.5776709
## 4     4  1.841492 -0.5218237
## 5     5  3.066017 -1.4310799
## 6     6  2.083390 -0.4693246
## 7     7  2.032495 -0.6452486
## 8     8  2.145453 -0.6869329
## 9     9  2.383348 -0.9728640</code></pre>
<p>Let’s make a scatterplot that compares the fixed-effect estimates to the conditional modes.</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="hierarchical-mixed-models.html#cb497-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb497-2"><a href="hierarchical-mixed-models.html#cb497-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(fixed.params, <span class="fu">plot</span>(slope <span class="sc">~</span> intercept, <span class="at">main =</span> <span class="st">&quot;fixed-effects fit&quot;</span>, <span class="at">pch =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>))</span>
<span id="cb497-3"><a href="hierarchical-mixed-models.html#cb497-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(fixed.params, <span class="fu">plot</span>(slope <span class="sc">~</span> intercept, <span class="at">main =</span> <span class="st">&quot;conditional modes&quot;</span>, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>))</span>
<span id="cb497-4"><a href="hierarchical-mixed-models.html#cb497-4" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(conditional.modes, <span class="fu">points</span>(slope <span class="sc">~</span> intercept, <span class="at">pch =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>))</span>
<span id="cb497-5"><a href="hierarchical-mixed-models.html#cb497-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">fixef</span>(fm3)[<span class="dv">1</span>], <span class="fu">fixef</span>(fm3)[<span class="dv">2</span>], <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>Note, again, that the conditional modes of the intercepts and slopes have shrunk (sometimes substantially) back towards the population means of each. The population means of the intercept and slope are shown by the red dot on the right-hand panel. Finally, we visualize the model by plotting beach-specific “fits”:</p>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="hierarchical-mixed-models.html#cb498-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb498-2"><a href="hierarchical-mixed-models.html#cb498-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(rikz, <span class="fu">plot</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> NAP, <span class="at">pch =</span> Beach, <span class="at">main =</span> <span class="st">&quot;Random-coefficients fit&quot;</span>))</span>
<span id="cb498-3"><a href="hierarchical-mixed-models.html#cb498-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">leg =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">pch =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>)</span>
<span id="cb498-4"><a href="hierarchical-mixed-models.html#cb498-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb498-5"><a href="hierarchical-mixed-models.html#cb498-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>){</span>
<span id="cb498-6"><a href="hierarchical-mixed-models.html#cb498-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">a =</span> conditional.modes<span class="sc">$</span>intercept[i], <span class="at">b =</span> conditional.modes<span class="sc">$</span>slope[i], </span>
<span id="cb498-7"><a href="hierarchical-mixed-models.html#cb498-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>) </span>
<span id="cb498-8"><a href="hierarchical-mixed-models.html#cb498-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb498-9"><a href="hierarchical-mixed-models.html#cb498-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb498-10"><a href="hierarchical-mixed-models.html#cb498-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> <span class="fu">fixef</span>(fm3)[<span class="dv">1</span>], <span class="at">b =</span> <span class="fu">fixef</span>(fm3)[<span class="dv">2</span>], <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
</div>
</div>
<div id="adding-a-beach-level-covariate" class="section level3 hasAnchor" number="6.4.2">
<h3><span class="header-section-number">6.4.2</span> Adding a beach-level covariate<a href="hierarchical-mixed-models.html#adding-a-beach-level-covariate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, we consider the effect of exposure, a beach-level covariate. Exposure is coded in the data set as a numerical predictor. However, there are only three unique values: 8, 10, and 11 (and only one beach has exposure level 8). We will follow Zuur et al. (2009) in treating exposure as a binary predictor, grouping the beaches with exposure levels 8 and 10 together as low exposure beaches.</p>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb499-1"><a href="hierarchical-mixed-models.html#cb499-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create an &#39;exposure&#39; factor, with two levels: low and high</span></span>
<span id="cb499-2"><a href="hierarchical-mixed-models.html#cb499-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb499-3"><a href="hierarchical-mixed-models.html#cb499-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(rikz, <span class="fu">table</span>(fBeach, Exposure))</span></code></pre></div>
<pre><code>##       Exposure
## fBeach 8 10 11
##      1 0  5  0
##      2 5  0  0
##      3 0  0  5
##      4 0  0  5
##      5 0  5  0
##      6 0  0  5
##      7 0  0  5
##      8 0  5  0
##      9 0  5  0</code></pre>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="hierarchical-mixed-models.html#cb501-1" aria-hidden="true" tabindex="-1"></a>rikz<span class="sc">$</span>fExp <span class="ot">&lt;-</span> rikz<span class="sc">$</span>Exposure  <span class="co"># make a new variable so that we can leave the original alone</span></span>
<span id="cb501-2"><a href="hierarchical-mixed-models.html#cb501-2" aria-hidden="true" tabindex="-1"></a>rikz<span class="sc">$</span>fExp[rikz<span class="sc">$</span>Exposure <span class="sc">==</span> <span class="dv">8</span>] <span class="ot">&lt;-</span> <span class="dv">10</span>  <span class="co"># assign a value of 10 to the lone beach with exposure = 8</span></span>
<span id="cb501-3"><a href="hierarchical-mixed-models.html#cb501-3" aria-hidden="true" tabindex="-1"></a>rikz<span class="sc">$</span>fExp <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(rikz<span class="sc">$</span>fExp)  <span class="co"># make the new variable into a factor</span></span>
<span id="cb501-4"><a href="hierarchical-mixed-models.html#cb501-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb501-5"><a href="hierarchical-mixed-models.html#cb501-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rikz)</span></code></pre></div>
<pre><code>##      Sample      Richness         Exposure          NAP              Beach  
##  Min.   : 1   Min.   : 0.000   Min.   : 8.00   Min.   :-1.3360   Min.   :1  
##  1st Qu.:12   1st Qu.: 3.000   1st Qu.:10.00   1st Qu.:-0.3750   1st Qu.:3  
##  Median :23   Median : 4.000   Median :10.00   Median : 0.1670   Median :5  
##  Mean   :23   Mean   : 5.689   Mean   :10.22   Mean   : 0.3477   Mean   :5  
##  3rd Qu.:34   3rd Qu.: 8.000   3rd Qu.:11.00   3rd Qu.: 1.1170   3rd Qu.:7  
##  Max.   :45   Max.   :22.000   Max.   :11.00   Max.   : 2.2550   Max.   :9  
##                                                                             
##      fBeach   fExp   
##  1      : 5   10:25  
##  2      : 5   11:20  
##  3      : 5          
##  4      : 5          
##  5      : 5          
##  6      : 5          
##  (Other):15</code></pre>
<p>We will consider a model in which we use separate distributions of random intercepts for the the low- and high-exposure beaches. To fit this model, we will need to embellish our notation. Now, let <span class="math inline">\(i=1, 2\)</span> index the exposure level of the beaches. Let <span class="math inline">\(j=1,\ldots, n_i\)</span> index the replicate beaches within each exposure level. Let <span class="math inline">\(k=1, \ldots, 5\)</span> index the samples at each beach.</p>
<p>Here we see an interesting consequence of our decision to model the differences among the beaches with either a fixed or random effect. <strong>In order to draw inferences about the effect of low vs. high exposure, we must use a random effect for the beach-to-beach differences.</strong> This makes sense when we reflect upon it. In order to draw inferences about low vs. high exposure, we have to envision separate populations of low and high exposure beaches, and construe the beaches in this experiment as two separate random samples from those populations. If instead we treat the beach-to-beach differences with fixed effects, then we are effectively saying that these are the only low- and high-exposure beaches that we care about. Therefore, in the fixed-effects formulation, these nine beaches are our two populations, and there is no inference to be done.</p>
<p>As above, we will consider a series of three models with various specifications of the random effect. We will consider:</p>
<ul>
<li>A model with random intercepts for the beaches but common slopes within each exposure group</li>
<li>A model with independent random intercepts and slopes for beaches within each exposure group.</li>
<li>A model with random intercepts and slopes for beaches within each exposure group, and potential correlations between them</li>
</ul>
<p>Initially, we fit a model with richly specified fixed effects. In this case, this will mean that the average slope and intercept will vary between the exposure groups.</p>
<p>These models can be written and fit as follows. The random-intercepts model is
<span class="math display">\[\begin{align*}
y_{ijk} &amp; \sim \mathcal{N}(A_{ij} + b_i x_{ijk}, \sigma_\varepsilon^2)\\
A_{ij}  &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(a_i, \sigma^2_A).
\end{align*}\]</span>
We fit this model in R with the code</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="hierarchical-mixed-models.html#cb503-1" aria-hidden="true" tabindex="-1"></a>fm4 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> fExp <span class="sc">*</span> NAP <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> fBeach), <span class="at">data =</span> rikz) </span>
<span id="cb503-2"><a href="hierarchical-mixed-models.html#cb503-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm4)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sqrt(Richness) ~ fExp * NAP + (1 | fBeach)
##    Data: rikz
## 
## REML criterion at convergence: 89.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.4532 -0.5066 -0.0280  0.3478  2.6221 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  fBeach   (Intercept) 0.1395   0.3735  
##  Residual             0.3182   0.5641  
## Number of obs: 45, groups:  fBeach, 9
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)   2.7722     0.2047  7.3111  13.544 1.92e-06 ***
## fExp11       -0.9213     0.3096  7.5513  -2.976   0.0189 *  
## NAP          -0.8580     0.1207 37.7420  -7.110 1.82e-08 ***
## fExp11:NAP    0.3979     0.1818 37.1348   2.189   0.0350 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr) fExp11 NAP   
## fExp11     -0.661              
## NAP        -0.174  0.115       
## fExp11:NAP  0.115 -0.212 -0.664</code></pre>
<p>The model with independent intercepts and slopes can be written as
<span class="math display">\[\begin{align*}
y_{ijk} &amp; \sim \mathcal{N}(A_{ij} + B_{ij} x_{ijk}, \sigma_\varepsilon^2)\\
A_{ij}  &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(a_i, \sigma^2_A) \\
B_{ij}  &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(b_i, \sigma^2_B) .
\end{align*}\]</span>
We fit this model with the code</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="hierarchical-mixed-models.html#cb505-1" aria-hidden="true" tabindex="-1"></a>fm5 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> fExp <span class="sc">*</span> NAP <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> fBeach) <span class="sc">+</span> (<span class="dv">0</span> <span class="sc">+</span> NAP <span class="sc">|</span> fBeach),</span>
<span id="cb505-2"><a href="hierarchical-mixed-models.html#cb505-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> rikz) </span>
<span id="cb505-3"><a href="hierarchical-mixed-models.html#cb505-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm5)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sqrt(Richness) ~ fExp * NAP + (1 | fBeach) + (0 + NAP | fBeach)
##    Data: rikz
## 
## REML criterion at convergence: 85.9
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.70750 -0.40036 -0.01429  0.32923  2.02319 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  fBeach   (Intercept) 0.1783   0.4222  
##  fBeach.1 NAP         0.1476   0.3842  
##  Residual             0.2122   0.4606  
## Number of obs: 45, groups:  fBeach, 9
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)   2.8962     0.2153  7.1463  13.450 2.46e-06 ***
## fExp11       -1.0394     0.3248  7.2622  -3.200  0.01434 *  
## NAP          -0.8618     0.2007  5.7464  -4.295  0.00565 ** 
## fExp11:NAP    0.3904     0.3012  5.7584   1.296  0.24444    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr) fExp11 NAP   
## fExp11     -0.663              
## NAP        -0.062  0.041       
## fExp11:NAP  0.041 -0.090 -0.666</code></pre>
<p>The model with possibly correlated random intercepts and slopes can be written as
<span class="math display">\[\begin{align*}
y_{ijk} &amp; \sim \mathcal{N}(A_{ij} + B_{ij} x_{ijk}, \sigma_\varepsilon^2)\\
\left(\begin{array}{c} A \\ B \end{array} \right)_i &amp; \sim \mathcal{N}_2 \left(\left(\begin{array}{c} a_i \\ b_i \end{array} \right), \left(\begin{array}{cc} \sigma_A^2 &amp; \sigma_{AB} \\ \sigma_{AB} &amp; \sigma_B^2 \end{array} \right) \right).
\end{align*}\]</span></p>
<p>We fit the model in R as follows</p>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="hierarchical-mixed-models.html#cb507-1" aria-hidden="true" tabindex="-1"></a>fm6 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> fExp <span class="sc">*</span> NAP <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> NAP<span class="sc">|</span> fBeach), <span class="at">data =</span> rikz)  </span>
<span id="cb507-2"><a href="hierarchical-mixed-models.html#cb507-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm6)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sqrt(Richness) ~ fExp * NAP + (1 + NAP | fBeach)
##    Data: rikz
## 
## REML criterion at convergence: 85.8
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.70561 -0.39766 -0.01305  0.32821  2.02192 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr
##  fBeach   (Intercept) 0.1767   0.4203       
##           NAP         0.1464   0.3826   0.05
##  Residual             0.2125   0.4610       
## Number of obs: 45, groups:  fBeach, 9
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)   2.8956     0.2146  6.9871  13.494 2.93e-06 ***
## fExp11       -1.0389     0.3237  7.0837  -3.210  0.01462 *  
## NAP          -0.8588     0.2001  5.6602  -4.292  0.00587 ** 
## fExp11:NAP    0.3874     0.3003  5.6586   1.290  0.24724    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr) fExp11 NAP   
## fExp11     -0.663              
## NAP        -0.026  0.017       
## fExp11:NAP  0.017 -0.054 -0.666</code></pre>
<p>Because these models form a series of nested models, we can use LRTs or AIC to find the most parsimonious fit.</p>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb509-1"><a href="hierarchical-mixed-models.html#cb509-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm4, fm5, fm6)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: rikz
## Models:
## fm4: sqrt(Richness) ~ fExp * NAP + (1 | fBeach)
## fm5: sqrt(Richness) ~ fExp * NAP + (1 | fBeach) + (0 + NAP | fBeach)
## fm6: sqrt(Richness) ~ fExp * NAP + (1 + NAP | fBeach)
##     npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
## fm4    6 94.275 105.11 -41.137   82.275                     
## fm5    7 94.418 107.06 -40.209   80.418 1.8565  1     0.1730
## fm6    8 96.373 110.83 -40.186   80.373 0.0454  1     0.8312</code></pre>
<p>Both AIC and the LRT suggest that the model with only random intercepts provides the most parsimonious fit. Let’s take a closer look at that fit</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="hierarchical-mixed-models.html#cb512-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm4)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sqrt(Richness) ~ fExp * NAP + (1 | fBeach)
##    Data: rikz
## 
## REML criterion at convergence: 89.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.4532 -0.5066 -0.0280  0.3478  2.6221 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  fBeach   (Intercept) 0.1395   0.3735  
##  Residual             0.3182   0.5641  
## Number of obs: 45, groups:  fBeach, 9
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)   2.7722     0.2047  7.3111  13.544 1.92e-06 ***
## fExp11       -0.9213     0.3096  7.5513  -2.976   0.0189 *  
## NAP          -0.8580     0.1207 37.7420  -7.110 1.82e-08 ***
## fExp11:NAP    0.3979     0.1818 37.1348   2.189   0.0350 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr) fExp11 NAP   
## fExp11     -0.661              
## NAP        -0.174  0.115       
## fExp11:NAP  0.115 -0.212 -0.664</code></pre>
<p>We can analyze the fixed-effects as follows. Based on the contrasts R has used, the low exposure beaches are the baseline; thus the values for the “Intercept” and “NAP” coefficients give the intercept and slope for low-exposure beaches. The values of the “fExp11” and “fExp11:NAP” coefficients (resp.) give the differences of the intercepts and slopes (resp.) between the high vs. low exposure beaches. Thus the negative value of the “NAP” coefficient suggests that species richness declines as NAP increases at low-exposure beaches. The positive coefficient for the “fExp11:NAP” interaction suggests that species richness declines more gradually with increasing NAP at high-exposure beaches as compared to low-exposure beaches. Because we have analyzed the square-root transform of the response, it is hard to assign any biological meaning to the magnitudes of the coefficients. This is one downside of using a transformation to stabilize the variance in the response.</p>
<p>We’ll visualize the model with a plot.</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="hierarchical-mixed-models.html#cb514-1" aria-hidden="true" tabindex="-1"></a>a0 <span class="ot">&lt;-</span> <span class="fu">fixef</span>(fm4)[<span class="dv">1</span>]  <span class="co"># mean intercept for low-exposure beaches</span></span>
<span id="cb514-2"><a href="hierarchical-mixed-models.html#cb514-2" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">fixef</span>(fm4)[<span class="dv">2</span>]  <span class="co"># mean slope for low-exposure beaches</span></span>
<span id="cb514-3"><a href="hierarchical-mixed-models.html#cb514-3" aria-hidden="true" tabindex="-1"></a>a1 <span class="ot">&lt;-</span> <span class="fu">fixef</span>(fm4)[<span class="dv">3</span>]  <span class="co"># difference in mean intercepts for high vs low </span></span>
<span id="cb514-4"><a href="hierarchical-mixed-models.html#cb514-4" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="fu">fixef</span>(fm4)[<span class="dv">4</span>]  <span class="co"># difference in mean slopes for high vs low</span></span>
<span id="cb514-5"><a href="hierarchical-mixed-models.html#cb514-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-6"><a href="hierarchical-mixed-models.html#cb514-6" aria-hidden="true" tabindex="-1"></a>c.mode <span class="ot">&lt;-</span> <span class="fu">ranef</span>(fm4)<span class="sc">$</span>fBeach</span>
<span id="cb514-7"><a href="hierarchical-mixed-models.html#cb514-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-8"><a href="hierarchical-mixed-models.html#cb514-8" aria-hidden="true" tabindex="-1"></a>low.beaches <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">9</span>) <span class="co"># indices of the low-exposure beaches</span></span>
<span id="cb514-9"><a href="hierarchical-mixed-models.html#cb514-9" aria-hidden="true" tabindex="-1"></a>high.beaches <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">7</span>) <span class="co"># indices of the high-exposure beacues</span></span>
<span id="cb514-10"><a href="hierarchical-mixed-models.html#cb514-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-11"><a href="hierarchical-mixed-models.html#cb514-11" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))  <span class="co"># split the plot region</span></span>
<span id="cb514-12"><a href="hierarchical-mixed-models.html#cb514-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-13"><a href="hierarchical-mixed-models.html#cb514-13" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(rikz, <span class="fu">plot</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> NAP, </span>
<span id="cb514-14"><a href="hierarchical-mixed-models.html#cb514-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">type     =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb514-15"><a href="hierarchical-mixed-models.html#cb514-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">main     =</span> <span class="st">&quot;Exposure = 8 or 10&quot;</span>))  <span class="co"># set up the axes</span></span>
<span id="cb514-16"><a href="hierarchical-mixed-models.html#cb514-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-17"><a href="hierarchical-mixed-models.html#cb514-17" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">subset</span>(rikz, fExp <span class="sc">==</span> <span class="st">&quot;10&quot;</span>), <span class="fu">points</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> NAP, <span class="at">pch =</span> Beach))  <span class="co"># plot points for low exposure beaches</span></span>
<span id="cb514-18"><a href="hierarchical-mixed-models.html#cb514-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-19"><a href="hierarchical-mixed-models.html#cb514-19" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> a0, <span class="at">b =</span> b0, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)  <span class="co"># add the average line for low-exposure beaches</span></span>
<span id="cb514-20"><a href="hierarchical-mixed-models.html#cb514-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-21"><a href="hierarchical-mixed-models.html#cb514-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(low.beaches)) {</span>
<span id="cb514-22"><a href="hierarchical-mixed-models.html#cb514-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb514-23"><a href="hierarchical-mixed-models.html#cb514-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">a =</span> a0 <span class="sc">+</span> c.mode[low.beaches[i], <span class="dv">1</span>], <span class="at">b =</span> b0, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span>
<span id="cb514-24"><a href="hierarchical-mixed-models.html#cb514-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb514-25"><a href="hierarchical-mixed-models.html#cb514-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-26"><a href="hierarchical-mixed-models.html#cb514-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Repeat for high exposure beaches</span></span>
<span id="cb514-27"><a href="hierarchical-mixed-models.html#cb514-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-28"><a href="hierarchical-mixed-models.html#cb514-28" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(rikz, <span class="fu">plot</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> NAP, </span>
<span id="cb514-29"><a href="hierarchical-mixed-models.html#cb514-29" aria-hidden="true" tabindex="-1"></a>                <span class="at">type     =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb514-30"><a href="hierarchical-mixed-models.html#cb514-30" aria-hidden="true" tabindex="-1"></a>                <span class="at">main     =</span> <span class="st">&quot;Exposure = 11&quot;</span>))  <span class="co"># set up the axes</span></span>
<span id="cb514-31"><a href="hierarchical-mixed-models.html#cb514-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-32"><a href="hierarchical-mixed-models.html#cb514-32" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">subset</span>(rikz, fExp <span class="sc">==</span> <span class="st">&quot;11&quot;</span>), <span class="fu">points</span>(<span class="fu">sqrt</span>(Richness) <span class="sc">~</span> NAP, <span class="at">pch =</span> Beach))  <span class="co"># plot points for low exposure beaches</span></span>
<span id="cb514-33"><a href="hierarchical-mixed-models.html#cb514-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-34"><a href="hierarchical-mixed-models.html#cb514-34" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> a0 <span class="sc">+</span> a1, <span class="at">b =</span> b0 <span class="sc">+</span> b1, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)  <span class="co"># add the average line for low-exposure beaches</span></span>
<span id="cb514-35"><a href="hierarchical-mixed-models.html#cb514-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb514-36"><a href="hierarchical-mixed-models.html#cb514-36" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(high.beaches)) {</span>
<span id="cb514-37"><a href="hierarchical-mixed-models.html#cb514-37" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb514-38"><a href="hierarchical-mixed-models.html#cb514-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">a =</span> a0 <span class="sc">+</span> a1 <span class="sc">+</span> c.mode[high.beaches[i], <span class="dv">1</span>], <span class="at">b =</span> b0 <span class="sc">+</span> b1, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span>
<span id="cb514-39"><a href="hierarchical-mixed-models.html#cb514-39" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<!-- Finally, we'll fit a model in which the slope does not depend on exposure, just for comparison.  That is, we entertain the model -->
<!-- \begin{align*} -->
<!-- y_{ijk} & = A_{ij} + b x_{ijk} + \varepsilon_{ijk} \\ -->
<!-- A_{ij} & \sim \mathcal{N}(a_i, \sigma^2_A) \\ -->
<!-- \varepsilon_{ijk} & \stackrel{\text{iid}}{\sim} \mathcal{N}(0, \sigma_\varepsilon^2). -->
<!-- \end{align*} -->
<!-- ```{r} -->
<!-- fm5 <- lmerTest::lmer(sqrt(Richness) ~ 1 + NAP + fExp + (1 | fBeach), data = rikz) -->
<!-- a0 <- coef(summary(fm5))[1, 1]  # marginal intercept for low-exposure beaches -->
<!-- b0 <- coef(summary(fm5))[2, 1]  # common slope for all beaches -->
<!-- a1 <- coef(summary(fm5))[3, 1]  # difference in marginal intercepts for high vs low  -->
<!-- c.mode <- ranef(fm5)$fBeach -->
<!-- # this code is ugly, but oh well -->
<!-- par(mfrow = c(1, 2))  # split the plot region -->
<!-- with(rikz, plot(sqrt(Richness) ~ NAP,  -->
<!--                 type     = "n",  -->
<!--                 main     = "Exposure = 8 or 10"))  # set up the axes -->
<!-- with(subset(rikz, fExp == "10"), points(sqrt(Richness) ~ NAP, pch = Beach))  # plot points for low exposure beaches -->
<!-- abline(a = a0, b = b0, col = "red", lwd = 2)  # add the average line for low-exposure beaches -->
<!-- for (i in 1:length(low.beaches)) { -->
<!--   abline(a = a0 + c.mode[low.beaches[i], 1], b = b0, col = "red", lty = "dotted") -->
<!-- } -->
<!-- # Repeat for high exposure beaches -->
<!-- with(rikz, plot(sqrt(Richness) ~ NAP,  -->
<!--                 type     = "n",  -->
<!--                 main     = "Exposure = 11"))  # set up the axes -->
<!-- with(subset(rikz, fExp == "11"), points(sqrt(Richness) ~ NAP, pch = Beach))  # plot points for low exposure beaches -->
<!-- abline(a = a0 + a1, b = b0, col = "blue", lwd = 2)  # add the average line for low-exposure beaches -->
<!-- for (i in 1:length(high.beaches)) { -->
<!--   abline(a = a0 + a1 + c.mode[high.beaches[i], 1], b = b0, col = "blue", lty = "dotted") -->
<!-- } -->
<!-- # we want a model where the variance of the random beach effects differs between low vs. high exposure beaches. -->
<!-- # how do we do that?? -->
<!-- ``` -->
</div>
</div>
<div id="nested-and-crossed-random-effects" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Nested and crossed random effects<a href="hierarchical-mixed-models.html#nested-and-crossed-random-effects" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="nested-random-effects" class="section level3 hasAnchor" number="6.5.1">
<h3><span class="header-section-number">6.5.1</span> Nested random effects<a href="hierarchical-mixed-models.html#nested-random-effects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A major advantage of the <code>lme4::lmer</code> software is that it allows nested and crossed random effects. We will look first at an example of nested random effects. These data come from a study by Yates (1935), as reported in Venables &amp; Ripley (Modern Applied Statistics with S, 4e, 2002). They are found in the <code>MASS</code> library as the <code>oats</code> data. The description in the help documentation states:</p>
<blockquote>
<p>The yield of oats from a split-plot field trial using three varieties and four levels of manurial treatment. The experiment was laid out in 6 blocks of 3 main plots, each split into 4 sub-plots. The varieties were applied to the main plots and the manurial treatments to the sub-plots.</p>
</blockquote>
<p>Let’s first take a look at the data.</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb515-1"><a href="hierarchical-mixed-models.html#cb515-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb515-2"><a href="hierarchical-mixed-models.html#cb515-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb515-3"><a href="hierarchical-mixed-models.html#cb515-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb515-4"><a href="hierarchical-mixed-models.html#cb515-4" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lme4)</span>
<span id="cb515-5"><a href="hierarchical-mixed-models.html#cb515-5" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lmerTest)</span>
<span id="cb515-6"><a href="hierarchical-mixed-models.html#cb515-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb515-7"><a href="hierarchical-mixed-models.html#cb515-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(oats)</span>
<span id="cb515-8"><a href="hierarchical-mixed-models.html#cb515-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(oats)</span></code></pre></div>
<pre><code>##    B                V           N            Y        
##  I  :12   Golden.rain:24   0.0cwt:18   Min.   : 53.0  
##  II :12   Marvellous :24   0.2cwt:18   1st Qu.: 86.0  
##  III:12   Victory    :24   0.4cwt:18   Median :102.5  
##  IV :12                    0.6cwt:18   Mean   :104.0  
##  V  :12                                3rd Qu.:121.2  
##  VI :12                                Max.   :174.0</code></pre>
<p>The variables are (respectively) [B]lock, [V]ariety, [N]itrogen (the manure), and the [Y]ield, in units of 1/4lbs, according to the help documentation.</p>
<p>To develop notation, let <span class="math inline">\(i = 1, \ldots, 3\)</span> index the three varieties, let <span class="math inline">\(j = 1, \ldots, 4\)</span> index the four manure treatments, and let <span class="math inline">\(k = 1, \ldots, 6\)</span> index the blocks. We wish to entertain the usual model for a split-plot design with a blocking factor at the whole-plot level:</p>
<p><span class="math display">\[\begin{align}
y_{ijk} &amp; \sim \mathcal{N}(\mu_{ij} + B_k + W_{ik}, \sigma^2_\varepsilon) \\
B_k  &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(0, \sigma^2_B) \\
W_{ik}  &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(0, \sigma^2_W).
\end{align}\]</span></p>
<p>Here, <span class="math inline">\(\mu_{ij}\)</span> is the average response for the combination of variety <span class="math inline">\(i\)</span> and manure treatment <span class="math inline">\(j\)</span>; the <span class="math inline">\(B_k\)</span> are the random effects for the blocks, the <span class="math inline">\(W_{ik}\)</span> are the whole-plot errors, and the <span class="math inline">\(\varepsilon_{ijk}\)</span> are the split-plot (observation-level) errors. We proceed to fit the model using <code>lmerTest::lmer</code>. A key to the coding here is to notice that each combination of block and variety uniquely specifies one of the 18 whole plots. (In other words, variety is not replicated within the blocks.) Therefore, we can code the whole-plot random effect as <code>(1 | B : V)</code>, which creats a random effect for each unique combination of block and variety. The rest of the model coding is straightforward.</p>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb517-1"><a href="hierarchical-mixed-models.html#cb517-1" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(Y <span class="sc">~</span> V <span class="sc">*</span> N <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> B) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> B <span class="sc">:</span> V), <span class="at">data =</span> oats)</span>
<span id="cb517-2"><a href="hierarchical-mixed-models.html#cb517-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb517-3"><a href="hierarchical-mixed-models.html#cb517-3" aria-hidden="true" tabindex="-1"></a><span class="co"># for nested random effects, lmer provides the coding shortcut  </span></span>
<span id="cb517-4"><a href="hierarchical-mixed-models.html#cb517-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb517-5"><a href="hierarchical-mixed-models.html#cb517-5" aria-hidden="true" tabindex="-1"></a>fm1a <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(Y <span class="sc">~</span> V <span class="sc">*</span> N <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> B <span class="sc">/</span> V), <span class="at">data =</span> oats)</span>
<span id="cb517-6"><a href="hierarchical-mixed-models.html#cb517-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb517-7"><a href="hierarchical-mixed-models.html#cb517-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: Y ~ V * N + (1 | B) + (1 | B:V)
##    Data: oats
## 
## REML criterion at convergence: 529
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.81301 -0.56145  0.01758  0.63865  1.57034 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  B:V      (Intercept) 106.1    10.30   
##  B        (Intercept) 214.5    14.65   
##  Residual             177.1    13.31   
## Number of obs: 72, groups:  B:V, 18; B, 6
## 
## Fixed effects:
##                     Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)          80.0000     9.1070 16.0816   8.784 1.55e-07 ***
## VMarvellous           6.6667     9.7150 30.2308   0.686   0.4978    
## VVictory             -8.5000     9.7150 30.2308  -0.875   0.3885    
## N0.2cwt              18.5000     7.6829 45.0000   2.408   0.0202 *  
## N0.4cwt              34.6667     7.6829 45.0000   4.512 4.58e-05 ***
## N0.6cwt              44.8333     7.6829 45.0000   5.835 5.48e-07 ***
## VMarvellous:N0.2cwt   3.3333    10.8653 45.0000   0.307   0.7604    
## VVictory:N0.2cwt     -0.3333    10.8653 45.0000  -0.031   0.9757    
## VMarvellous:N0.4cwt  -4.1667    10.8653 45.0000  -0.383   0.7032    
## VVictory:N0.4cwt      4.6667    10.8653 45.0000   0.430   0.6696    
## VMarvellous:N0.6cwt  -4.6667    10.8653 45.0000  -0.430   0.6696    
## VVictory:N0.6cwt      2.1667    10.8653 45.0000   0.199   0.8428    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) VMrvll VVctry N0.2cw N0.4cw N0.6cw VM:N0.2 VV:N0.2 VM:N0.4
## VMarvellous -0.533                                                           
## VVictory    -0.533  0.500                                                    
## N0.2cwt     -0.422  0.395  0.395                                             
## N0.4cwt     -0.422  0.395  0.395  0.500                                      
## N0.6cwt     -0.422  0.395  0.395  0.500  0.500                               
## VMrvll:N0.2  0.298 -0.559 -0.280 -0.707 -0.354 -0.354                        
## VVctry:N0.2  0.298 -0.280 -0.559 -0.707 -0.354 -0.354  0.500                 
## VMrvll:N0.4  0.298 -0.559 -0.280 -0.354 -0.707 -0.354  0.500   0.250         
## VVctry:N0.4  0.298 -0.280 -0.559 -0.354 -0.707 -0.354  0.250   0.500   0.500 
## VMrvll:N0.6  0.298 -0.559 -0.280 -0.354 -0.354 -0.707  0.500   0.250   0.500 
## VVctry:N0.6  0.298 -0.280 -0.559 -0.354 -0.354 -0.707  0.250   0.500   0.250 
##             VV:N0.4 VM:N0.6
## VMarvellous                
## VVictory                   
## N0.2cwt                    
## N0.4cwt                    
## N0.6cwt                    
## VMrvll:N0.2                
## VVctry:N0.2                
## VMrvll:N0.4                
## VVctry:N0.4                
## VMrvll:N0.6  0.250         
## VVctry:N0.6  0.500   0.500</code></pre>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb519-1"><a href="hierarchical-mixed-models.html#cb519-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm1)</span></code></pre></div>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##      Sum Sq Mean Sq NumDF DenDF F value    Pr(&gt;F)    
## V     526.1   263.0     2    10  1.4853    0.2724    
## N   20020.5  6673.5     3    45 37.6857 2.458e-12 ***
## V:N   321.8    53.6     6    45  0.3028    0.9322    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We proceed to analyze the fixed effects in the usual fashion, noting first that the variety-by-nitrogen interaction is not significant. We then proceed to inspect the <span class="math inline">\(F\)</span>-tests of the fixed effects, and see that the marginal means for the manure treatment are significantly different, but there are no significant differences among the marginal means for the three varieties.</p>
<p>Note that it would be incorrect to have coded the model as</p>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb521-1"><a href="hierarchical-mixed-models.html#cb521-1" aria-hidden="true" tabindex="-1"></a>fm1.wrong <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(Y <span class="sc">~</span> V <span class="sc">*</span> N <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> B) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> V), <span class="at">data =</span> oats)</span></code></pre></div>
<p>as this would have treated the random effects for block and variety as crossed, not nested.</p>
<p>To complete the analysis, we should notice that the levels of the nitrogen treatment correspond to equally spaced values of a numerical covariate. We can thus extract the polynomial trends by assigning polynomial contrasts to the nitrogen treatment.</p>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb522-1"><a href="hierarchical-mixed-models.html#cb522-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(oats<span class="sc">$</span>N) <span class="ot">&lt;-</span> <span class="fu">contr.poly</span>(<span class="at">n =</span> <span class="dv">4</span>)</span>
<span id="cb522-2"><a href="hierarchical-mixed-models.html#cb522-2" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(Y <span class="sc">~</span> V <span class="sc">*</span> N <span class="sc">+</span>  (<span class="dv">1</span> <span class="sc">|</span> B) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> B <span class="sc">:</span> V), <span class="at">data =</span> oats)</span>
<span id="cb522-3"><a href="hierarchical-mixed-models.html#cb522-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb522-4"><a href="hierarchical-mixed-models.html#cb522-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: Y ~ V * N + (1 | B) + (1 | B:V)
##    Data: oats
## 
## REML criterion at convergence: 533.2
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.81301 -0.56145  0.01758  0.63865  1.57034 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  B:V      (Intercept) 106.1    10.30   
##  B        (Intercept) 214.5    14.65   
##  Residual             177.1    13.31   
## Number of obs: 72, groups:  B:V, 18; B, 6
## 
## Fixed effects:
##                 Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept)     104.5000     7.7976   8.8688  13.402 3.45e-07 ***
## VMarvellous       5.2917     7.0789  10.0000   0.748    0.472    
## VVictory         -6.8750     7.0789  10.0000  -0.971    0.354    
## N.L              33.6901     5.4327  45.0000   6.201 1.57e-07 ***
## N.Q              -4.1667     5.4327  45.0000  -0.767    0.447    
## N.C              -0.8199     5.4327  45.0000  -0.151    0.881    
## VMarvellous:N.L  -4.8075     7.6829  45.0000  -0.626    0.535    
## VVictory:N.L      2.5715     7.6829  45.0000   0.335    0.739    
## VMarvellous:N.Q  -1.9167     7.6829  45.0000  -0.249    0.804    
## VVictory:N.Q     -1.0833     7.6829  45.0000  -0.141    0.888    
## VMarvellous:N.C   3.9877     7.6829  45.0000   0.519    0.606    
## VVictory:N.C     -2.8696     7.6829  45.0000  -0.374    0.711    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) VMrvll VVctry N.L    N.Q    N.C    VM:N.L VV:N.L VM:N.Q
## VMarvellous -0.454                                                        
## VVictory    -0.454  0.500                                                 
## N.L          0.000  0.000  0.000                                          
## N.Q          0.000  0.000  0.000  0.000                                   
## N.C          0.000  0.000  0.000  0.000  0.000                            
## VMrvlls:N.L  0.000  0.000  0.000 -0.707  0.000  0.000                     
## VVictry:N.L  0.000  0.000  0.000 -0.707  0.000  0.000  0.500              
## VMrvlls:N.Q  0.000  0.000  0.000  0.000 -0.707  0.000  0.000  0.000       
## VVictry:N.Q  0.000  0.000  0.000  0.000 -0.707  0.000  0.000  0.000  0.500
## VMrvlls:N.C  0.000  0.000  0.000  0.000  0.000 -0.707  0.000  0.000  0.000
## VVictry:N.C  0.000  0.000  0.000  0.000  0.000 -0.707  0.000  0.000  0.000
##             VV:N.Q VM:N.C
## VMarvellous              
## VVictory                 
## N.L                      
## N.Q                      
## N.C                      
## VMrvlls:N.L              
## VVictry:N.L              
## VMrvlls:N.Q              
## VVictry:N.Q              
## VMrvlls:N.C  0.000       
## VVictry:N.C  0.000  0.500</code></pre>
<p>We see that only the linear trend of the nitrogen treatment is significant. Let’s make a quick plot to visualize this effect.</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="hierarchical-mixed-models.html#cb524-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(oats, <span class="fu">plot</span>(Y <span class="sc">~</span> N))</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
</div>
<div id="crossed-random-effects" class="section level3 hasAnchor" number="6.5.2">
<h3><span class="header-section-number">6.5.2</span> Crossed random effects<a href="hierarchical-mixed-models.html#crossed-random-effects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To illustrate crossed random effects, we will model players’ scores from the 2018 US Open golf tournament. This data set includes scores for all 136 players who competed in the tournament. All players participated in the first two days of the tournament. Players who had a sufficiently low (good) total score from those first two days qualified to compete in the next two days. Players who with a high (poor) total score from the first two days were disqualified or “cut” from the tournament.</p>
<p>To develop notation, let <span class="math inline">\(i=1, \ldots, 136\)</span> index the players, and let <span class="math inline">\(j = 1, \ldots, 4\)</span> index the days. We seek to fit the model
<span class="math display">\[\begin{align}
y_{ij} &amp; \sim \mathcal{N}(\mu + A_i + B_j, \sigma^2_\varepsilon) \\
A_i  &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(0, \sigma^2_A) \\
B_j  &amp; \stackrel{\text{iid}}{\sim} \mathcal{N}(0, \sigma^2_B).
\end{align}\]</span></p>
<p>In this model, <span class="math inline">\(\mu\)</span> is the average score, <span class="math inline">\(A_i\)</span> are the player-level random effects, <span class="math inline">\(B_j\)</span> are the day-level random effects, and <span class="math inline">\(\varepsilon_{ij}\)</span> are the observation-level errors. Note that because each player played at most once in each day, there is no possibility to separate a possible player-by-day interaction (also a random effect) from the observation-level error. If the players had played multiple rounds in a given day, we could have tried to separate the player-by-day random effect from the observation-level error. We fit the model in <code>lmerTest::lmer</code>.</p>
<div class="sourceCode" id="cb525"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb525-1"><a href="hierarchical-mixed-models.html#cb525-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb525-2"><a href="hierarchical-mixed-models.html#cb525-2" aria-hidden="true" tabindex="-1"></a>golf <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/golf.txt&quot;</span>, <span class="at">head =</span> T)</span>
<span id="cb525-3"><a href="hierarchical-mixed-models.html#cb525-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb525-4"><a href="hierarchical-mixed-models.html#cb525-4" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(score <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> player) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> round), <span class="at">data =</span> golf)</span>
<span id="cb525-5"><a href="hierarchical-mixed-models.html#cb525-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb525-6"><a href="hierarchical-mixed-models.html#cb525-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)  <span class="co"># comparison of the std devs of the random effects is interesting</span></span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: score ~ 1 + (1 | player) + (1 | round)
##    Data: golf
## 
## REML criterion at convergence: 2130.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.6856 -0.6669 -0.0515  0.5825  4.5577 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  player   (Intercept)  0.5059  0.7113  
##  round    (Intercept)  3.1513  1.7752  
##  Residual             11.2507  3.3542  
## Number of obs: 400, groups:  player, 136; round, 4
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)  74.2631     0.9081  3.0093   81.78  3.9e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>It is interesting to compare the standard deviations of the random effects. It is also interesting to use the profile function to see the asymmetry in the confidence intervals for these standard deviations.</p>
<div class="sourceCode" id="cb527"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb527-1"><a href="hierarchical-mixed-models.html#cb527-1" aria-hidden="true" tabindex="-1"></a>pp.golf <span class="ot">&lt;-</span> <span class="fu">profile</span>(fm1)</span>
<span id="cb527-2"><a href="hierarchical-mixed-models.html#cb527-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb527-3"><a href="hierarchical-mixed-models.html#cb527-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(pp.golf)</span></code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## .sig01       0.0000000  1.551146
## .sig02       0.8129721  3.837297
## .sigma       3.0513011  3.666234
## (Intercept) 72.2434040 76.265786</code></pre>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb529-1"><a href="hierarchical-mixed-models.html#cb529-1" aria-hidden="true" tabindex="-1"></a>lattice<span class="sc">::</span><span class="fu">xyplot</span>(pp.golf, <span class="at">absVal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>We can also extract the conditional modes for the players and rounds.</p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="hierarchical-mixed-models.html#cb530-1" aria-hidden="true" tabindex="-1"></a>player.modes <span class="ot">&lt;-</span> <span class="fu">ranef</span>(fm1)<span class="sc">$</span>player</span>
<span id="cb530-2"><a href="hierarchical-mixed-models.html#cb530-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(player.modes)</span></code></pre></div>
<pre><code>##             (Intercept)
## Akiyoshi      0.3983034
## Aphibarnrat  -0.3069054
## Axley        -0.0142805
## Babcock       0.1920115
## Baddeley     -0.1925652
## Berger       -0.4212456</code></pre>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="hierarchical-mixed-models.html#cb532-1" aria-hidden="true" tabindex="-1"></a>(round.modes <span class="ot">&lt;-</span> <span class="fu">ranef</span>(fm1)<span class="sc">$</span>round)</span></code></pre></div>
<pre><code>##     (Intercept)
## rd1   1.7211234
## rd2  -0.9012137
## rd3   1.1661848
## rd4  -1.9860945</code></pre>
<p>According to Wikipedia, on day 1 “conditions were extremely difficult as gusty winds hung around all day with sunny skies, making the course firm and fast.” This corresponds with the large conditional mode for round 1.</p>
<p>Finally, it is interesting to compare the conditional modes for the players who qualified to play in rounds 3 and 4, vs. the players who were “cut”.</p>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="hierarchical-mixed-models.html#cb534-1" aria-hidden="true" tabindex="-1"></a>player.stats <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">name =</span> <span class="fu">row.names</span>(player.modes),</span>
<span id="cb534-2"><a href="hierarchical-mixed-models.html#cb534-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">mode =</span> player.modes[, <span class="dv">1</span>],</span>
<span id="cb534-3"><a href="hierarchical-mixed-models.html#cb534-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">rds  =</span> <span class="fu">with</span>(golf, <span class="fu">as.numeric</span>(<span class="fu">table</span>(player))))</span>
<span id="cb534-4"><a href="hierarchical-mixed-models.html#cb534-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb534-5"><a href="hierarchical-mixed-models.html#cb534-5" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(player.stats, <span class="fu">stripchart</span>(mode <span class="sc">~</span> <span class="fu">as.factor</span>(rds), <span class="at">method =</span> <span class="st">&quot;jitter&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;rounds played&quot;</span>, </span>
<span id="cb534-6"><a href="hierarchical-mixed-models.html#cb534-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">xlab =</span> <span class="st">&quot;conditional mode&quot;</span>, <span class="at">pch =</span> <span class="dv">1</span>))</span></code></pre></div>
<p><img src="06-HierarchicalModels_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>Interestingly, some players who qualified to play in rounds 3 and 4 ended up with higher (worse) conditional modes than some of the players who were “cut”. We might infer that these players played above their abilities on days 1 and 2.</p>
<p><img src="images/sports-comic.png" /><!-- --></p>
<p>Thanks to xkcd for the perspective.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="generalized-least-squares.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="generalized-linear-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
